/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.reporteditor.tree.dialogs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

public final class UnistallReportWizardVisualPanel1 extends JPanel {

    /**
     * Creates new form UnistallReportWizardVisualPanel1
     */
    public UnistallReportWizardVisualPanel1() {
        initComponents();
        chDisablePublications.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(final ActionEvent e) {
                chRemovePublications.setSelected(!chDisablePublications.isSelected());
                chEnablePublications.setSelected(!chDisablePublications.isSelected());
            }
        });
        chRemovePublications.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(final ActionEvent e) {
                chDisablePublications.setSelected(!chRemovePublications.isSelected());
                chEnablePublications.setSelected(!chRemovePublications.isSelected());
            }
        });
        chEnablePublications.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(final ActionEvent e) {
                chDisablePublications.setSelected(!chEnablePublications.isSelected());
                chRemovePublications.setSelected(!chEnablePublications.isSelected());
            }
        });
    }

    @Override
    public String getName() {
        return "Select the required action";
    }

    void setup(final UnistallReportWizardWizardPanel1 panel) {
        if (UnistallReportWizardWizardPanel1.ACTION_CLEAR.equals(panel.getAction())) {
            chRemovePublications.setSelected(true);
            chDisablePublications.setSelected(false);
            chEnablePublications.setSelected(false);
        } else if (UnistallReportWizardWizardPanel1.ACTION_DISABLE.equals(panel.getAction())) {
            chDisablePublications.setSelected(true);
            chRemovePublications.setSelected(false);
            chEnablePublications.setSelected(false);
        } else {
            chEnablePublications.setSelected(true);
            chDisablePublications.setSelected(false);
            chRemovePublications.setSelected(false);
        }
    }

    void store(final UnistallReportWizardWizardPanel1 panel) {
        if (chDisablePublications.isSelected()) {
            panel.setAction(UnistallReportWizardWizardPanel1.ACTION_DISABLE);
        } else if (chRemovePublications.isSelected()) {
            panel.setAction(UnistallReportWizardWizardPanel1.ACTION_CLEAR);
        } else {
            panel.setAction(UnistallReportWizardWizardPanel1.ACTION_ENABLE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chDisablePublications = new javax.swing.JRadioButton();
        chRemovePublications = new javax.swing.JRadioButton();
        chEnablePublications = new javax.swing.JRadioButton();

        org.openide.awt.Mnemonics.setLocalizedText(chDisablePublications, org.openide.util.NbBundle.getMessage(UnistallReportWizardVisualPanel1.class, "UnistallReportWizardVisualPanel1.chDisablePublications.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(chRemovePublications, org.openide.util.NbBundle.getMessage(UnistallReportWizardVisualPanel1.class, "UnistallReportWizardVisualPanel1.chRemovePublications.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(chEnablePublications, org.openide.util.NbBundle.getMessage(UnistallReportWizardVisualPanel1.class, "UnistallReportWizardVisualPanel1.chEnablePublications.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chDisablePublications)
                    .addComponent(chRemovePublications)
                    .addComponent(chEnablePublications))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chDisablePublications)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chEnablePublications)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chRemovePublications)
                .addContainerGap(204, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton chDisablePublications;
    private javax.swing.JRadioButton chEnablePublications;
    private javax.swing.JRadioButton chRemovePublications;
    // End of variables declaration//GEN-END:variables
}
