/*
 * Copyright (c) 2008-2016, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */
 
package org.radixware.kernel.utils.wia;

public enum EHResult {

	//Common values
	S_OK(0x00000000,"Operation successful"),
	E_ABORT(0x80004004,"Operation aborted"),
	E_ACCESSDENIED(0x80070005,"General access denied error"),
	E_FAIL(0x80004005,"Unspecified failure"),
	E_HANDLE(0x80070006,"Handle that is not valid"),
	E_INVALIDARG(0x80070057,"One or more arguments are not valid"),
	E_NOINTERFACE(0x80004002,"No such interface supported"),
	E_NOTIMPL(0x80004001,"Not implemented"),
	E_OUTOFMEMORY(0x8007000E,"Failed to allocate necessary memory"),
	E_POINTER(0x80004003,"Pointer that is not valid"),
	E_UNEXPECTED(0x8000FFFF,"Unexpected failure"),
	
	//COM values			
	E_PENDING(0x8000000A,"The data necessary to complete this operation is not yet available."),
	E_BOUNDS(0x8000000B,"The operation attempted to access data outside the valid range"),
	E_CHANGED_STATE(0x8000000C,"A concurrent or interleaved operation changed the state of the object, invalidating this operation."),
	E_ILLEGAL_STATE_CHANGE(0x8000000D,"An illegal state change was requested."),
	E_ILLEGAL_METHOD_CALL(0x8000000E,"A method was called at an unexpected time."),
	RO_E_METADATA_NAME_NOT_FOUND(0x8000000F,"Typename or Namespace was not found in metadata file."),
	RO_E_METADATA_NAME_IS_NAMESPACE(0x80000010,"Name is an existing namespace rather than a typename."),
	RO_E_METADATA_INVALID_TYPE_FORMAT(0x80000011,"Typename has an invalid format."),
	RO_E_INVALID_METADATA_FILE(0x80000012,"Metadata file is invalid or corrupted."),
	RO_E_CLOSED(0x80000013,"The object has been closed."),
	RO_E_EXCLUSIVE_WRITE(0x80000014,"Only one thread may access the object during a write operation."),
	RO_E_CHANGE_NOTIFICATION_IN_PROGRESS(0x80000015,"Operation is prohibited during change notification."),
	RO_E_ERROR_STRING_NOT_FOUND(0x80000016,"The text associated with this error code could not be found."),
	E_STRING_NOT_NULL_TERMINATED(0x80000017,"String not null terminated."),
	E_ILLEGAL_DELEGATE_ASSIGNMENT(0x80000018,"A delegate was assigned when not allowed."),
	E_ASYNC_OPERATION_NOT_STARTED(0x80000019,"An async operation was not properly started."),
	E_APPLICATION_EXITING(0x8000001A,"The application is exiting and cannot service this request."),
	E_APPLICATION_VIEW_EXITING(0x8000001B,"The application view is exiting and cannot service this request."),
	RO_E_MUST_BE_AGILE(0x8000001C,"The object must support the IAgileObject interface."),
	RO_E_UNSUPPORTED_FROM_MTA(0x8000001D,"Activating a single-threaded class from MTA is not supported."),
	RO_E_COMMITTED(0x8000001E,"The object has been committed."),
	CO_E_INIT_TLS(0x80004006,"Thread local storage failure"),
	CO_E_INIT_SHARED_ALLOCATOR(0x80004007,"Get shared memory allocator failure"),
	CO_E_INIT_MEMORY_ALLOCATOR(0x80004008,"Get memory allocator failure"),
	CO_E_INIT_CLASS_CACHE(0x80004009,"Unable to initialize class cache"),
	CO_E_INIT_RPC_CHANNEL(0x8000400A,"Unable to initialize RPC services"),
	CO_E_INIT_TLS_SET_CHANNEL_CONTROL(0x8000400B,"Cannot set thread local storage channel control"),
	CO_E_INIT_TLS_CHANNEL_CONTROL(0x8000400C,"Could not allocate thread local storage channel control"),
	CO_E_INIT_UNACCEPTED_USER_ALLOCATOR(0x8000400D,"The user supplied memory allocator is unacceptable"),
	CO_E_INIT_SCM_MUTEX_EXISTS(0x8000400E,"The OLE service mutex already exists"),
	CO_E_INIT_SCM_FILE_MAPPING_EXISTS(0x8000400F,"The OLE service file mapping already exists"),
	CO_E_INIT_SCM_MAP_VIEW_OF_FILE(0x80004010,"Unable to map view of file for OLE service"),
	CO_E_INIT_SCM_EXEC_FAILURE(0x80004011,"Failure attempting to launch OLE service"),
	CO_E_INIT_ONLY_SINGLE_THREADED(0x80004012,"There was an attempt to call CoInitialize a second time while single threaded"),
	CO_E_CANT_REMOTE(0x80004013,"A Remote activation was necessary but was not allowed"),
	CO_E_BAD_SERVER_NAME(0x80004014,"A Remote activation was necessary but the server name provided was invalid"),
	CO_E_WRONG_SERVER_IDENTITY(0x80004015,"The class is configured to run as a security id different from the caller"),
	CO_E_OLE1DDE_DISABLED(0x80004016,"Use of Ole1 services requiring DDE windows is disabled"),
	CO_E_RUNAS_SYNTAX(0x80004017,"A RunAs specification must be <domain name>\\<user name> or simply <user name>."),
	CO_E_CREATEPROCESS_FAILURE(0x80004018,"The server process could not be started. The pathname may be incorrect."),
	CO_E_RUNAS_CREATEPROCESS_FAILURE(0x80004019,"The server process could not be started as the configured identity. The pathname may be incorrect or unavailable."),
	CO_E_RUNAS_LOGON_FAILURE(0x8000401A,"The server process could not be started because the configured identity is incorrect. Check the user name and password."),
	CO_E_LAUNCH_PERMSSION_DENIED(0x8000401B,"The client is not allowed to launch this server."),
	CO_E_START_SERVICE_FAILURE(0x8000401C,"The service providing this server could not be started."),
	CO_E_REMOTE_COMMUNICATION_FAILURE(0x8000401D,"This computer was unable to communicate with the computer providing the server."),
	CO_E_SERVER_START_TIMEOUT(0x8000401E,"The server did not respond after being launched."),
	CO_E_CLSREG_INCONSISTENT(0x8000401F,"The registration information for this server is inconsistent or incomplete."),
	CO_E_IIDREG_INCONSISTENT(0x80004020,"The registration information for this interface is inconsistent or incomplete."),
	CO_E_NOT_SUPPORTED(0x80004021,"The operation attempted is not supported."),
	CO_E_RELOAD_DLL(0x80004022,"A dll must be loaded."),
	CO_E_MSI_ERROR(0x80004023,"A Microsoft Software Installer error was encountered."),
	CO_E_ATTEMPT_TO_CREATE_OUTSIDE_CLIENT_CONTEXT(0x80004024,"The specified activation could not occur in the client context as specified."),
	CO_E_SERVER_PAUSED(0x80004025,"Activations on the server are paused."),
	CO_E_SERVER_NOT_PAUSED(0x80004026,"Activations on the server are not paused."),
	CO_E_CLASS_DISABLED(0x80004027,"The component or application containing the component has been disabled."),
	CO_E_CLRNOTAVAILABLE(0x80004028,"The common language runtime is not available"),
	CO_E_ASYNC_WORK_REJECTED(0x80004029,"The thread-pool rejected the submitted asynchronous work."),
	CO_E_SERVER_INIT_TIMEOUT(0x8000402A,"The server started, but did not finish initializing in a timely fashion."),
	CO_E_NO_SECCTX_IN_ACTIVATE(0x8000402B,"Unable to complete the call since there is no COM+ security context inside IObjectControl.Activate."),
	CO_E_TRACKER_CONFIG(0x80004030,"The provided tracker configuration is invalid"),
	CO_E_THREADPOOL_CONFIG(0x80004031,"The provided thread pool configuration is invalid"),
	CO_E_SXS_CONFIG(0x80004032,"The provided side-by-side configuration is invalid"),
	CO_E_MALFORMED_SPN(0x80004033,"The server principal name (SPN) obtained during security negotiation is malformed."),
	OLE_E_OLEVERB(0x80040000,"Invalid OLEVERB structure"),
	OLE_E_ADVF(0x80040001,"Invalid advise flags"),
	OLE_E_ENUM_NOMORE(0x80040002,"Can't enumerate any more, because the associated data is missing"),
	OLE_E_ADVISENOTSUPPORTED(0x80040003,"This implementation doesn't take advises"),
	OLE_E_NOCONNECTION(0x80040004,"There is no connection for this connection ID"),
	OLE_E_NOTRUNNING(0x80040005,"Need to run the object to perform this operation"),
	OLE_E_NOCACHE(0x80040006,"There is no cache to operate on"),
	OLE_E_BLANK(0x80040007,"Uninitialized object"),
	OLE_E_CLASSDIFF(0x80040008,"Linked object's source class has changed"),
	OLE_E_CANT_GETMONIKER(0x80040009,"Not able to get the moniker of the object"),
	OLE_E_CANT_BINDTOSOURCE(0x8004000A,"Not able to bind to the source"),
	OLE_E_STATIC(0x8004000B,"Object is static; operation not allowed"),
	OLE_E_PROMPTSAVECANCELLED(0x8004000C,"User canceled out of save dialog"),
	OLE_E_INVALIDRECT(0x8004000D,"Invalid rectangle"),
	OLE_E_WRONGCOMPOBJ(0x8004000E,"compobj.dll is too old for the ole2.dll initialized"),
	OLE_E_INVALIDHWND(0x8004000F,"Invalid window handle"),
	OLE_E_NOT_INPLACEACTIVE(0x80040010,"Object is not in any of the inplace active states"),
	OLE_E_CANTCONVERT(0x80040011,"Not able to convert object"),
	OLE_E_NOSTORAGE(0x80040012,"Not able to perform the operation because object is not given storage yet"),
	DV_E_FORMATETC(0x80040064,"Invalid FORMATETC structure"),
	DV_E_DVTARGETDEVICE(0x80040065,"Invalid DVTARGETDEVICE structure"),
	DV_E_STGMEDIUM(0x80040066,"Invalid STDGMEDIUM structure"),
	DV_E_STATDATA(0x80040067,"Invalid STATDATA structure"),
	DV_E_LINDEX(0x80040068,"Invalid lindex"),
	DV_E_TYMED(0x80040069,"Invalid tymed"),
	DV_E_CLIPFORMAT(0x8004006A,"Invalid clipboard format"),
	DV_E_DVASPECT(0x8004006B,"Invalid aspect(s)"),
	DV_E_DVTARGETDEVICE_SIZE(0x8004006C,"tdSize parameter of the DVTARGETDEVICE structure is invalid"),
	DV_E_NOIVIEWOBJECT(0x8004006D,"Object doesn't support IViewObject interface"),
	DRAGDROP_E_NOTREGISTERED(0x80040100,"Trying to revoke a drop target that has not been registered"),
	DRAGDROP_E_ALREADYREGISTERED(0x80040101,"This window has already been registered as a drop target"),
	DRAGDROP_E_INVALIDHWND(0x80040102,"Invalid window handle"),
	CLASS_E_NOAGGREGATION(0x80040110,"Class does not support aggregation (or class object is remote)"),
	CLASS_E_CLASSNOTAVAILABLE(0x80040111,"ClassFactory cannot supply requested class"),
	CLASS_E_NOTLICENSED(0x80040112,"Class is not licensed for use"),
	VIEW_E_DRAW(0x80040140,"Error drawing view"),
	REGDB_E_READREGDB(0x80040150,"Could not read key from registry"),
	REGDB_E_WRITEREGDB(0x80040151,"Could not write key to registry"),
	REGDB_E_KEYMISSING(0x80040152,"Could not find the key in the registry"),
	REGDB_E_INVALIDVALUE(0x80040153,"Invalid value for registry"),
	REGDB_E_CLASSNOTREG(0x80040154,"Class not registered"),
	REGDB_E_IIDNOTREG(0x80040155,"Interface not registered"),
	REGDB_E_BADTHREADINGMODEL(0x80040156,"Threading model entry is not valid"),
	CAT_E_CATIDNOEXIST(0x80040160,"CATID does not exist"),
	CAT_E_NODESCRIPTION(0x80040161,"Description not found"),
	CS_E_PACKAGE_NOTFOUND(0x80040164,"No package in the software installation data in the Active Directory meets this criteria."),
	CS_E_NOT_DELETABLE(0x80040165,"Deleting this will break the referential integrity of the software installation data in the Active Directory."),
	CS_E_CLASS_NOTFOUND(0x80040166,"The CLSID was not found in the software installation data in the Active Directory."),
	CS_E_INVALID_VERSION(0x80040167,"The software installation data in the Active Directory is corrupt."),
	CS_E_NO_CLASSSTORE(0x80040168,"There is no software installation data in the Active Directory."),
	CS_E_OBJECT_NOTFOUND(0x80040169,"There is no software installation data object in the Active Directory."),
	CS_E_OBJECT_ALREADY_EXISTS(0x8004016A,"The software installation data object in the Active Directory already exists."),
	CS_E_INVALID_PATH(0x8004016B,"The path to the software installation data in the Active Directory is not correct."),
	CS_E_NETWORK_ERROR(0x8004016C,"A network error interrupted the operation."),
	CS_E_ADMIN_LIMIT_EXCEEDED(0x8004016D,"The size of this object exceeds the maximum size set by the Administrator."),
	CS_E_SCHEMA_MISMATCH(0x8004016E,"The schema for the software installation data in the Active Directory does not match the required schema."),
	CS_E_INTERNAL_ERROR(0x8004016F,"An error occurred in the software installation data in the Active Directory."),
	CACHE_E_NOCACHE_UPDATED(0x80040170,"Cache not updated"),
	OLEOBJ_E_NOVERBS(0x80040180,"No verbs for OLE object"),
	OLEOBJ_E_INVALIDVERB(0x80040181,"Invalid verb for OLE object"),
	INPLACE_E_NOTUNDOABLE(0x800401A0,"Undo is not available"),
	INPLACE_E_NOTOOLSPACE(0x800401A1,"Space for tools is not available"),
	CONVERT10_E_OLESTREAM_GET(0x800401C0,"OLESTREAM Get method failed"),
	CONVERT10_E_OLESTREAM_PUT(0x800401C1,"OLESTREAM Put method failed"),
	CONVERT10_E_OLESTREAM_FMT(0x800401C2,"Contents of the OLESTREAM not in correct format"),
	CONVERT10_E_OLESTREAM_BITMAP_TO_DIB(0x800401C3,"There was an error in a Windows GDI call while converting the bitmap to a DIB"),
	CONVERT10_E_STG_FMT(0x800401C4,"Contents of the IStorage not in correct format"),
	CONVERT10_E_STG_NO_STD_STREAM(0x800401C5,"Contents of IStorage is missing one of the standard streams"),
	CONVERT10_E_STG_DIB_TO_BITMAP(0x800401C6,"There was an error in a Windows GDI call while converting the DIB to a bitmap."),
	CLIPBRD_E_CANT_OPEN(0x800401D0,"OpenClipboard Failed"),
	CLIPBRD_E_CANT_EMPTY(0x800401D1,"EmptyClipboard Failed"),
	CLIPBRD_E_CANT_SET(0x800401D2,"SetClipboard Failed"),
	CLIPBRD_E_BAD_DATA(0x800401D3,"Data on clipboard is invalid"),
	CLIPBRD_E_CANT_CLOSE(0x800401D4,"CloseClipboard Failed"),
	MK_E_CONNECTMANUALLY(0x800401E0,"Moniker needs to be connected manually"),
	MK_E_EXCEEDEDDEADLINE(0x800401E1,"Operation exceeded deadline"),
	MK_E_NEEDGENERIC(0x800401E2,"Moniker needs to be generic"),
	MK_E_UNAVAILABLE(0x800401E3,"Operation unavailable"),
	MK_E_SYNTAX(0x800401E4,"Invalid syntax"),
	MK_E_NOOBJECT(0x800401E5,"No object for moniker"),
	MK_E_INVALIDEXTENSION(0x800401E6,"Bad extension for file"),
	MK_E_INTERMEDIATEINTERFACENOTSUPPORTED(0x800401E7,"Intermediate operation failed"),
	MK_E_NOTBINDABLE(0x800401E8,"Moniker is not bindable"),
	MK_E_NOTBOUND(0x800401E9,"Moniker is not bound"),
	MK_E_CANTOPENFILE(0x800401EA,"Moniker cannot open file"),
	MK_E_MUSTBOTHERUSER(0x800401EB,"User input required for operation to succeed"),
	MK_E_NOINVERSE(0x800401EC,"Moniker class has no inverse"),
	MK_E_NOSTORAGE(0x800401ED,"Moniker does not refer to storage"),
	MK_E_NOPREFIX(0x800401EE,"No common prefix"),
	MK_E_ENUMERATION_FAILED(0x800401EF,"Moniker could not be enumerated"),
	CO_E_NOTINITIALIZED(0x800401F0,"CoInitialize has not been called."),
	CO_E_ALREADYINITIALIZED(0x800401F1,"CoInitialize has already been called."),
	CO_E_CANTDETERMINECLASS(0x800401F2,"Class of object cannot be determined"),
	CO_E_CLASSSTRING(0x800401F3,"Invalid class string"),
	CO_E_IIDSTRING(0x800401F4,"Invalid interface string"),
	CO_E_APPNOTFOUND(0x800401F5,"Application not found"),
	CO_E_APPSINGLEUSE(0x800401F6,"Application cannot be run more than once"),
	CO_E_ERRORINAPP(0x800401F7,"Some error in application program"),
	CO_E_DLLNOTFOUND(0x800401F8,"DLL for class not found"),
	CO_E_ERRORINDLL(0x800401F9,"Error in the DLL"),
	CO_E_WRONGOSFORAPP(0x800401FA,"Wrong operating system or operating system version for the application"),
	CO_E_OBJNOTREG(0x800401FB,"Object is not registered"),
	CO_E_OBJISREG(0x800401FC,"Object is already registered"),
	CO_E_OBJNOTCONNECTED(0x800401FD,"Object is not connected to server"),
	CO_E_APPDIDNTREG(0x800401FE,"Application was launched but it didn't register a class factory"),
	CO_E_RELEASED(0x800401FF,"Object has been released"),
	EVENT_S_SOME_SUBSCRIBERS_FAILED(0x00040200,"An event was able to invoke some but not all of the subscribers"),
	EVENT_E_ALL_SUBSCRIBERS_FAILED(0x80040201,"An event was unable to invoke any of the subscribers"),
	EVENT_S_NOSUBSCRIBERS(0x00040202,"An event was delivered but there were no subscribers"),
	EVENT_E_QUERYSYNTAX(0x80040203,"A syntax error occurred trying to evaluate a query string"),
	EVENT_E_QUERYFIELD(0x80040204,"An invalid field name was used in a query string"),
	EVENT_E_INTERNALEXCEPTION(0x80040205,"An unexpected exception was raised"),
	EVENT_E_INTERNALERROR(0x80040206,"An unexpected internal error was detected"),
	EVENT_E_INVALID_PER_USER_SID(0x80040207,"The owner SID on a per-user subscription doesn't exist"),
	EVENT_E_USER_EXCEPTION(0x80040208,"A user-supplied component or subscriber raised an exception"),
	EVENT_E_TOO_MANY_METHODS(0x80040209,"An interface has too many methods to fire events from"),
	EVENT_E_MISSING_EVENTCLASS(0x8004020A,"A subscription cannot be stored unless its event class already exists"),
	EVENT_E_NOT_ALL_REMOVED(0x8004020B,"Not all the objects requested could be removed"),
	EVENT_E_COMPLUS_NOT_INSTALLED(0x8004020C,"COM+ is required for this operation, but is not installed"),
	EVENT_E_CANT_MODIFY_OR_DELETE_UNCONFIGURED_OBJECT(0x8004020D,"Cannot modify or delete an object that was not added using the COM+ Admin SDK"),
	EVENT_E_CANT_MODIFY_OR_DELETE_CONFIGURED_OBJECT(0x8004020E,"Cannot modify or delete an object that was added using the COM+ Admin SDK"),
	EVENT_E_INVALID_EVENT_CLASS_PARTITION(0x8004020F,"The event class for this subscription is in an invalid partition"),
	EVENT_E_PER_USER_SID_NOT_LOGGED_ON(0x80040210,"The owner of the PerUser subscription is not logged on to the system specified"),
	
	//Storage values
	STG_E_INVALIDFUNCTION(0x80030001,"Unable to perform requested operation."),	
	STG_E_FILENOTFOUND(0x80030002,"The file could not be found.)"),
	STG_E_PATHNOTFOUND(0x80030003,"The path could not be found."),
	STG_E_TOOMANYOPENFILES(0x80030004,"There are insufficient resources to open another file."),
	STG_E_ACCESSDENIED(0x80030005,"Access Denied."),
	STG_E_INVALIDHANDLE(0x80030006,"Attempted an operation on an invalid object."),
	STG_E_INSUFFICIENTMEMORY(0x80030008,"There is insufficient memory available to complete operation."),
	STG_E_INVALIDPOINTER(0x80030009,"Invalid pointer error."),
	STG_E_NOMOREFILES(0x80030012,"There are no more entries to return."),
	STG_E_DISKISWRITEPROTECTED(0x80030013,"Disk is write-protected."),
	STG_E_SEEKERROR(0x80030019,"An error occurred during a seek operation."),
	STG_E_WRITEFAULT(0x8003001D,"A disk error occurred during a write operation."),
	STG_E_READFAULT(0x8003001E,"A disk error occurred during a read operation."),
	STG_E_SHAREVIOLATION(0x80030020,"A share violation has occurred."),
	STG_E_LOCKVIOLATION(0x80030021,"A lock violation has occurred."),
	STG_E_FILEALREADYEXISTS(0x80030050,"The file already exists."),
	STG_E_INVALIDPARAMETER(0x80030057,"Invalid parameter error."),
	STG_E_MEDIUMFULL(0x80030070,"There is insufficient disk space to complete operation."),
	STG_E_PROPSETMISMATCHED(0x800300F0,"Illegal write of non-simple property to simple property set."),
	STG_E_ABNORMALAPIEXIT(0x800300FA,"An API call exited abnormally."),
	STG_E_INVALIDHEADER(0x800300FB,"The file is not a valid compound file."),
	STG_E_INVALIDNAME(0x800300FC,"The name is not valid."),
	STG_E_UNKNOWN(0x800300FD,"An unexpected error occurred."),
	STG_E_UNIMPLEMENTEDFUNCTION(0x800300FE,"That function is not implemented."),
	STG_E_INVALIDFLAG(0x800300FF,"Invalid flag error."),
	STG_E_INUSE(0x80030100,"Attempted to use an object that is busy."),
	STG_E_NOTCURRENT(0x80030101,"The storage has been changed since the last commit."),
	STG_E_REVERTED(0x80030102,"Attempted to use an object that has ceased to exist."),
	STG_E_CANTSAVE(0x80030103,"Can't save."),
	STG_E_OLDFORMAT(0x80030104,"The compound file  was produced with an incompatible version of storage."),
	STG_E_OLDDLL(0x80030105,"The compound file was produced with a newer version of storage."),
	STG_E_SHAREREQUIRED(0x80030106,"Share.exe or equivalent is required for operation."),
	STG_E_NOTFILEBASEDSTORAGE(0x80030107,"Illegal operation called on non-file based storage."),
	STG_E_EXTANTMARSHALLINGS(0x80030108,"Illegal operation called on object with extant marshallings."),
	STG_E_DOCFILECORRUPT(0x80030109,"The docfile has been corrupted."),
	STG_E_BADBASEADDRESS(0x80030110,"OLE32.DLL has been loaded at the wrong address."),
	STG_E_DOCFILETOOLARGE(0x80030111,"The compound file is too large for the current implementation"),
	STG_E_NOTSIMPLEFORMAT(0x80030112,"The compound file was not created with the STGM_SIMPLE flag"),
	STG_E_INCOMPLETE(0x80030201,"The file download was aborted abnormally. The file is incomplete."),
	STG_E_TERMINATED(0x80030202,"The file download has been terminated."),
	STG_S_CONVERTED(0x00030200,"The underlying file was converted to compound file format."),
	STG_S_BLOCK(0x00030201,"The storage operation should block until more data is available."),
	STG_S_RETRYNOW(0x00030202,"The storage operation should retry immediately."),
	STG_S_MONITORING(0x00030203,"The notified event sink will not influence the storage operation."),
	STG_S_MULTIPLEOPENS(0x00030204,"Multiple opens prevent consolidated. (commit succeeded)"),
	STG_S_CONSOLIDATIONFAILED(0x00030205,"Consolidation of the storage file failed. (commit succeeded)."),
	STG_S_CANNOTCONSOLIDATE(0x00030206,"Consolidation of the storage file is inappropriate. (commit succeeded)."),
	STG_E_STATUS_COPY_PROTECTION_FAILURE(0x80030305,"Generic Copy Protection Error."),
	STG_E_CSS_AUTHENTICATION_FAILURE(0x80030306,"Copy Protection Error - DVD CSS Authentication failed."),
	STG_E_CSS_KEY_NOT_PRESENT(0x80030307,"Copy Protection Error - The given sector does not have a valid CSS key."),
	STG_E_CSS_KEY_NOT_ESTABLISHED(0x80030308,"Copy Protection Error - DVD session key not established."),
	STG_E_CSS_SCRAMBLED_SECTOR(0x80030309,"Copy Protection Error - The read failed because the sector is encrypted."),
	STG_E_CSS_REGION_MISMATCH(0x8003030A,"Copy Protection Error - The current DVD's region does not correspond to the region setting of the drive."),
	STG_E_RESETS_EXHAUSTED(0x8003030B,"Copy Protection Error - The drive's region setting may be permanent or the number of user resets has been exhausted."),
	
	//WIA values
	WIA_ERROR_BUSY(0x80210006,"The device is busy. Close any apps that are using this device or wait for it to finish and then try again."),
	WIA_ERROR_COVER_OPEN(0x80210016,"One or more of the device’s cover is open."),
	WIA_ERROR_DEVICE_COMMUNICATION(0x8021000A,"Communication with the WIA device failed. Make sure that the device is powered on and connected to the PC. If the problem persists, disconnect and reconnect the device."),
	WIA_ERROR_DEVICE_LOCKED(0x8021000D,"The device is locked. Close any apps that are using this device or wait for it to finish and then try again."),
	WIA_ERROR_EXCEPTION_IN_DRIVER(0x8021000E,"The device driver threw an exception."),
	WIA_ERROR_GENERAL_ERROR(0x80210001,"An unknown error has occurred with the WIA device."),
	WIA_ERROR_INCORRECT_HARDWARE_SETTING(0x8021000C,"There is an incorrect setting on the WIA device."),
	WIA_ERROR_INVALID_COMMAND(0x8021000B,"The device doesn't support this command."),
	WIA_ERROR_INVALID_DRIVER_RESPONSE(0x8021000F,"The response from the driver is invalid."),
	WIA_ERROR_ITEM_DELETED(0x8021000F,"The WIA device was deleted. It's no longer available."),
	WIA_ERROR_LAMP_OFF(0x80210017,"The scanner's lamp is off."),
	WIA_ERROR_MAXIMUM_PRINTER_ENDORSER_COUNTER(0x80210021,"A scan job was interrupted because an Imprinter/Endorser item reached the maximum valid value for WIA_IPS_PRINTER_ENDORSER_COUNTER, and was reset to 0. This feature is available with Windows 8 and later versions of Windows."),
	WIA_ERROR_MULTI_FEED(0x80210020,"A scan error occurred because of a multiple page feed condition. This feature is available with Windows 8 and later versions of Windows."),
	WIA_ERROR_OFFLINE(0x80210005,"The device is offline. Make sure the device is powered on and connected to the PC."),
	WIA_ERROR_PAPER_EMPTY(0x80210003,"There are no documents in the document feeder."),
	WIA_ERROR_PAPER_JAM(0x80210002,"Paper is jammed in the scanner's document feeder."),
	WIA_ERROR_PAPER_PROBLEM(0x80210004,"An unspecified problem occurred with the scanner's document feeder."),
	WIA_ERROR_WARMING_UP(0x80210007,"The device is warming up."),
	WIA_ERROR_USER_INTERVENTION(0x80210008,"There is a problem with the WIA device. Make sure that the device is turned on, online, and any cables are properly connected."),
	WIA_S_NO_DEVICE_AVAILABLE(0x80210015,"No scanner device was found. Make sure the device is online, connected to the PC, and has the correct driver installed on the PC."),

	//other values
	RPC_E_WRONG_THREAD(0x8001010E, "Thread calls via an interface pointer which is for a proxy object that does not belong to the thread's apartment.");
	private final int code;
	private final String description;

	private EHResult(final int code, final String description){
		this.code = code;
		this.description = description;
	}
	
	public int getCode(){
		return code;
	}
	
	public String getDescription(){
		return description;
	}
	
    public static EHResult fromCode(final int code) {
        for (EHResult result : EHResult.values()) {
            if (result.code==code) {
                return result;
            }
        }
        return null;
    }
	
}