package org.radixware.kernel.designer.common.dialogs.stack;

import java.awt.Component;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.radixware.kernel.common.defs.Definition;
import org.radixware.kernel.common.defs.RadixObject;
import org.radixware.kernel.common.defs.ads.src.SrcPositionLocator;


public class ChooseStackTraceItemPanel extends javax.swing.JPanel {

    public ChooseStackTraceItemPanel() {
        initComponents();
        jList1.setCellRenderer(new CellRenderer());
    }

    public void open(List<Definition> definitions){
        if (definitions == null || definitions.isEmpty()) return;
        jList1.setListData(definitions.toArray());
        jList1.setSelectedIndex(0);
    }
    
    public void open(Collection<SrcPositionLocator.SrcLocation> locations){
        if (locations == null || locations.isEmpty()) return;
        jList1.setListData(locations.toArray());
        jList1.setSelectedIndex(0);
    }
    
    public SrcPositionLocator.SrcLocation getSelectedLocation(){
        if (jList1.getSelectedValue() instanceof SrcPositionLocator.SrcLocation){
            return (SrcPositionLocator.SrcLocation) jList1.getSelectedValue();
        }
        return null;
    }
    
    public Definition getSelectedDefinition(){
        if (jList1.getSelectedValue() instanceof Definition){
            return (Definition) jList1.getSelectedValue();
        }
        return null;
    }

    private final class CellRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList tree, Object value, int index, boolean isSelected, boolean hasFocus) {
            Component c = super.getListCellRendererComponent(tree, value, index, isSelected, hasFocus);
            RadixObject object = null;
            if (value instanceof SrcPositionLocator.SrcLocation){
                SrcPositionLocator.SrcLocation location = (SrcPositionLocator.SrcLocation) value;
                object = location.getRadixObject().getOwnerDefinition();
            } else {
                if (value instanceof Definition){
                    object = (Definition) value;
                }
            }
            
            if (object != null){
                setText(object.getQualifiedName());
                setIcon(object.getIcon().getIcon());
            }
            
            setForeground(c.getForeground());
            
            return this;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
