/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.common.design.msdleditor.field.panel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;
import org.radixware.kernel.common.msdl.enums.EEncoding;
import org.radixware.kernel.common.msdl.fields.StructureFieldModel;
import org.radixware.schemas.msdl.Structure.FieldNaming.BerTLV;


public class BerTLVPanel extends AbstractEditItem implements ActionListener {

    private StructureFieldModel field = null;
    /**
     * Creates new form BerTLVPanel
     */
    public BerTLVPanel() {
        initComponents();
    }
    
    public void open(StructureFieldModel field) {
        super.open(field.getMsdlField());
        encodingPanel.setAllowedEncodings(new EEncoding[] { EEncoding.NONE, EEncoding.HEX, EEncoding.HEXEBCDIC });
        this.field = field;
        if(isFieldProper()) {
            EEncoding currentEnc = getBerTLVEncoding();
            if(currentEnc != null && currentEnc != EEncoding.NONE)
                encodingPanel.setEncoding(currentEnc, currentEnc);
            else
                encodingPanel.setEncoding(EEncoding.NONE, EEncoding.NONE);
        }
        encodingPanel.addActionListener(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encodingPanel = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.EncodingPanel();
        verticalGlue = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 600), new java.awt.Dimension(0, 0));

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
        add(encodingPanel);
        add(verticalGlue);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.EncodingPanel encodingPanel;
    private javax.swing.Box.Filler verticalGlue;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(isFieldProper()) {
            BerTLV tlv = getBerTLV();
            EEncoding currentEncoding = getBerTLVEncoding();
            
            EEncoding selectedEncoding = encodingPanel.getEncoding();
            boolean modified = false;
            if(currentEncoding != null)  {
                if (currentEncoding != selectedEncoding) {
                    tlv.setEncoding(selectedEncoding.getValue());
                    modified = true;
                }
            }
            else {
                if(selectedEncoding != EEncoding.NONE) {
                    tlv.setEncoding(selectedEncoding.getValue());
                    modified = true;
                }
            }
            if(modified) {
                field.setModified();
            }
        }
    }
    
    private boolean isFieldProper() {
         return field != null && 
          field.getField().getStructure().isSetFieldNaming() &&
          field.getField().getStructure().getFieldNaming().isSetBerTLV();
    }
    
    private BerTLV getBerTLV() {
        return field.getField().getStructure().getFieldNaming().getBerTLV();
    }
    
    private EEncoding getBerTLVEncoding() {
        if(isFieldProper()) {
          BerTLV tlv = getBerTLV();
          if(tlv.isSetEncoding())
              return EEncoding.getInstance(tlv.getEncoding());
          return EEncoding.NONE;
        }
        return null;
    }
}
