/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.editors.creation;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.openide.util.ChangeSupport;
import org.openide.util.NbBundle;
import org.radixware.kernel.common.enums.ERuntimeEnvironmentType;
import org.radixware.kernel.designer.ads.common.dialogs.ChooseEnvComboBoxModel;


public class AdsTransparentClassWizardStep1Panel extends javax.swing.JPanel{

    public static final String DYNAMIC = NbBundle.getMessage(AdsTransparentClassWizardStep1Panel.class, "Creature-Step-Btn1");
    public static final String PRESENTATION = NbBundle.getMessage(AdsTransparentClassWizardStep1Panel.class, "Creature-Step-Btn2");

    /** Creates new form TransparentClassStepVisual */
    public AdsTransparentClassWizardStep1Panel() {
        initComponents();
        methodsCheck.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                changeSupport.fireChange();
            }

        });
        classChooser.addChangeListener(new ChangeListener(){

            @Override
            public void stateChanged(ChangeEvent e) {
                changeSupport.fireChange();
            }

        });
    }
    void open(AdsTransparentClassCreature creature) {
        classChooser.open(creature.getAdsModule(), getEnvironment());
    }

    ERuntimeEnvironmentType getEnvironment() {
        return classChooser.getEnvironment();
    }

    String getPublishedClass() {
        return classChooser.getPublishedName();
    }

    String getClassName() {
        return classChooser.getCustomName();
    }

    boolean isExtendable() {
        return extCheck.isSelected();
    }

    boolean isPublishMethods(){
        return methodsCheck.isSelected();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        extCheck = new javax.swing.JCheckBox();
        classChooser = new org.radixware.kernel.designer.ads.editors.creation.TransparentClassAndNameChooser();
        methodsCheck = new javax.swing.JCheckBox();

        extCheck.setText(org.openide.util.NbBundle.getMessage(AdsTransparentClassWizardStep1Panel.class, "Creature-Step-Extend")); // NOI18N

        methodsCheck.setText(org.openide.util.NbBundle.getMessage(AdsTransparentClassWizardStep1Panel.class, "Creature-Step-PulishMethods")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(classChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(extCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(methodsCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(extCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(methodsCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.radixware.kernel.designer.ads.editors.creation.TransparentClassAndNameChooser classChooser;
    private javax.swing.JCheckBox extCheck;
    private javax.swing.JCheckBox methodsCheck;
    // End of variables declaration//GEN-END:variables

    public boolean isComplete() {
        boolean res = classChooser.isComplete();
        extCheck.setEnabled(res);
        methodsCheck.setEnabled(res);
        return res;
    }

    private ChangeSupport changeSupport = new ChangeSupport(this);

    public final void addChangeListener(ChangeListener l) {
        changeSupport.addChangeListener(l);
    }

    public final void removeChangeListener(ChangeListener l) {
        changeSupport.removeChangeListener(l);
    }
}
