/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * BCHPanel.java
 *
 * Created on 03.12.2008, 13:12:04
 */

package org.radixware.kernel.common.design.msdleditor.field.panel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;
import org.radixware.kernel.common.design.msdleditor.DefaultLayout;
import org.radixware.kernel.common.design.msdleditor.enums.EAlign;
import org.radixware.kernel.common.msdl.fields.AbstractFieldModel;
import org.radixware.kernel.common.msdl.fields.BCHFieldModel;
import org.radixware.schemas.msdl.BCHField;


public class BCHPanel extends AbstractEditItem implements ActionListener {

    private BCHField field;
    private AbstractFieldModel fieldModel;
    boolean opened = false;

    /** Creates new form BCHPanel */
    public BCHPanel() {
        initComponents();
        ArrayList<JLabel> l = new ArrayList<JLabel>();
        l.add(jLabelBCHAlign);
        l.add(jLabel2);
        l.add(jLabel3);
        ArrayList<JComponent> e = new ArrayList<JComponent>();
        e.add(alignPanel1);
        e.add(extCharPanel1);
        e.add(jTextFieldDefaultValue);
        DefaultLayout.doLayout(this, l, e,true);

    }

    public void open(BCHFieldModel fieldModel) {
        super.open(fieldModel.getMsdlField());
        this.field = fieldModel.getField();
        this.fieldModel = fieldModel;
        alignPanel1.addActionListener(this);
        alignPanel1.getSetParentPanel().addActionListener(this);
        extCharPanel1.addActionListener(this);
        DocumentListener dl = new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                defaultValueChanged();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                defaultValueChanged();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                defaultValueChanged();
            }
        };
        jTextFieldDefaultValue.getDocument().addDocumentListener(dl);
        update();
    }

    @Override
    public void update() {
        opened = false;
        alignPanel1.setAlign(EAlign.getInstance(field.getAlign()),
                             EAlign.getInstance(fieldModel.getBCHAlign(false)));
        extCharPanel1.setString(field.getPadChar(), fieldModel.getBCHPad(false));
        jTextFieldDefaultValue.setText(field.getDefaultVal());
        opened = true;
        super.update();
    }

    private void save() {
        field.setAlign(alignPanel1.getAlign().getValue());
        field.setPadChar(extCharPanel1.getString());
        fieldModel.setModified();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBCHAlign = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDefaultValue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alignPanel1 = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.AlignPanel();
        extCharPanel1 = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.ExtCharPanel();

        jLabelBCHAlign.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/radixware/kernel/common/design/msdleditor/Bundle"); // NOI18N
        jLabelBCHAlign.setText(bundle.getString("ALIGN")); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(bundle.getString("BCH_PAD")); // NOI18N

        jTextFieldDefaultValue.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldDefaultValueCaretUpdate(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(bundle.getString("DEFAULT_VALUE")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabelBCHAlign, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDefaultValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(alignPanel1, 0, 0, Short.MAX_VALUE)
                    .addComponent(extCharPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBCHAlign, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(alignPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extCharPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDefaultValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDefaultValueCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldDefaultValueCaretUpdate
//        if (!opened)
//            return;
//        field.setDefaultVal(this.jTextFieldDefaultValue.getText());
//        fieldModel.setModified();
    }//GEN-LAST:event_jTextFieldDefaultValueCaretUpdate


    private void defaultValueChanged() {
        if (!opened)
            return;
        field.setDefaultVal(this.jTextFieldDefaultValue.getText());
        fieldModel.setModified();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.AlignPanel alignPanel1;
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.ExtCharPanel extCharPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBCHAlign;
    private javax.swing.JTextField jTextFieldDefaultValue;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (!opened)
            return;
        save();
    }

}
