/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * ParagraphLinkEditorPanel.java
 *
 * Created on 17.08.2009, 10:53:31
 */
package org.radixware.kernel.designer.ads.editors.exploreritems;

import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import org.openide.util.NbBundle;
import org.radixware.kernel.common.defs.ads.explorerItems.AdsParagraphLinkExplorerItemDef;
import org.radixware.kernel.designer.ads.common.dialogs.AccessEditPanel;
import org.radixware.kernel.designer.common.dialogs.components.InheritableTitlePanel;
import org.radixware.kernel.designer.common.dialogs.components.DefinitionLinkEditPanel;


public class ParagraphLinkEditorPanel extends javax.swing.JPanel {

    private AdsParagraphLinkExplorerItemDef link;

    private AccessEditPanel accessPanel = new AccessEditPanel();
    private javax.swing.JLabel accessLabel = new javax.swing.JLabel(NbBundle.getMessage(ParagraphLinkEditorPanel.class, "AccessBoxTip"));
    /** Creates new form ParagraphLinkEditorPanel */
    public ParagraphLinkEditorPanel() {
        initComponents();
        javax.swing.JPanel innerpane = new javax.swing.JPanel();
        GridBagLayout gbl = new GridBagLayout();
        GridBagConstraints c = new GridBagConstraints();
        innerpane.setLayout(gbl);

        c.anchor = GridBagConstraints.WEST;
        c.gridwidth = 2;
        c.weightx = 1.0;
        c.insets = new Insets(10, 10, 10, 10);
        c.fill = GridBagConstraints.HORIZONTAL;
        gbl.setConstraints(titleEditor, c);
        innerpane.add(titleEditor);

        c.gridwidth = 1;
        c.gridy = 1;
        c.weightx = 0.0;
        c.insets = new Insets(0, 10, 10, 10);
        gbl.setConstraints(accessLabel, c);
        innerpane.add(accessLabel);
        c.gridx = 1;
        c.insets = new Insets(0, 0, 10, 10);
        c.fill = GridBagConstraints.NONE;
        gbl.setConstraints(accessPanel, c);
        innerpane.add(accessPanel);

        c.gridy = 2;
        c.gridx = 0;
        c.fill = GridBagConstraints.HORIZONTAL;
        c.insets = new Insets(0, 10, 10, 10);
        gbl.setConstraints(refLabel, c);
        innerpane.add(refLabel);

        c.gridx = 1;
        c.weightx = 1.0;
        c.insets = new Insets(0, 0, 10, 10);
        gbl.setConstraints(refEditor, c);
        innerpane.add(refEditor);

        setLayout(new BorderLayout());
        add(innerpane, BorderLayout.NORTH);
    }

    private boolean readonly = false;
    private InheritableTitlePanel titleEditor = new InheritableTitlePanel();
    private javax.swing.JLabel refLabel = new javax.swing.JLabel(NbBundle.getMessage(ParagraphLinkEditorPanel.class, "ParagraphLink-Reference"));
    private DefinitionLinkEditPanel refEditor = new DefinitionLinkEditPanel();

    public void open(final AdsParagraphLinkExplorerItemDef link) {
        this.link = link;
        titleEditor.open(link);
        update();
    }

    public void update() {
        this.readonly = link.isReadOnly();
        titleEditor.update();
        refEditor.open(link.findReferencedParagraph(), link.getReferencedParagraphId());
        refEditor.setClearable(false);
        refEditor.setEnabled(!readonly);
        accessPanel.open(link); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
