/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * ScopeCommandSetupStep1.java
 *
 * Created on May 29, 2009, 10:01:37 AM
 */
package org.radixware.kernel.designer.ads.editors.clazz.creation;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.openide.util.ChangeSupport;
import org.radixware.kernel.common.enums.ECommandScope;


public class ScopeCommandSetupStep1Visual extends javax.swing.JPanel {

    /** Creates new form ScopeCommandSetupStep1 */
    public ScopeCommandSetupStep1Visual() {
        initComponents();

        namePanel.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                creature.name = namePanel.getCurrentName();
                changeSupport.fireChange();
            }
        });
        chObject.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                creature.scope = ECommandScope.OBJECT;
                updateButtons();
                changeSupport.fireChange();
            }
        });
        chPropCommand.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                creature.scope = ECommandScope.PROPERTY;
                updateButtons();
                changeSupport.fireChange();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePanel = new org.radixware.kernel.designer.common.dialogs.components.NameEditPanel();
        jLabel1 = new javax.swing.JLabel();
        objectSetupPanel = new javax.swing.JPanel();
        chObject = new javax.swing.JRadioButton();
        chPropCommand = new javax.swing.JRadioButton();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ScopeCommandSetupStep1Visual.class, "ScopeCommandSetupStep1Visual.jLabel1.text")); // NOI18N

        chObject.setText(org.openide.util.NbBundle.getMessage(ScopeCommandSetupStep1Visual.class, "ScopeCommandSetupStep1Visual.chObject.text")); // NOI18N

        chPropCommand.setText(org.openide.util.NbBundle.getMessage(ScopeCommandSetupStep1Visual.class, "ScopeCommandSetupStep1Visual.chPropCommand.text")); // NOI18N

        javax.swing.GroupLayout objectSetupPanelLayout = new javax.swing.GroupLayout(objectSetupPanel);
        objectSetupPanel.setLayout(objectSetupPanelLayout);
        objectSetupPanelLayout.setHorizontalGroup(
            objectSetupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objectSetupPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(objectSetupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chPropCommand)
                    .addComponent(chObject))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        objectSetupPanelLayout.setVerticalGroup(
            objectSetupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objectSetupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chObject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chPropCommand)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                    .addComponent(objectSetupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(objectSetupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton chObject;
    private javax.swing.JRadioButton chPropCommand;
    private javax.swing.JLabel jLabel1;
    private org.radixware.kernel.designer.common.dialogs.components.NameEditPanel namePanel;
    private javax.swing.JPanel objectSetupPanel;
    // End of variables declaration//GEN-END:variables
    private final ChangeSupport changeSupport = new ChangeSupport(this);

    public void removeChangeListener(ChangeListener listener) {
        changeSupport.removeChangeListener(listener);
    }

    public void addChangeListener(ChangeListener listener) {
        changeSupport.addChangeListener(listener);
    }
    ScopeCommandCreature creature;

    public void open(ScopeCommandCreature creature) {
        this.creature = creature;
        this.namePanel.setCurrentName(creature.name);
        this.objectSetupPanel.setVisible(creature.scope != ECommandScope.GROUP);

        updateButtons();
    }

    private void updateButtons() {
        synchronized (this) {
            if (creature.scope == ECommandScope.GROUP) {
                return;
            }
            if (creature.scope == ECommandScope.OBJECT) {
                chObject.setSelected(true);
                chPropCommand.setSelected(false);
            } else if (creature.scope == ECommandScope.PROPERTY) {
                chObject.setSelected(false);
                chPropCommand.setSelected(true);
            }
        }
    }

    public boolean isComplete() {
        return namePanel.isComplete();
    }
}
