/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * TestStep1.java
 *
 * Created on Jan 14, 2009, 8:38:38 AM
 */
package org.radixware.kernel.designer.common.dialogs.wizards;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import org.openide.util.ChangeSupport;
import org.radixware.kernel.designer.common.dialogs.components.state.StateManager;


public class TestStepPanel extends javax.swing.JPanel {

    public ChangeSupport changeSupport = new ChangeSupport(this);

    /** Creates new form TestStep1 */
    public TestStepPanel(final TestWizard.TestStep step) {
        initComponents();

        step.errorManager = new StateManager(edError);
        step.warningManager = new StateManager(edWarning);

        chCompleted.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                step.setComplete(chCompleted.isSelected());
            }
        });
        edError.addCaretListener(new CaretListener() {

            @Override
            public void caretUpdate(CaretEvent e) {
                step.setErrorMessage(edError.getText());
            }
        });
        edWarning.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                step.setWarningMessage(edWarning.getText());
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chCompleted = new javax.swing.JCheckBox();
        edError = new javax.swing.JTextField();
        edWarning = new javax.swing.JTextField();

        chCompleted.setText(org.openide.util.NbBundle.getMessage(TestStepPanel.class, "TestStepPanel.chCompleted.text")); // NOI18N

        edError.setText(org.openide.util.NbBundle.getMessage(TestStepPanel.class, "TestStepPanel.edError.text")); // NOI18N

        edWarning.setText(org.openide.util.NbBundle.getMessage(TestStepPanel.class, "TestStepPanel.edWarning.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edError, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(edWarning, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(chCompleted))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edWarning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chCompleted)
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox chCompleted;
    public javax.swing.JTextField edError;
    public javax.swing.JTextField edWarning;
    // End of variables declaration//GEN-END:variables
}
