/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.editors.clazz.simple;

import java.awt.BorderLayout;
import org.radixware.kernel.common.defs.RadixObject;
import org.radixware.kernel.common.defs.ads.clazz.AdsClassDef;
import org.radixware.kernel.common.scml.Scml;
import org.radixware.kernel.designer.common.annotations.registrators.EditorFactoryRegistration;
import org.radixware.kernel.designer.common.editors.RadixObjectEditor;
import org.radixware.kernel.designer.common.general.editors.IEditorFactory;
import org.radixware.kernel.designer.common.general.editors.IRadixObjectEditor;
import org.radixware.kernel.designer.common.general.editors.OpenInfo;


public class AdsClassEditor extends RadixObjectEditor<AdsClassDef> {

    private AdsClassEditorTabbedPane adsClassEditorTabbedPanel = null;

    @EditorFactoryRegistration
    public static final class Factory implements IEditorFactory<AdsClassDef> {

        @Override
        public IRadixObjectEditor<AdsClassDef> newInstance(AdsClassDef classDef) {
            return new AdsClassEditor(classDef);
        }
    }

    /** Creates new form AdsClassEditor */
    protected AdsClassEditor(AdsClassDef clazz) {
        super(clazz);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    public AdsClassDef getClassDef() {
        return getRadixObject();
    }

    @Override
    public boolean open(OpenInfo info) {
        final AdsClassDef adsClassDef = getClassDef();
        removeAll();
        adsClassEditorTabbedPanel = new AdsClassEditorTabbedPane();
        add(adsClassEditorTabbedPanel, BorderLayout.CENTER);
        adsClassEditorTabbedPanel.open(adsClassDef);

        {
            final RadixObject radixObject = info.getTarget();
            if (radixObject instanceof Scml.Item || radixObject instanceof Scml) {
                final Scml targetScml;
                if (radixObject instanceof Scml) {
                    targetScml = (Scml) radixObject;
                } else {
                    final Scml.Item scmlItem = (Scml.Item) radixObject;
                    targetScml = scmlItem.getOwnerScml();
                }

                
                if (adsClassDef.getBody().isParentOf(targetScml)) {
                    adsClassEditorTabbedPanel.openBodyTab(info);
                } else if (adsClassDef.getHeader().isParentOf(targetScml)) {
                    adsClassEditorTabbedPanel.openHeaderTab(info);
                }
            }
        }

        update();
        return super.open(info);
    }

    @Override
    public void update() {
        adsClassEditorTabbedPanel.update();
        setReadonly(getClassDef().isReadOnly());
    }

    public void setReadonly(boolean readonly) {
        adsClassEditorTabbedPanel.setReadonly(readonly);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
