/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.editors.clazz.simple;

import org.radixware.kernel.designer.common.dialogs.components.state.StateAbstractDialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.radixware.kernel.common.defs.ads.clazz.entity.AdsEntityClassDef.AccessAreas;


abstract class StateAbstractSetupAccessAreaDialog extends StateAbstractDialog {

    public static abstract class StateAbstractSetupAccessAreaPanel extends StateAbstractPanel {

        protected AccessAreas accessAreas;

        /** Creates new form AccessAreaPanel */
        public StateAbstractSetupAccessAreaPanel(AccessAreas accessAreas) {
            super();
            this.accessAreas = accessAreas;

            initComponents();

            nameTextField.addCaretListener(new CaretListener() {

                @Override
                public void caretUpdate(CaretEvent e) {
                    check();
                }
            });
            check();
        }

        public String getResultName() {
            return nameTextField.getText();
        }

        protected void setResultName(String name) {
            nameTextField.setText(name);
        }

        @Override
        public boolean requestFocusInWindow() {
            return nameTextField.requestFocusInWindow();
        }



        /** This method is called from within the constructor to
         * initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            nameTextField = new javax.swing.JTextField();
            jLabel1 = new javax.swing.JLabel();
            stateDisplayer = new org.radixware.kernel.designer.common.dialogs.components.state.StateDisplayer();

            nameTextField.setText(org.openide.util.NbBundle.getMessage(StateAbstractSetupAccessAreaPanel.class, "AbstractAccessAreaEditPanel.nameTextField.text")); // NOI18N

            jLabel1.setText(org.openide.util.NbBundle.getMessage(StateAbstractSetupAccessAreaPanel.class, "AbstractAccessAreaEditPanel.jLabel1.text")); // NOI18N

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(22, 22, 22).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(stateDisplayer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE).addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)).addContainerGap()));
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel1)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(stateDisplayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(19, Short.MAX_VALUE)));
        }// </editor-fold>                        
        // Variables declaration - do not modify                     
        private javax.swing.JLabel jLabel1;
        private javax.swing.JTextField nameTextField;
        private org.radixware.kernel.designer.common.dialogs.components.state.StateDisplayer stateDisplayer;
    }

    public StateAbstractSetupAccessAreaDialog(final StateAbstractSetupAccessAreaPanel innerPanel, final String title){
        super(innerPanel, title);

        getDialog().addWindowListener(new WindowAdapter() {

            @Override
            public void windowOpened(WindowEvent e) {
                ((StateAbstractSetupAccessAreaPanel) getComponent()).requestFocusInWindow();
                ((StateAbstractSetupAccessAreaPanel) getComponent()).check();
            }
        });
    }

    protected String getResultName(){
        return ((StateAbstractSetupAccessAreaPanel) getComponent()).getResultName();
    }

}
