/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * GenericParametersPanel.java
 *
 * Created on Mar 26, 2009, 11:53:00 AM
 */
package org.radixware.kernel.designer.common.dialogs.choosetype;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.openide.util.ChangeSupport;
import org.radixware.kernel.common.defs.Definition;
import org.radixware.kernel.common.defs.ads.type.AdsTypeDeclaration;
import org.radixware.kernel.common.defs.ads.type.IAdsTypedObject;


public class GenericParametersPanel extends javax.swing.JPanel {

    private GenericParametersWizardTable genericInset;

    /**
     * Creates new form GenericParametersPanel
     */
    public GenericParametersPanel() {
        initComponents();
        setLayout(new BorderLayout());
    }

    public void open(Definition context, IAdsTypedObject parameter, AdsTypeDeclaration.TypeArguments arguments) {
        removeAll();
        genericInset = new GenericParametersWizardTable();
        genericInset.open(context, parameter, arguments);
        genericInset.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                changeSupport.fireChange();
            }
        });
        add(genericInset, BorderLayout.CENTER);
    }

    public List<AdsTypeDeclaration.TypeArgument> getGenericParameters() {
        return genericInset != null ? genericInset.getGenericParameters() : null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private ChangeSupport changeSupport = new ChangeSupport(this);

    public final void addChangeListener(ChangeListener l) {
        changeSupport.addChangeListener(l);
    }

    public final void removeChangeListener(ChangeListener l) {
        changeSupport.removeChangeListener(l);
    }

//    private StateManager state = new StateManager(this);

    public boolean isComplete() {
        return genericInset != null && genericInset.isComplete();
    }
}
