/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * TraceItemViewerPanel.java
 *
 * Created on Jan 12, 2009, 5:39:36 PM
 */

package org.radixware.kernel.designer.common.dialogs.events;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.LogRecord;
import org.openide.util.NbBundle;


public class TraceItemViewerPanel extends javax.swing.JPanel {

    /** Creates new form TraceItemViewerPanel */
    public TraceItemViewerPanel(LogRecord logRecord) {
        initComponents();
        timeTextField.setText((new SimpleDateFormat("HH:mm:ss.SSS dd/MM/yy")).format(new Date(logRecord.getMillis())));
        if (logRecord.getSourceClassName() == null || logRecord.getSourceMethodName() == null)
            sourceTextField.setText(NbBundle.getBundle(TraceItemViewerPanel.class).getString("UNKNOWN"));
        else
            sourceTextField.setText(logRecord.getSourceClassName() + "." + logRecord.getSourceMethodName());
        loggerTextField.setText(logRecord.getLoggerName());
        messageTextArea.setText(logRecord.getMessage());
        if (logRecord.getThrown() != null) {
            StringBuilder buf = new StringBuilder();
            StackTraceElement[] elems = logRecord.getThrown().getStackTrace();
            for (StackTraceElement elem : elems)
                buf.append(elem.toString() + "\n");
            stackTraceTextArea.setText(buf.toString());
            thrownPanel.setVisible(true);
        } else {
            thrownPanel.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sourceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loggerTextField = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        thrownPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stackTraceTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText(org.openide.util.NbBundle.getMessage(TraceItemViewerPanel.class, "TraceItemViewerPanel.jLabel2.text")); // NOI18N

        timeTextField.setEditable(false);
        timeTextField.setText(org.openide.util.NbBundle.getMessage(TraceItemViewerPanel.class, "TraceItemViewerPanel.timeTextField.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(TraceItemViewerPanel.class, "TraceItemViewerPanel.jLabel3.text")); // NOI18N

        sourceTextField.setEditable(false);
        sourceTextField.setText(org.openide.util.NbBundle.getMessage(TraceItemViewerPanel.class, "TraceItemViewerPanel.sourceTextField.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(TraceItemViewerPanel.class, "TraceItemViewerPanel.jLabel4.text")); // NOI18N

        loggerTextField.setEditable(false);
        loggerTextField.setText(org.openide.util.NbBundle.getMessage(TraceItemViewerPanel.class, "TraceItemViewerPanel.loggerTextField.text")); // NOI18N

        jSplitPane1.setDividerLocation(125);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setContinuousLayout(true);

        messageTextArea.setColumns(20);
        messageTextArea.setEditable(false);
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        jLabel5.setText(org.openide.util.NbBundle.getMessage(TraceItemViewerPanel.class, "TraceItemViewerPanel.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        stackTraceTextArea.setColumns(20);
        stackTraceTextArea.setEditable(false);
        stackTraceTextArea.setRows(5);
        jScrollPane2.setViewportView(stackTraceTextArea);

        jLabel6.setText(org.openide.util.NbBundle.getMessage(TraceItemViewerPanel.class, "TraceItemViewerPanel.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout thrownPanelLayout = new javax.swing.GroupLayout(thrownPanel);
        thrownPanel.setLayout(thrownPanelLayout);
        thrownPanelLayout.setHorizontalGroup(
            thrownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thrownPanelLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        thrownPanelLayout.setVerticalGroup(
            thrownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thrownPanelLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(thrownPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                            .addComponent(loggerTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                            .addComponent(sourceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loggerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField loggerTextField;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JTextField sourceTextField;
    private javax.swing.JTextArea stackTraceTextArea;
    private javax.swing.JPanel thrownPanel;
    private javax.swing.JTextField timeTextField;
    // End of variables declaration//GEN-END:variables

}
