begin
  execute immediate 'ALTER TABLE RDX_DDSVERSION ADD CONSTRAINT PK_RDX_DDSVERSION PRIMARY KEY(LAYERURI)';
exception WHEN OTHERS THEN
  -- suppresses ORA-02260: table can have only one primary key
  IF SQLCODE = -02260 THEN NULL; ELSE RAISE; END IF;
end;
/

DELETE FROM RDX_DDSUPGRADELOG WHERE rowid not in (SELECT MIN(rowid)
  FROM RDX_DDSUPGRADELOG GROUP BY LAYERURI, FROMRELEASE, TORELEASE, FILENAME);
/

begin
  execute immediate 'ALTER TABLE RDX_DDSUPGRADELOG ADD CONSTRAINT PK_RDX_DDSUPGRADELOG PRIMARY KEY(LAYERURI, FROMRELEASE, TORELEASE, FILENAME)';
exception WHEN OTHERS THEN
  -- suppresses ORA-02260: table can have only one primary key
  IF SQLCODE = -02260 THEN NULL; ELSE RAISE; END IF;
end;
/

