create table RDX_SM_INSTANCESTATEHISTORY(
	INSTANCEID NUMBER(9,0) not null,
	REGTIMEMILLIS NUMBER(18,0) not null,
	THREADID NUMBER(18,0) not null,
	NAME VARCHAR2(400 char) null,
	ARTESEQ NUMBER(18,0) null,
	ARTESERIAL NUMBER(18,0) null,
	DBSID VARCHAR2(400 char) null,
	DBSERIAL VARCHAR2(400 char) null,
	TRACECONTEXTS VARCHAR2(400 char) null,
	CPUDIFFNANOS NUMBER(18,0) null,
	DBDIFFNANOS NUMBER(18,0) null,
	EXTDIFFNANOS NUMBER(18,0) null,
	OTHERDIFFNANOS NUMBER(18,0) null,
	UPTIMESEC NUMBER(9,0) null,
	STACK VARCHAR2(4000 char) null,
    STACKPART1 VARCHAR2(4000 char) null,
    STACKPART2 VARCHAR2(4000 char) null,
    STACKPART3 VARCHAR2(4000 char) null,
	RQSTARTTIMEMILLIS NUMBER(18,0) null,
	EXTDATA VARCHAR2(4000 char) null)
/

grant select, update, insert, delete on RDX_SM_INSTANCESTATEHISTORY to &USER&_RUN_ROLE
/

create unique index PK_RDX_SM_INSTANCESTATEHISTORY on RDX_SM_INSTANCESTATEHISTORY (INSTANCEID asc, REGTIMEMILLIS asc, THREADID asc)
/

alter table RDX_SM_INSTANCESTATEHISTORY add constraint PK_RDX_SM_INSTANCESTATEHISTORY primary key (INSTANCEID, REGTIMEMILLIS, THREADID) rely
/

