alter table RDX_SM_INSTANCESTATEHISTORY
	add FORCED NUMBER(1,0) null
/

alter table RDX_SM_INSTANCESTATEHISTORY
	add LOCKNAME VARCHAR2(100 char) null
/

alter table RDX_SM_INSTANCESTATEHISTORY
	add LOCKOWNERNAME VARCHAR2(100 char) null
/

alter table RDX_SM_INSTANCESTATEHISTORY
	add PRIMARYUNITID NUMBER(18,0) null
/

alter table RDX_SM_INSTANCESTATEHISTORY
	add THREADKIND VARCHAR2(100 char) null
/

alter table RDX_SM_INSTANCESTATEHISTORY
	add UNITID NUMBER(18,0) null
/

