create table RDX_SM_STACKDATA(
	DIGEST VARCHAR2(100 char) not null,
	COMPRESSEDSTACK BLOB not null,
	LASTUSAGETIMEMILLIS NUMBER(18,0) not null)
/

grant select, update, insert, delete on RDX_SM_STACKDATA to &USER&_RUN_ROLE
/

alter table RDX_SM_INSTANCESTATEHISTORY
	add STACKDIGEST VARCHAR2(100 char) null
/

create unique index PK_RDX_SM_STACKDATA on RDX_SM_STACKDATA (DIGEST asc)
/

alter table RDX_SM_STACKDATA add constraint PK_RDX_SM_STACKDATA primary key (DIGEST) rely
/

create or replace view RDX_SM_INSTANCESTATEVIEW as
select RDX_SM_INSTANCESTATEHISTORY.INSTANCEID as INSTANCEID,
       RDX_SM_INSTANCESTATEHISTORY.REGTIMEMILLIS as REGTIMEMILLIS,
       RDX_SM_INSTANCESTATEHISTORY.THREADID as THREADID,
       RDX_SM_INSTANCESTATEHISTORY.THREADKIND as THREADKIND,
       RDX_SM_INSTANCESTATEHISTORY.FORCED as FORCED,
       RDX_SM_INSTANCESTATEHISTORY.NAME as NAME,
       RDX_SM_INSTANCESTATEHISTORY.UNITID as UNITID,
       RDX_SM_INSTANCESTATEHISTORY.PRIMARYUNITID as PRIMARYUNITID,
       RDX_SM_INSTANCESTATEHISTORY.ARTESEQ as ARTESEQ,
       RDX_SM_INSTANCESTATEHISTORY.ARTESERIAL as ARTESERIAL,
       RDX_SM_INSTANCESTATEHISTORY.DBSID as DBSID,
       RDX_SM_INSTANCESTATEHISTORY.DBSERIAL as DBSERIAL,
       RDX_SM_INSTANCESTATEHISTORY.TRACECONTEXTS as TRACECONTEXTS,
       RDX_SM_INSTANCESTATEHISTORY.CPUDIFFNANOS as CPUDIFFNANOS,
       RDX_SM_INSTANCESTATEHISTORY.DBDIFFNANOS as DBDIFFNANOS,
       RDX_SM_INSTANCESTATEHISTORY.EXTDIFFNANOS as EXTDIFFNANOS,
       RDX_SM_INSTANCESTATEHISTORY.OTHERDIFFNANOS as OTHERDIFFNANOS,
       RDX_SM_INSTANCESTATEHISTORY.UPTIMESEC as UPTIMESEC,
       RDX_SM_INSTANCESTATEHISTORY.STACKDIGEST as STACKDIGEST,
       RDX_SM_STACKDATA.COMPRESSEDSTACK as COMPRESSEDSTACK,
       RDX_Utils.gunzipToClob(RDX_SM_STACKDATA.COMPRESSEDSTACK) as STACK,
       RDX_SM_INSTANCESTATEHISTORY.LOCKNAME as LOCKNAME,
       RDX_SM_INSTANCESTATEHISTORY.LOCKOWNERNAME as LOCKOWNERNAME,
       RDX_SM_INSTANCESTATEHISTORY.RQSTARTTIMEMILLIS as RQSTARTTIMEMILLIS,
       RDX_SM_INSTANCESTATEHISTORY.EXTDATA as EXTDATA
from RDX_SM_INSTANCESTATEHISTORY, RDX_SM_STACKDATA
where RDX_SM_INSTANCESTATEHISTORY.STACKDIGEST = RDX_SM_STACKDATA.DIGEST(+)
        
        
/

grant select, delete on RDX_SM_INSTANCESTATEVIEW to &USER&_RUN_ROLE
/

