create index IDX_RDX_SM_INSTANCESTATEHISTOR on RDX_SM_INSTANCESTATEHISTORY (INSTANCEID asc, REGTIMEMILLIS asc)
/

create index IDX_RDX_SM_STACKDATA_LASTUSAGE on RDX_SM_STACKDATA (LASTUSAGETIMEMILLIS asc)
/

