insert into RDX_UPVALNUM
select 
    'pruIYTC6UKMOZHJTCUJWL4DKR3BME', 'tblHW4OSVMS27NRDISQAAAAAAAAAA', ID, 0
from
    RDX_TESTCASE
where  
    CLASSGUID = 'aclRFAF35NQEZHWPKJAMOFJZA4RRQ' AND
    GROUPID is null
/