alter table RDX_PC_OUTMESSAGE
	add DELIVERYCALLBACKDATA VARCHAR2(4000 char) null
/

alter table RDX_PC_SENTMESSAGE
	add DELIVERYCALLBACKDATA VARCHAR2(4000 char) null
/

alter table RDX_PC_OUTMESSAGE
	add PREVSTAGEMESSAGEID NUMBER(9,0) null
/

alter table RDX_PC_SENTMESSAGE
	add PREVSTAGEMESSAGEID NUMBER(9,0) null
/

alter table RDX_PC_OUTMESSAGE
	add SENDCALLBACKDATA VARCHAR2(4000 char) null
/

alter table RDX_PC_SENTMESSAGE
	add SENDCALLBACKDATA VARCHAR2(4000 char) null
/

alter table RDX_PC_OUTMESSAGE
	add STAGENO NUMBER(9,0) null
/

alter table RDX_PC_SENTMESSAGE
	add STAGENO NUMBER(9,0) null
/

