alter table RDX_QUEUESAFPARTITION drop constraint PK_RDX_QUEUESAFPARTITION cascade
/

drop index PK_RDX_QUEUESAFPARTITION
/

create unique index PK_RDX_QUEUESAFPARTITION on RDX_QUEUESAFPARTITION (QUEUEID asc, ID asc)
/

alter table RDX_QUEUESAFPARTITION add constraint PK_RDX_QUEUESAFPARTITION primary key (QUEUEID, ID) rely
/

