/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * AdsModuleDefinitionWizardStep1Panel.java
 *
 * Created on Jan 19, 2009, 9:22:39 AM
 */
package org.radixware.kernel.designer.ads.editors.creation;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.openide.util.ChangeSupport;
import org.radixware.kernel.common.defs.Definition;
import org.radixware.kernel.common.defs.ads.clazz.AdsClassDef;
import org.radixware.kernel.common.enums.ERuntimeEnvironmentType;
import org.radixware.kernel.common.types.Id;
import org.radixware.kernel.designer.ads.common.dialogs.EnvironmentComboBoxModel;
import org.radixware.kernel.designer.common.dialogs.chooseobject.ChooseDefinitionCfg;
import org.radixware.kernel.designer.common.dialogs.components.DefinitionLinkEditPanel;
import org.radixware.kernel.designer.common.dialogs.utils.IAdvancedAcceptor;


class AdsModuleDefinitionWizardStep1Panel extends javax.swing.JPanel implements ChangeListener {

//    private ChooseEnvComboBoxModel envModel = new ChooseEnvComboBoxModel();
    /**
     * Creates new form AdsModuleDefinitionWizardStep1Panel
     */
    public AdsModuleDefinitionWizardStep1Panel(AdsClassDef parentClass) {
        initComponents();
        nameEditor.addChangeListener(this);
        cbEnv.setModel(EnvironmentComboBoxModel.Factory.newInstanceWithRestrictingOwner(parentClass));
        componentStub.setVisible(false);
        linkLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameEditor = new org.radixware.kernel.designer.common.dialogs.components.NameEditPanel();
        lbEnv = new javax.swing.JLabel();
        cbEnv = new javax.swing.JComboBox();
        linkLabel = new javax.swing.JLabel();
        componentStub = new org.radixware.kernel.designer.common.dialogs.components.DefinitionLinkEditPanel();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(AdsModuleDefinitionWizardStep1Panel.class, "Name-Label")); // NOI18N

        lbEnv.setText(org.openide.util.NbBundle.getMessage(AdsModuleDefinitionWizardStep1Panel.class, "AdsTransparentWizard-Env-Tip")); // NOI18N

        linkLabel.setText(org.openide.util.NbBundle.getMessage(AdsModuleDefinitionWizardStep1Panel.class, "AdsModuleDefinitionWizardStep1Panel.linkLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(lbEnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbEnv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(componentStub, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnv)
                    .addComponent(cbEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkLabel)
                    .addComponent(componentStub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbEnv;
    private org.radixware.kernel.designer.common.dialogs.components.DefinitionLinkEditPanel componentStub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbEnv;
    private javax.swing.JLabel linkLabel;
    private org.radixware.kernel.designer.common.dialogs.components.NameEditPanel nameEditor;
    // End of variables declaration//GEN-END:variables

    public boolean isComplete() {
        return nameEditor.isComplete();
    }

    public void setCurrentName(String name) {
        nameEditor.setCurrentName(name);
    }

    public void setLinkedDefinition(String label, ChooseDefinitionCfg config, Definition definition, Id id) {
        DefinitionLinkEditPanel panel = (DefinitionLinkEditPanel) componentStub;
        panel.open(config, definition, id);
        componentStub.setVisible(true);
        linkLabel.setText(label);
        linkLabel.setVisible(true);
    }

    public Definition getLinkedDefinition() {
        return ((DefinitionLinkEditPanel) componentStub).getDefinition();
    }

    public String getCurrentName() {
        return nameEditor.getCurrentName();
    }
    private ChangeSupport changeSupport = new ChangeSupport(this);

    public void addChangeListener(ChangeListener l) {
        changeSupport.addChangeListener(l);
    }

    public void removeChangeListener(ChangeListener l) {
        changeSupport.removeChangeListener(l);
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        changeSupport.fireChange();
    }

    public ERuntimeEnvironmentType getEnvironemnt() {
        return ERuntimeEnvironmentType.getForName(cbEnv.getSelectedItem().toString());
    }

    public void enableEnvironemnt(boolean enable, ERuntimeEnvironmentType e) {
        lbEnv.setVisible(enable);
        cbEnv.setVisible(enable);
        cbEnv.getModel().setSelectedItem(e);
    }

    public void setNameAcceptor(IAdvancedAcceptor<String> nameAcceptor) {
        nameEditor.setNameAcceptor(nameAcceptor);
    }
}
