/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.editors.msdl;

import java.awt.BorderLayout;
import org.radixware.kernel.common.defs.ads.msdl.AdsMsdlSchemeDef;
import org.radixware.kernel.common.design.msdleditor.field.RootPanel;
import org.radixware.kernel.common.msdl.RootMsdlScheme;
import org.radixware.kernel.designer.ads.common.dialogs.AccessEditPanel;
import org.radixware.kernel.designer.common.annotations.registrators.EditorFactoryRegistration;
import org.radixware.kernel.designer.common.editors.RadixObjectEditor;
import org.radixware.kernel.designer.common.general.editors.IEditorFactory;
import org.radixware.kernel.designer.common.general.editors.IRadixObjectEditor;
import org.radixware.kernel.designer.common.general.editors.OpenInfo;


public class RootMsdlSchemeEditor extends RadixObjectEditor<RootMsdlScheme> {

    protected RootMsdlSchemeEditor(RootMsdlScheme msdlScheme) {
        super(msdlScheme);
        initComponents();
    }

    @EditorFactoryRegistration
    public static final class Factory implements IEditorFactory<RootMsdlScheme> {

        @Override
        public IRadixObjectEditor newInstance(RootMsdlScheme msdlScheme) {
            return new RootMsdlSchemeEditor(msdlScheme);
        }
    }
  
    public AdsMsdlSchemeDef getMsdlScheme() {
        return (AdsMsdlSchemeDef)getRadixObject().getContainer();
    }

    private PreprocessorClassPanel preprocessorClassPanel = new PreprocessorClassPanel();
    @Override
    public boolean open(OpenInfo openInfo) {
        final AdsMsdlSchemeDef scheme = getMsdlScheme();
        getRootPanel().open(scheme.getRootMsdlScheme(),preprocessorClassPanel);
        preprocessorClassPanel.open(getMsdlScheme());
        return super.open(openInfo);
    }

    @Override
    public boolean isOpeningAfterNewObjectCreationRequired() {
        return true;
    }

    private RootPanel rootPanel = null;

    public RootPanel getRootPanel() {
        if (rootPanel == null) {
            rootPanel = new RootPanel();
            add(rootPanel);
        }
        return rootPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    @Override
    public void update() {
        getRootPanel().update();
        preprocessorClassPanel.update();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
} 
