/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.radixware.kernel.designer.ads.common.dialogs;

import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.miginfocom.swing.MigLayout;
import org.openide.util.ChangeSupport;
import org.radixware.kernel.common.defs.ads.common.ReleaseUtils;
import org.radixware.kernel.designer.common.dialogs.components.state.StateManager;


public class ReleaseNamePanel extends javax.swing.JPanel {

    public ReleaseNamePanel() {
        initComponents();
        setLayout(new MigLayout("fill, insets 5", "[shrink][grow]", "[][25:pref]"));
        add(jLabel1, "shrink");
        add(edReleaseVersion, "growx, wrap");
        add(stateDisplayer, "span");
    }

    public void open(boolean isPatch, String number, String title) {
        jLabel1.setText(title);
        this.edReleaseVersion.getDocument().removeDocumentListener(documentListener);
        this.isPatch = isPatch;
        if (number != null && !number.isEmpty()) {
            this.edReleaseVersion.setText(number);
        } else {
            this.edReleaseVersion.setText("");
        }
        this.edReleaseVersion.getDocument().addDocumentListener(documentListener);
        isReady();
        changeSupport.fireChange();
    }

    public boolean isReady() {
        String number = edReleaseVersion.getText();
        if (number.isEmpty() || ReleaseUtils.isValidReleaseName(number, isPatch)) {
            stateManager.ok();
            return true;
        } else {
            stateManager.error("Incorrect release number");
            return false;
        }
        
    }
    
    
    public void removeChangeListener(ChangeListener listener) {
        changeSupport.removeChangeListener(listener);
    }

    public void addChangeListener(ChangeListener listener) {
        changeSupport.addChangeListener(listener);
    }
    
    public String getText() {
        return edReleaseVersion.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edReleaseVersion = new javax.swing.JTextField();
        stateDisplayer = new org.radixware.kernel.designer.common.dialogs.components.state.StateDisplayer();

        setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ReleaseNamePanel.class, "ReleaseNamePanel.jLabel1.text")); // NOI18N
        add(jLabel1, java.awt.BorderLayout.WEST);

        edReleaseVersion.setText(org.openide.util.NbBundle.getMessage(ReleaseNamePanel.class, "ReleaseNamePanel.edReleaseVersion.text")); // NOI18N
        add(edReleaseVersion, java.awt.BorderLayout.CENTER);
        add(stateDisplayer, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    private final DocumentListener documentListener = new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            isReady();
            changeSupport.fireChange();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            isReady();
            changeSupport.fireChange();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            isReady();
            changeSupport.fireChange();
        }
    };
    private final ChangeSupport changeSupport = new ChangeSupport(this);
    private final StateManager stateManager = new StateManager(this);
    private boolean isPatch;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edReleaseVersion;
    private javax.swing.JLabel jLabel1;
    private org.radixware.kernel.designer.common.dialogs.components.state.StateDisplayer stateDisplayer;
    // End of variables declaration//GEN-END:variables
}
