/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * ChooseTypePanel.java
 *
 * Created on Jul 22, 2009, 4:23:29 PM
 */

package org.radixware.kernel.designer.common.editors.module.images;

import org.radixware.kernel.common.enums.ERadixIconType;


public class ChooseTypePanel extends javax.swing.JPanel {

    /** Creates new form ChooseTypePanel */
    public ChooseTypePanel() {
        initComponents();
    }

    public ERadixIconType getImageType() {
        if (svgRadioButton.isSelected())
            return ERadixIconType.SVG;
        if (pngRadioButton.isSelected())
            return ERadixIconType.PNG;
        if (gifRadioButton.isSelected())
            return ERadixIconType.GIF;
        if (jpgRadioButton.isSelected())
            return ERadixIconType.JPG;
//        if (bmpRadioButton.isSelected())
//            return ERadixIconType.BMP;
        return ERadixIconType.UNKNOWN;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        svgRadioButton = new javax.swing.JRadioButton();
        pngRadioButton = new javax.swing.JRadioButton();
        gifRadioButton = new javax.swing.JRadioButton();
        jpgRadioButton = new javax.swing.JRadioButton();

        buttonGroup1.add(svgRadioButton);
        svgRadioButton.setSelected(true);
        svgRadioButton.setText(org.openide.util.NbBundle.getMessage(ChooseTypePanel.class, "ChooseTypePanel.svgRadioButton.text")); // NOI18N

        buttonGroup1.add(pngRadioButton);
        pngRadioButton.setText(org.openide.util.NbBundle.getMessage(ChooseTypePanel.class, "ChooseTypePanel.pngRadioButton.text")); // NOI18N

        buttonGroup1.add(gifRadioButton);
        gifRadioButton.setText(org.openide.util.NbBundle.getMessage(ChooseTypePanel.class, "ChooseTypePanel.gifRadioButton.text")); // NOI18N

        buttonGroup1.add(jpgRadioButton);
        jpgRadioButton.setText(org.openide.util.NbBundle.getMessage(ChooseTypePanel.class, "ChooseTypePanel.jpgRadioButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(svgRadioButton)
                    .addComponent(pngRadioButton)
                    .addComponent(gifRadioButton)
                    .addComponent(jpgRadioButton))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svgRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pngRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gifRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpgRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton gifRadioButton;
    private javax.swing.JRadioButton jpgRadioButton;
    private javax.swing.JRadioButton pngRadioButton;
    private javax.swing.JRadioButton svgRadioButton;
    // End of variables declaration//GEN-END:variables

}
