/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * NullIndicatorPanel.java
 *
 * Created on 22.01.2009, 14:29:06
 */

package org.radixware.kernel.common.design.msdleditor.field.panel.simple;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;


public class ExtBoolPanel extends AbstractEditItem implements ActionListener {

    private Boolean defaultParentValue;
    private Boolean parentValue;
    private ActionListener al;


    /** Creates new form NullIndicatorPanel */
    public ExtBoolPanel() {
        initComponents();
        setParentPanel1.setEnabled(false);
        setParentPanel1.addActionListener(this);
        checkBox.addActionListener(this);
    }

    public void setDefaultParentValue(boolean defaultParentValue) {
        this.defaultParentValue = defaultParentValue;
    }

    public void addActionListener(final ActionListener l) {
        al = l;
    }
    
    public void removeActionListener(final ActionListener l) {
        al = null;
    }
    
    @Override
    public void setEnabled(boolean state) {
        checkBox.setEnabled(state);
        setParentPanel1.setEnabled(state);
    }
    

    private boolean parentValueExists() {
        return parentValue != null;
    }

    public void setEditable(boolean state) {
        checkBox.setEnabled(state);
    }
        
    public void setValue(Boolean value, Boolean parentValue) {
        if (parentValue == null && defaultParentValue != null) {
            parentValue = defaultParentValue;
        }
        this.parentValue = parentValue;
        setParentPanel1.setSelected(false);
        setValueImpl(value);
        setParentPanel1.setEnabled(parentValueExists());
        if (value == null) {
            setParentPanel1.setSelected(parentValueExists());
            setValueImpl(parentValue);
            checkBox.setEnabled(!parentValueExists());
        }
    }
    
    private void setValueImpl(Boolean b) {
        if (b != null) {
            checkBox.setSelected(b);
        }
    }

    public Boolean getValue() {
        if (setParentPanel1.getSelected()) {
            return null;
        }
        else {
            return checkBox.isSelected();
        }
    }
    
    public SetParentPanel getSetParentPanel() {
        return setParentPanel1;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBox = new javax.swing.JCheckBox();
        setParentPanel1 = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel();

        setPreferredSize(new java.awt.Dimension(100, 24));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/radixware/kernel/common/design/msdleditor/field/panel/simple/Bundle"); // NOI18N
        checkBox.setText(bundle.getString("ExtBoolPanel.checkBox.text")); // NOI18N
        checkBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(checkBox);
        add(setParentPanel1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBox;
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel setParentPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JCheckBox) {
            if (setParentPanel1.getSelected()) {
                setValueImpl(parentValue);
                checkBox.setEnabled(false);
            }
            else
                checkBox.setEnabled(true);
        }
        if (al != null)
            al.actionPerformed(new ActionEvent(this,0,null));
    }  
}
