/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * ExtCharPanel.java
 *
 * Created on 24.03.2009, 16:20:48
 */

package org.radixware.kernel.common.design.msdleditor.field.panel.simple;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;


public class ExtCharPanel extends AbstractEditItem implements ActionListener {

    private Character parentValue;
    private Character currentValue;
    private ActionListener al;

    /** Creates new form ExtCharPanel */
    public ExtCharPanel() {
        initComponents();
    }

    public void addActionListener(final ActionListener l) {
        charPanel1.addActionListener(this);
        setParentPanel1.addActionListener(this);
        al = l;
    }

    public void removeActionListener(final ActionListener l) {
        charPanel1.removeActionListener(this);
        setParentPanel1.removeActionListener(this);
        al = null;
    }

    public void setString(String value, String parentValue) {
        Character val = null;
        if (value != null && !value.equals(""))
            val = value.charAt(0);
        Character pval = null;
        if (parentValue != null && !parentValue.equals(""))
            pval = parentValue.charAt(0);
        setCharacter(val,pval);
    }

    public String getString() {
        Character ch = getCharacter();
        if (ch == null)
            return null;
        else
            return ch.toString();
    }

    public void setCharacter(Character value, Character parentValue) {
        this.parentValue = parentValue;
        this.currentValue = value;
        charPanel1.removeActionListener(this);
        charPanel1.setChar(value);
        setParentPanel1.setSelected(value == null && parentValue != null);
        setParentPanel1.setEnabled(parentValue != null);
        if (value == null)
            charPanel1.setChar(parentValue);
        charPanel1.setEnabled(value!=null||parentValue==null);
        charPanel1.addActionListener(this);
    }

    public Character getCharacter() {
        if (setParentPanel1.getSelected())
            return null;
        else
            return charPanel1.getChar();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        charPanel1 = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.CharPanel();
        setParentPanel1 = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(charPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setParentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(setParentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
            .addComponent(charPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.CharPanel charPanel1;
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel setParentPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JCheckBox) {
            JCheckBox cb = (JCheckBox)e.getSource();
            charPanel1.removeActionListener(this);
            if (cb.isSelected()) {
                charPanel1.setChar(parentValue);
                charPanel1.setEnabled(false);
            }
            else {
                charPanel1.setChar(null);
                charPanel1.setEnabled(true);
            }
            charPanel1.addActionListener(this);
        }
        currentValue = charPanel1.getChar();
        al.actionPerformed(new ActionEvent(this,1,""));
    }

}
