/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * NullIndicatorPanel.java
 *
 * Created on 22.01.2009, 14:29:06
 */

package org.radixware.kernel.common.design.msdleditor.field.panel.simple;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;
import org.radixware.kernel.common.msdl.enums.EEncoding;


public class ExtHexPanel extends AbstractEditItem implements ActionListener {

    private byte[] parentValue;
    private EEncoding parentViewType;
    private ActionListener al;


    /** Creates new form NullIndicatorPanel */
    public ExtHexPanel() {
        initComponents();
        setParentPanel1.setEnabled(false);
        setParentPanel1.addActionListener(this);
        hexPanel1.addActionListener(this);
    }

    public void addActionListener(final ActionListener l) {
        al = l;
    }
    
    @Override
    public void setEnabled(boolean state) {
        hexPanel1.setEnabled(state);
        setParentPanel1.setEnabled(state);
    }

    private boolean parentValueExists() {
        return parentValue != null && parentValue.length>0;
    }

    public void setEditable(boolean state) {
        hexPanel1.setEditable(state);
    }
        
    public void setValue(byte[] value, byte[] parentValue, EEncoding viewType, EEncoding parentViewType) {
        this.parentValue = parentValue;
        this.parentViewType = parentViewType;
        setParentPanel1.setSelected(false);
        hexPanel1.setValue(value, viewType);
        setParentPanel1.setEnabled(parentValueExists());
        if (value == null || value.length == 0) {
            setParentPanel1.setSelected(parentValueExists());
            hexPanel1.setValue(parentValue, parentViewType);
            hexPanel1.setEnabled(!parentValueExists());
        }
    }

    public byte[] getValue() {
        if (setParentPanel1.getSelected()) {
            return null;
        }
        else {
            return hexPanel1.getValue();
        }
    }
    
    public EEncoding getViewEncoding() {
        if (setParentPanel1.getSelected()) {
            return null;
        }
        else {
            return hexPanel1.getViewEncoding();
        }
    }
    
    public String getViewEncodingAsStr() {
        if (setParentPanel1.getSelected()) {
            return null;
        }
        else {
            return hexPanel1.getViewEncoding().getValue();
        }
    } 
    
    public SetParentPanel getSetParentPanel() {
        return setParentPanel1;
    }
    
    public void setLimit(int limit) {
        hexPanel1.setLimit(limit);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hexPanel1 = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.HexPanel();
        setParentPanel1 = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel();

        setPreferredSize(new java.awt.Dimension(100, 24));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
        add(hexPanel1);
        add(setParentPanel1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.HexPanel hexPanel1;
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel setParentPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JCheckBox) {
            if (setParentPanel1.getSelected()) {
                hexPanel1.setValue(parentValue, parentViewType);
                hexPanel1.setEnabled(false);
            }
            else
                hexPanel1.setEnabled(true);
        }
        if (al != null)
            al.actionPerformed(new ActionEvent(this,0,null));
    }  
}
