/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * SetParentPanel.java
 *
 * Created on 22.01.2009, 13:22:22
 */

package org.radixware.kernel.common.design.msdleditor.field.panel.simple;

import java.awt.event.ActionListener;
import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;


public class SetParentPanel extends AbstractEditItem {

    /** Creates new form SetParentPanel */
    public SetParentPanel() {
        initComponents();
    }

    public void setSelected(boolean state) {
        jCheckBox.setSelected(state);
    }

    public boolean getSelected() {
        return jCheckBox.getModel().isSelected();
    }

    @Override
    public void setEnabled(boolean state) {
        jCheckBox.setEnabled(state);
        super.setEnabled(state);
    }

    public boolean getEnabled() {
        return jCheckBox.isEnabled();
    }

    public void addActionListener(ActionListener l) {
        jCheckBox.addActionListener(l);
    }

    public void removeActionListener(ActionListener l) {
        jCheckBox.removeActionListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(20, 20));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/radixware/kernel/common/design/msdleditor/field/panel/simple/Bundle"); // NOI18N
        jCheckBox.setText(bundle.getString("SetParentPanel.jCheckBox.text")); // NOI18N
        jCheckBox.setToolTipText(bundle.getString("INHERIT")); // NOI18N
        add(jCheckBox);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox;
    // End of variables declaration//GEN-END:variables

}
