/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * AlignPanel.java
 *
 * Created on 22.01.2009, 11:21:49
 */

package org.radixware.kernel.common.design.msdleditor.field.panel.simple;

import java.awt.event.ActionListener;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;
import org.radixware.kernel.common.design.msdleditor.enums.EShieldedFormat;


public class ShieldedFormatPanel extends AbstractEditItem {

    private EShieldedFormat parentValue;
    public static class SchieldedFormatModel extends DefaultComboBoxModel {
        public SchieldedFormatModel() {
            super(new EShieldedFormat[]{EShieldedFormat.NOTDEFINED,EShieldedFormat.ASIS,EShieldedFormat.HEX});
        }
    }

    /** Creates new form AlignPanel */
    public ShieldedFormatPanel() {
        initComponents();
        setModel(new SchieldedFormatModel());
    }

    public void addActionListener(final ActionListener l) {
        jComboBoxUnit.addActionListener(l);
    }

    public void removeActionListener(final ActionListener l) {
        jComboBoxUnit.removeActionListener(l);
    }


    public void setModel(ComboBoxModel model) {
        jComboBoxUnit.setModel(model);
    }

    public void setShieldedFormat(EShieldedFormat value, EShieldedFormat parentValue) {
        this.parentValue = parentValue;
        getSetParentPanel().setSelected(false);
        jComboBoxUnit.getModel().setSelectedItem(value);
        getSetParentPanel().setEnabled(parentValue != EShieldedFormat.NOTDEFINED);
        if (value == EShieldedFormat.NOTDEFINED) {
            getSetParentPanel().setSelected(parentValue != EShieldedFormat.NOTDEFINED);
            jComboBoxUnit.getModel().setSelectedItem(parentValue);
            jComboBoxUnit.setEnabled(parentValue == EShieldedFormat.NOTDEFINED);
        }
    }

    public EShieldedFormat getShieldedFormat() {
        if (getSetParentPanel().getSelected()) {
            jComboBoxUnit.getModel().setSelectedItem(parentValue);
            jComboBoxUnit.setEnabled(false);
            return EShieldedFormat.NOTDEFINED;
        }
        else {
            jComboBoxUnit.setEnabled(true);
            EShieldedFormat result = (EShieldedFormat)jComboBoxUnit.getModel().getSelectedItem();
            if (result == EShieldedFormat.NOTDEFINED && parentValue != EShieldedFormat.NOTDEFINED) {
                jComboBoxUnit.getModel().setSelectedItem(parentValue);
                jComboBoxUnit.setEnabled(false);
                getSetParentPanel().setSelected(true);
            }
            return result;
        }
    }

    public SetParentPanel getSetParentPanel() {
        return setParentPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxUnit = new javax.swing.JComboBox();
        setParentPanel = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jComboBoxUnit, 0, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBoxUnit)
            .addComponent(setParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxUnit;
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel setParentPanel;
    // End of variables declaration//GEN-END:variables

}
