/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * SortingsPanel.java
 *
 * Created on Apr 27, 2009, 10:47:08 AM
 */
package org.radixware.kernel.designer.ads.editors.filters;

import java.awt.BorderLayout;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.radixware.kernel.common.defs.ads.clazz.presentation.AdsFilterDef;
import org.radixware.kernel.designer.common.editors.sqml.SqmlEditorPanel;


public class SortingsPanel extends javax.swing.JPanel {

    private SqmlEditorPanel sqmlEditor = new SqmlEditorPanel();

    /** Creates new form SortingsPanel */
    public SortingsPanel() {
        super();
        initComponents();
        defaultAndBaseSortingsPanel1.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                SortingsPanel.this.onSelectionChange();
            }
        });

        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(sqmlEditor, BorderLayout.NORTH);
    }

    private void onSelectionChange() {
        AdsFilterDef.EnabledSorting selected = defaultAndBaseSortingsPanel1.getSelectedEnabledSorting();

        if (selected != null) {
            sqmlEditor.open(selected.getHint());
            sqmlEditor.setEnabled(true);
        } else {
            sqmlEditor.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultAndBaseSortingsPanel1 = new org.radixware.kernel.designer.ads.editors.presentations.DefaultAndBaseSortingsPanel();
        jPanel1 = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(SortingsPanel.class, "EnabledSortingHint"))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 115));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 115));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(defaultAndBaseSortingsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(defaultAndBaseSortingsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private AdsFilterDef filter;

    public void open(AdsFilterDef adsFilterDef) {
        this.filter = adsFilterDef;
        defaultAndBaseSortingsPanel1.open(filter);
        onSelectionChange();
    }

    public void update() {
        defaultAndBaseSortingsPanel1.update();
        onSelectionChange();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.radixware.kernel.designer.ads.editors.presentations.DefaultAndBaseSortingsPanel defaultAndBaseSortingsPanel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
