/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.editors.clazz.algo.workflow.dialog;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import org.openide.util.NbBundle;
import org.radixware.kernel.common.defs.ads.clazz.algo.object.*;
import org.radixware.kernel.designer.common.editors.jml.JmlEditor;
import org.radixware.kernel.common.enums.EEventSeverity;


public class EdgePanel extends EditorDialog.EditorPanel<AdsEdge> {

    public EdgePanel(AdsEdge edge) {
        super(edge);
        initComponents();
/*
        EEventSeverity[] es = new EEventSeverity[] {
            EEventSeverity.ALARM,
            EEventSeverity.DEBUG,
            EEventSeverity.ERROR,
            EEventSeverity.EVENT,
            EEventSeverity.WARNING
        };

        comboSeverity.setModel(new javax.swing.DefaultComboBoxModel(
                new EEventSeverity[] { EEventSeverity.ALARM, EEventSeverity.DEBUG, EEventSeverity.ERROR, EEventSeverity.EVENT, EEventSeverity.WARNING}
                ));
*/
        comboSeverity.setModel(
            new javax.swing.DefaultComboBoxModel(
                new EEventSeverity[] {
                    EEventSeverity.ALARM,
                    EEventSeverity.ERROR,
                    EEventSeverity.WARNING,
                    EEventSeverity.EVENT,
                    EEventSeverity.DEBUG
                    }
                )
            );

        editor.setBorder(BorderFactory.createLineBorder(new Color(127, 157, 185), 1));
        editor.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(127, 157, 185), 1), NbBundle.getMessage(EdgePanel.class, "EdgePanel.trace.text")));
        panelEditor.add(editor);

        comboSeverity.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                obj.setTraceSeverity((EEventSeverity) comboSeverity.getSelectedItem());
            }                
        });
        comboSeverity.setEnabled(!edge.isReadOnly());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSeverity = new javax.swing.JLabel();
        panelEditor = new javax.swing.JPanel();
        comboSeverity = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(500, 300));
        setRequestFocusEnabled(false);

        labelSeverity.setText(org.openide.util.NbBundle.getMessage(EdgePanel.class, "EdgePanel.labelSeverity.text")); // NOI18N

        panelEditor.setLayout(new java.awt.BorderLayout());

        comboSeverity.setModel(new javax.swing.DefaultComboBoxModel(new EEventSeverity[] { EEventSeverity.ALARM, EEventSeverity.DEBUG, EEventSeverity.ERROR, EEventSeverity.EVENT, EEventSeverity.WARNING}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSeverity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
            .addComponent(panelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeverity)
                    .addComponent(comboSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboSeverity;
    private javax.swing.JLabel labelSeverity;
    private javax.swing.JPanel panelEditor;
    // End of variables declaration//GEN-END:variables

    private final JmlEditor editor = new JmlEditor();

    @Override
    public void init() {
        comboSeverity.setSelectedItem(obj.getTraceSeverity());
        editor.open(obj.getTraceSource());
        editor.requestFocusInWindow();
    }

    @Override
    public void apply() {
    }

    @Override
    public String getTitle() {
        return NbBundle.getMessage(getClass(), "CTL_EdgePanel");
    }
}
