/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.editors.clazz.algo.workflow.dialog;

import org.radixware.kernel.common.defs.ads.AdsDefinition;
import org.radixware.kernel.common.defs.ads.clazz.algo.object.AdsAppObject;
import org.radixware.kernel.common.defs.ads.localization.AdsMultilingualStringDef;
import org.radixware.kernel.common.defs.localization.IMultilingualStringDef;
import org.radixware.kernel.common.enums.EIsoLanguage;
import org.radixware.kernel.common.types.Id;
import org.radixware.kernel.common.utils.RadixResourceBundle;
import org.radixware.kernel.designer.common.dialogs.components.localizing.HandleInfo;


public class SubmitVariantPanel extends javax.swing.JPanel {
    private Id titleId;
    final private AdsAppObject obj;

    /** Creates new form TypePropertyChoosePanel */
    public SubmitVariantPanel(AdsAppObject obj, Id titleId, Boolean confirm, Boolean update, Boolean visible) {
        initComponents();

        this.obj = obj;
        this.titleId = titleId;
        panelTitle.open(new HandleInfo() {
            @Override
            public AdsDefinition getAdsDefinition() {
                return SubmitVariantPanel.this.obj.getOwnerClass();
            }
            @Override
            public Id getTitleId() {
                return SubmitVariantPanel.this.titleId;
            }
            @Override
            protected void onAdsMultilingualStringDefChange(IMultilingualStringDef multilingualStringDef) {
                SubmitVariantPanel.this.titleId = multilingualStringDef != null ? multilingualStringDef.getId() : null;
            }
            @Override
            protected void onLanguagesPatternChange(EIsoLanguage language, String newStringValue) {
                getAdsMultilingualStringDef().setValue(language, newStringValue);
            }
        });

        if (confirm != null)
            chkConfirmation.setSelected(confirm);
        else
            chkConfirmation.setSelected(true);

        if (update != null)
            chkUpdate.setSelected(update);
        else
            chkUpdate.setSelected(true);

        if (visible != null)
            chkVisible.setSelected(visible);
        else
            chkVisible.setSelected(true);
    }

    public Id getTitleId(){
        return titleId;
    }

    public Boolean getConfirmation(){
        return Boolean.valueOf(chkConfirmation.isSelected());
    }

    public Boolean getUpdate(){
        return Boolean.valueOf(chkUpdate.isSelected());
    }

    public Boolean getVisible(){
        return Boolean.valueOf(chkVisible.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbVisible = new javax.swing.JLabel();
        chkConfirmation = new javax.swing.JCheckBox();
        lbConfirmation = new javax.swing.JLabel();
        chkVisible = new javax.swing.JCheckBox();
        lbUpdate = new javax.swing.JLabel();
        chkUpdate = new javax.swing.JCheckBox();
        panelTitle = new org.radixware.kernel.designer.common.dialogs.components.localizing.LocalizingEditorPanel(RadixResourceBundle.getMessage(getClass(), "SubmitVariantPanel.panelTitle.text"));

        setPreferredSize(new java.awt.Dimension(350, 94));
        setRequestFocusEnabled(false);

        lbVisible.setText(org.openide.util.NbBundle.getMessage(SubmitVariantPanel.class, "SubmitVariantPanel.lbVisible.text")); // NOI18N

        chkConfirmation.setSelected(true);
        chkConfirmation.setText(org.openide.util.NbBundle.getMessage(SubmitVariantPanel.class, "SubmitVariantPanel.chkConfirmation.text")); // NOI18N
        chkConfirmation.setMargin(new java.awt.Insets(0, 0, 2, 2));

        lbConfirmation.setText(org.openide.util.NbBundle.getMessage(SubmitVariantPanel.class, "SubmitVariantPanel.lbConfirmation.text")); // NOI18N

        chkVisible.setSelected(true);
        chkVisible.setText(org.openide.util.NbBundle.getMessage(SubmitVariantPanel.class, "SubmitVariantPanel.chkVisible.text")); // NOI18N
        chkVisible.setMargin(new java.awt.Insets(0, 0, 2, 2));
        chkVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVisibleActionPerformed(evt);
            }
        });

        lbUpdate.setText(org.openide.util.NbBundle.getMessage(SubmitVariantPanel.class, "SubmitVariantPanel.lbUpdate.text")); // NOI18N

        chkUpdate.setSelected(true);
        chkUpdate.setText(org.openide.util.NbBundle.getMessage(SubmitVariantPanel.class, "SubmitVariantPanel.chkUpdate.text")); // NOI18N
        chkUpdate.setMargin(new java.awt.Insets(0, 0, 2, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUpdate)
                    .addComponent(lbVisible)
                    .addComponent(lbConfirmation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkConfirmation)
                    .addComponent(chkUpdate)
                    .addComponent(chkVisible))
                .addContainerGap(273, Short.MAX_VALUE))
            .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkConfirmation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbConfirmation, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUpdate)
                    .addComponent(chkUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkVisible)
                    .addComponent(lbVisible)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVisibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVisibleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkConfirmation;
    private javax.swing.JCheckBox chkUpdate;
    private javax.swing.JCheckBox chkVisible;
    private javax.swing.JLabel lbConfirmation;
    private javax.swing.JLabel lbUpdate;
    private javax.swing.JLabel lbVisible;
    private org.radixware.kernel.designer.common.dialogs.components.localizing.LocalizingEditorPanel panelTitle;
    // End of variables declaration//GEN-END:variables

}
