/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.editors.clazz.algo.workflow.dialog;

import java.awt.Color;
import javax.swing.BorderFactory;
import org.openide.util.NbBundle;
import org.radixware.kernel.common.defs.RadixObject;
import org.radixware.kernel.common.defs.VisitorProvider;
import org.radixware.kernel.common.defs.ads.clazz.AdsExceptionClassDef;
import org.radixware.kernel.common.defs.ads.clazz.algo.object.*;
import org.radixware.kernel.designer.common.dialogs.chooseobject.ChooseDefinition;
import org.radixware.kernel.designer.common.dialogs.chooseobject.ChooseDefinitionCfg;
import org.radixware.kernel.designer.common.editors.jml.JmlEditor;


public class ThrowPanel extends EditorDialog.EditorPanel<AdsThrowObject> {

    public ThrowPanel(AdsThrowObject node) {
        super(node);
        initComponents();

        panelEditor.add(editor);
        editor.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(127, 157, 185), 1), NbBundle.getMessage(ThrowPanel.class, "ThrowPanel.Parameters")));

        textException.setEnabled(!node.isReadOnly());
        buttonException.setEnabled(!node.isReadOnly());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEditor = new javax.swing.JPanel();
        textException = new javax.swing.JTextField();
        labelException = new javax.swing.JLabel();
        buttonException = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(500, 300));
        setRequestFocusEnabled(false);

        panelEditor.setLayout(new java.awt.BorderLayout());

        textException.setEditable(false);

        labelException.setText(org.openide.util.NbBundle.getMessage(ThrowPanel.class, "ThrowPanel.labelException.text")); // NOI18N

        buttonException.setText("...");
        buttonException.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExceptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelException)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textException, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonException, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelException)
                    .addComponent(buttonException)
                    .addComponent(textException, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExceptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExceptionActionPerformed

        VisitorProvider provider = new VisitorProvider() {

            @Override
            public boolean isContainer(RadixObject object) {
                return true;
            }

            @Override
            public boolean isTarget(RadixObject object) {
                return object instanceof AdsExceptionClassDef;
            }
        };

        AdsPage page = obj.getOwnerPage();
        ChooseDefinitionCfg cfg = ChooseDefinitionCfg.Factory.newInstance(page, provider);
        AdsExceptionClassDef exceptionDef = (AdsExceptionClassDef) ChooseDefinition.chooseDefinition(cfg);

        if (obj.getExceptionDef() != exceptionDef) {
            obj.setExceptionDef(exceptionDef);
            textException.setText(exceptionDef != null ? exceptionDef.getQualifiedName() : NbBundle.getMessage(getClass(), "Panel.empty.text"));
        }

}//GEN-LAST:event_buttonExceptionActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonException;
    private javax.swing.JLabel labelException;
    private javax.swing.JPanel panelEditor;
    private javax.swing.JTextField textException;
    // End of variables declaration//GEN-END:variables

    private final JmlEditor editor = new JmlEditor();

    @Override
    public void init() {
        AdsExceptionClassDef exceptionDef = obj.getExceptionDef();
        textException.setText(exceptionDef != null ? exceptionDef.getQualifiedName() : NbBundle.getMessage(getClass(), "Panel.empty.text"));

        editor.open(obj.getParameters());
    }

    @Override
    public void apply() {
    }

    @Override
    public String getTitle() {
        return NbBundle.getMessage(getClass(), "CTL_ThrowPanel");
    }
}
