/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.dds.editors.table;

import org.radixware.kernel.common.defs.dds.DdsViewDef;


public class ViewPanel extends javax.swing.JPanel {
    
    private final DdsViewDef view;
    private boolean readOnly = false;
    private final boolean inherited;
    private final ViewTablesPanel viewTablesPanel;

    /**
     * Creates new form ViewPanel
     */
    public ViewPanel(DdsViewDef view) {
        initComponents();
        this.view = view;
        inherited = view.findOverwritten() != null;
        this.splitter.setLeftComponent(viewTablesPanel = new ViewTablesPanel());
        viewTablesPanel.open(view);
        sqmlEditorPanel.open(view.getSqml());
    }
    
    public void setReadOnly(boolean readOnly) {
        this.readOnly = readOnly;
        updateEnableState();
    }
    
    private void updateEnableState() {
        sqmlEditorPanel.setEditable(!readOnly && !inherited);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitter = new javax.swing.JSplitPane();
        sqmlEditorPanel = new org.radixware.kernel.designer.common.editors.sqml.SqmlEditorPanel();

        setLayout(new java.awt.BorderLayout());

        splitter.setRightComponent(sqmlEditorPanel);

        add(splitter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane splitter;
    private org.radixware.kernel.designer.common.editors.sqml.SqmlEditorPanel sqmlEditorPanel;
    // End of variables declaration//GEN-END:variables
}
