/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * InheritableObjectTitleFormatPanel.java
 *
 * Created on 20.08.2009, 13:36:34
 */
package org.radixware.kernel.designer.ads.editors.presentations;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import org.openide.util.NbBundle;
import org.radixware.kernel.common.defs.ExtendableDefinitions.EScope;
import org.radixware.kernel.common.defs.ads.clazz.members.AdsPropertyDef;
import org.radixware.kernel.common.defs.ads.clazz.presentation.AdsEditorPresentationDef;
import org.radixware.kernel.designer.ads.editors.clazz.simple.IAdsPropertiesListProvider;


public class InheritableObjectTitleFormatPanel extends javax.swing.JPanel {

    /** Creates new form InheritableObjectTitleFormatPanel */
    public InheritableObjectTitleFormatPanel() {
        initComponents();
        ActionListener inheritListener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                InheritableObjectTitleFormatPanel.this.onInheritanceChange();
            }
        };
        inheritCheck.addActionListener(inheritListener);
    }

    @Override
    public String getName() {
        return NbBundle.getMessage(InheritableObjectTitleFormatPanel.class, "ObjectTitleFormatTip");
    }

    private void onInheritanceChange() {
        if (!isUpdate) {
            boolean isSelected = inheritCheck.isSelected();
            presentation.setObjectTitleFormatInherited(isSelected);
            update();
        }
    }
    private AdsEditorPresentationDef presentation;

    public void open(final AdsEditorPresentationDef presentation) {
        this.presentation = presentation;
        update();
    }
    private boolean isUpdate = false;

    public void update() {
        if (presentation != null) {
            isUpdate = true;

            boolean readonly = presentation.isReadOnly();
            boolean isInherited = presentation.isObjectTitleFormatInherited();

            inheritCheck.setSelected(isInherited);
            inheritCheck.setEnabled(!readonly);

            objectTitleFormatPanel.open(presentation.getObjectTitleFormat(), new IAdsPropertiesListProvider(){

                 @Override
                 public List<AdsPropertyDef> getAdsPropertiesList() {
                     return presentation.getOwnerClass().getProperties().get(EScope.ALL);
                 }

            });
            objectTitleFormatPanel.setReadonly(readonly || isInherited);

            isUpdate = false;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        inheritCheck = new javax.swing.JCheckBox();
        objectTitleFormatPanel = new org.radixware.kernel.designer.ads.editors.clazz.simple.ObjectTitleFormatPanel();

        setLayout(new java.awt.GridBagLayout());

        inheritCheck.setText(org.openide.util.NbBundle.getMessage(InheritableObjectTitleFormatPanel.class, "InheritConditions")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(inheritCheck, gridBagConstraints);

        objectTitleFormatPanel.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(objectTitleFormatPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox inheritCheck;
    private org.radixware.kernel.designer.ads.editors.clazz.simple.ObjectTitleFormatPanel objectTitleFormatPanel;
    // End of variables declaration//GEN-END:variables
}
