/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * TestPanel.java
 *
 * Created on Sep 23, 2009, 11:09:15 AM
 */

package org.radixware.kernel.designer.ads.localization.dialog;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JLabel;
import org.radixware.kernel.designer.ads.localization.dialog.StatisticsPanel.StatisticsInfo;


public class StatisticsInformationPanel extends javax.swing.JPanel  {

    public StatisticsInformationPanel() {
        initComponents();
    }

    public void  open(final List<StatisticsInfo> statistic) {
        removeAll();
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        for (StatisticsInfo statistInfo : statistic){
            final JLabel label=new JLabel();
            final MyIcon icon=new MyIcon(statistInfo.getColor());
            label.setIcon(icon);
            final String text= " - Translation to "+ statistInfo.getLabel() +": "+ statistInfo.getPersent()+"%";
            label.setText(text);
            this.add(label);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    private class MyIcon implements Icon {
        private final Color color;

        public MyIcon(final Color color) {
            this.color=color;
        }

        @Override
        public void paintIcon(final Component c, final Graphics g, final int x, final int y) {
            final Color savedPen = g.getColor();
            g.setColor(color);
            g.fillRect(0, 0, 16, 16);
            g.setColor(savedPen);
        }

        @Override
        public int getIconWidth() {
           return 16;
        }

        @Override
        public int getIconHeight() {
            return 16;
        }

    }
}
