/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.editors.clazz.algo.workflow.dialog;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.util.NbBundle;
import org.radixware.kernel.common.defs.ads.clazz.algo.object.*;
import org.radixware.kernel.designer.ads.editors.clazz.algo.workflow.palette.Item;


public class TabbedPanel extends EditorDialog.EditorPanel<AdsAppObject> {

    private final List<EditorDialog.EditorPanel> panels;

    public TabbedPanel(final AdsAppObject node, List<EditorDialog.EditorPanel> panels) {
        super(node);
        initComponents();

        int idx = 0;
        for (EditorDialog.EditorPanel panel: panels) {
            panelTab.add(panel.getTitle(), panel);
            panelTab.setIconAt(idx++, panel.getIcon() != null ? panel.getIcon().getIcon() : null);
            panel.setEnabled(!obj.isReadOnly());
        }

        textName.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                obj.setName(textName.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                obj.setName(textName.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                obj.setName(textName.getText());
            }
        });
        
        textName.setEnabled(!node.isReadOnly());
        this.panels = panels;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        panelTab = new javax.swing.JTabbedPane();

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setRequestFocusEnabled(false);

        labelName.setText(org.openide.util.NbBundle.getMessage(TabbedPanel.class, "TabbedPanel.labelName.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelTab, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTab, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
        );

        panelTab.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelName;
    private javax.swing.JTabbedPane panelTab;
    private javax.swing.JTextField textName;
    // End of variables declaration//GEN-END:variables

    private static final int DX = 20;
    private static final int DY = 65;

    @Override
    public Dimension getPreferredSize() {
        Dimension size = super.getPreferredSize();
        for (EditorDialog.EditorPanel panel: panels) {
            Dimension sz = panel.getPreferredSize();
            size.width = Math.max(size.width, sz.width + DX);
            size.height = Math.max(size.height, sz.height + DY);
        }
        return size;
    }

    @Override
    public Dimension getMinimumSize() {
        Dimension size = super.getMinimumSize();
        for (EditorDialog.EditorPanel panel: panels) {
            Dimension sz = panel.getMinimumSize();
            size.width = Math.max(size.width, sz.width + DX);
            size.height = Math.max(size.height, sz.height + DY);
        }
        return size;
    }

    @Override
    public void init() {
        textName.setText(obj.getName());
        for (EditorDialog.EditorPanel panel: panels) {
            panel.init();
            panel.activate();
        }

        //int sel = panelTab.getSelectedIndex();
        //if (sel >=0 && sel <= panels.size()-1)
        //    panels.get(sel).activate();

        panelTab.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent evt) {
                int sel = panelTab.getSelectedIndex();
                if (sel >=0 && sel <= panels.size()-1)
                    panels.get(sel).activate();
            }
        });

        textName.requestFocusInWindow();
    }

    @Override
    public void apply() {
        for (EditorDialog.EditorPanel panel: panels)
            panel.apply();
    }

    @Override
    public String getTitle() {
        String title = NbBundle.getMessage(getClass(), "CTL_Properties");
        Item item = Item.getItem(obj);
        if (item != null)
            title = item.getTitle() + " " + title;
        return title;
    }
}
