/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.utils.keyStoreAdmin.dialogs;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import org.jdesktop.application.Action;

import org.radixware.kernel.utils.keyStoreAdmin.utils.KeyStoreAdminFileFilter;
import org.radixware.kernel.utils.keyStoreAdmin.utils.KeyStoreAdminFileSelector;
import org.radixware.kernel.utils.keyStoreAdmin.utils.KeyStoreAdminFileSelector.SelectNewFileMode;



public class SignCertificateDialog extends AKeyStoreAdminDialog {

    private static final ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/radixware/kernel/utils/keyStoreAdmin/resources/SignCertificateDialog");

    private String alias;
    private String requestFilePath;
    private String certificateFilePath;
    private int durationDays;
    private String defaultRequestFilePath;
    private String defaultCertificateFilePath;

    /** Creates new form CertificateRequestDialog */
    public SignCertificateDialog(java.awt.Frame parent, String[] aliases,
            String defaultAlias, String defaultRequestFilePath, String defaultCertificateFilePath,
            int defaultDurationDays) {
        super(parent);
        initComponents();

        DefaultComboBoxModel model = new DefaultComboBoxModel(aliases);
        jComboBoxAlias.setModel(model);
        jComboBoxAlias.setSelectedItem(defaultAlias);

        jSpinnerDurationDays.setValue(defaultDurationDays);

        this.defaultRequestFilePath = defaultRequestFilePath;
        this.defaultCertificateFilePath = defaultCertificateFilePath;
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    public String getAlias(){
        return alias;
    }

    public String getRequestFilePath(){
        return requestFilePath;
    }

    public String getCertificateFilePath(){
        return certificateFilePath;
    }

    public int getDurationDays(){
        return durationDays;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabelAlias = new javax.swing.JLabel();
        jLabelRequestFile = new javax.swing.JLabel();
        jComboBoxAlias = new javax.swing.JComboBox();
        jTextFieldRequestFile = new javax.swing.JTextField();
        jButtonRequestFile = new javax.swing.JButton();
        jLabelCertificateFile = new javax.swing.JLabel();
        jTextFieldCertificateFile = new javax.swing.JTextField();
        jButtonCertificateFile = new javax.swing.JButton();
        jLabelDurationDays = new javax.swing.JLabel();
        jSpinnerDurationDays = new javax.swing.JSpinner();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/radixware/kernel/utils/keyStoreAdmin/resources/SignCertificateDialog"); // NOI18N
        setTitle(bundle.getString("Dialog.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("org/radixware/kernel/utils/keyStoreAdmin/resources/CertificateRequestDialog"); // NOI18N
        okButton.setText(bundle1.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(bundle1.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabelAlias.setLabelFor(jComboBoxAlias);
        jLabelAlias.setText(bundle.getString("jLabelAlias.text")); // NOI18N
        jLabelAlias.setName("jLabelAlias"); // NOI18N

        jLabelRequestFile.setLabelFor(jTextFieldRequestFile);
        jLabelRequestFile.setText(bundle.getString("jLabelRequestFile.text")); // NOI18N
        jLabelRequestFile.setName("jLabelRequestFile"); // NOI18N

        jComboBoxAlias.setName("jComboBoxAlias"); // NOI18N

        jTextFieldRequestFile.setEditable(false);
        jTextFieldRequestFile.setName("jTextFieldRequestFile"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(org.radixware.kernel.utils.keyStoreAdmin.KeyStoreAdmin.class).getContext().getActionMap(SignCertificateDialog.class, this);
        jButtonRequestFile.setAction(actionMap.get("selectRequestFile")); // NOI18N
        jButtonRequestFile.setName("jButtonRequestFile"); // NOI18N

        jLabelCertificateFile.setLabelFor(jTextFieldCertificateFile);
        jLabelCertificateFile.setText(bundle.getString("jLabelCertificateFile.text")); // NOI18N
        jLabelCertificateFile.setName("jLabelCertificateFile"); // NOI18N

        jTextFieldCertificateFile.setEditable(false);
        jTextFieldCertificateFile.setName("jTextFieldCertificateFile"); // NOI18N

        jButtonCertificateFile.setAction(actionMap.get("selectCertificateFile")); // NOI18N
        jButtonCertificateFile.setName("jButtonCertificateFile"); // NOI18N

        jLabelDurationDays.setLabelFor(jSpinnerDurationDays);
        jLabelDurationDays.setText(bundle.getString("jLabelDurationDays.text")); // NOI18N
        jLabelDurationDays.setName("jLabelDurationDays"); // NOI18N

        jSpinnerDurationDays.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(90), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpinnerDurationDays.setName("jSpinnerDurationDays"); // NOI18N
        ((javax.swing.JSpinner.DefaultEditor)jSpinnerDurationDays.getEditor()).getTextField().addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                char key = e.getKeyChar();
                if (!Character.isDigit(key) && key!=KeyEvent.VK_BACK_SPACE && key!=KeyEvent.VK_DELETE)
                e.consume();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAlias)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton))
                            .addComponent(jComboBoxAlias, 0, 231, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRequestFile, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabelCertificateFile)
                            .addComponent(jLabelDurationDays))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerDurationDays, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCertificateFile, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jTextFieldRequestFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonRequestFile, 0, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonCertificateFile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlias)
                    .addComponent(jComboBoxAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRequestFile)
                    .addComponent(jTextFieldRequestFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRequestFile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCertificateFile)
                    .addComponent(jTextFieldCertificateFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCertificateFile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDurationDays)
                    .addComponent(jSpinnerDurationDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    protected void doClose(int retStatus) {
        returnStatus = retStatus;
        if (returnStatus==RET_OK){
            if (!checkInput())
                return;
            alias = (String)jComboBoxAlias.getSelectedItem();
            requestFilePath = jTextFieldRequestFile.getText();
            certificateFilePath = jTextFieldCertificateFile.getText();
            durationDays = (Integer)jSpinnerDurationDays.getValue();
        }

        setVisible(false);
        dispose();
    }

    /** Checks that input values are valid */
    private boolean checkInput(){
        String messageBoxTitle = bundle.getString("JOptionPaneInputError.title");
        String message;

        if (jTextFieldRequestFile.getText().length()==0){
            message = bundle.getString("RequestFilePathIsEmpty");
            JOptionPane.showMessageDialog(this, message, messageBoxTitle, JOptionPane.ERROR_MESSAGE);
            jTextFieldRequestFile.requestFocusInWindow();
            return false;
        }
        
        File tmpFile = new File(jTextFieldRequestFile.getText());
        if (tmpFile.exists()){
            if (!tmpFile.isFile()){
                message = bundle.getString("NotAFileRequest");
                JOptionPane.showMessageDialog(this, message, messageBoxTitle, JOptionPane.ERROR_MESSAGE);
                jTextFieldRequestFile.requestFocusInWindow();
                return false;
            }
        }

        if (jTextFieldCertificateFile.getText().length()==0){
            message = bundle.getString("CertificateFilePathIsEmpty");
            JOptionPane.showMessageDialog(this, message, messageBoxTitle, JOptionPane.ERROR_MESSAGE);
            jTextFieldCertificateFile.requestFocusInWindow();
            return false;
        }

        tmpFile = new File(jTextFieldCertificateFile.getText());
        if (tmpFile.exists()){
            if (!tmpFile.isFile()){
                message = bundle.getString("NotAFileCertificate");
                JOptionPane.showMessageDialog(this, message, messageBoxTitle, JOptionPane.ERROR_MESSAGE);
                jTextFieldCertificateFile.requestFocusInWindow();
                return false;
            }
        }

        return true;
    }

    @Action
    public void selectRequestFile(){
        String title = bundle.getString("openCertificateRequestChooser.dialogTitle");
        KeyStoreAdminFileFilter filter = new KeyStoreAdminFileFilter(new String[]{"csr"}, "Certificate signing request (*.csr)");
        File selectedFile = KeyStoreAdminFileSelector.selectFileForOpen(this, title, new KeyStoreAdminFileFilter[]{filter}, defaultRequestFilePath, SelectNewFileMode.FORBIDDEN);
        if (selectedFile!=null)
            jTextFieldRequestFile.setText(selectedFile.getAbsolutePath());
    }

    @Action
    public void selectCertificateFile(){
        String title = bundle.getString("saveCertificateChooser.dialogTitle");
        KeyStoreAdminFileFilter filter = new KeyStoreAdminFileFilter(new String[]{"cer"}, "Signed certificate (*.cer)");
        File selectedFile = KeyStoreAdminFileSelector.selectFileForSave(this, title, new KeyStoreAdminFileFilter[]{filter}, defaultCertificateFilePath);
        if (selectedFile!=null)
            jTextFieldCertificateFile.setText(selectedFile.getAbsolutePath());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButtonCertificateFile;
    private javax.swing.JButton jButtonRequestFile;
    private javax.swing.JComboBox jComboBoxAlias;
    private javax.swing.JLabel jLabelAlias;
    private javax.swing.JLabel jLabelCertificateFile;
    private javax.swing.JLabel jLabelDurationDays;
    private javax.swing.JLabel jLabelRequestFile;
    private javax.swing.JSpinner jSpinnerDurationDays;
    private javax.swing.JTextField jTextFieldCertificateFile;
    private javax.swing.JTextField jTextFieldRequestFile;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}