/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * CsvRowConditionDialog.java
 *
 * Created on Feb 24, 2012, 12:51:37 PM
 */
package org.radixware.kernel.designer.ads.editors.clazz.report;

import org.openide.util.NbBundle;
import org.radixware.kernel.common.defs.ads.clazz.sql.report.AdsCsvReportInfo;
import org.radixware.kernel.designer.common.annotations.registrators.EditorFactoryRegistration;
import org.radixware.kernel.designer.common.editors.RadixObjectEditor;
import org.radixware.kernel.designer.common.editors.RadixObjectModalEditor;
import org.radixware.kernel.designer.common.editors.jml.JmlEditor;
import org.radixware.kernel.designer.common.general.editors.IEditorFactory;
import org.radixware.kernel.designer.common.general.editors.OpenInfo;


public class AdsCsvReportInfoEditor extends RadixObjectModalEditor<AdsCsvReportInfo> {    
    private final JmlEditor jmlEditor = new JmlEditor();
    /** Creates new form CsvRowConditionDialog */
    public AdsCsvReportInfoEditor(final AdsCsvReportInfo object) {
        super(object);
        initComponents();        
        this.add(jmlEditor);
    }
    
     @Override
    public boolean open(final OpenInfo openInfo) {
        jmlEditor.open(getRadixObject().getRowCondition(),openInfo);
        return super.open(openInfo);
    }
     
     @Override
    public boolean isCancelable() {
        return false;
    }
     
     @Override
    public String getTitle() {
        return NbBundle.getMessage(AdsReportCsvExportColumnsPanel.class, "AdsReportCsvExportColumnsPanel-RowCondition-Title");
    }
     
     @EditorFactoryRegistration
    public static final class Factory implements IEditorFactory<AdsCsvReportInfo> {

        @Override
        public RadixObjectEditor<AdsCsvReportInfo> newInstance(final AdsCsvReportInfo object) {
            return new AdsCsvReportInfoEditor(object);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    protected void apply() {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void update() {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    
}
