/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */
package org.radixware.kernel.designer.ads.editors.clazz.report;

import org.radixware.kernel.common.defs.ads.clazz.sql.report.AdsReportForm;
import org.radixware.kernel.designer.common.general.editors.EditorsManager;
import org.radixware.kernel.designer.common.dialogs.RadixWareDesignerIcon;

class BandsPanel extends javax.swing.JPanel {

    private final AdsReportForm form;
    private volatile boolean updating = false;
//    private final AdsReportBand pageHeaderBand;
//    private final AdsReportBand titleBand;
//    private final AdsReportBand columnHeaderBand;
//    private final AdsReportBand detailBand;
//    private final AdsReportBand summaryBand;
//    private final AdsReportBand pageFooterBand;

    /**
     * Creates new form BandsPanel
     */
    public BandsPanel(final AdsReportForm form) {
        this.form = form;
        initComponents();

        setupInitialValues();
    }

    private void setupInitialValues() {
        updating = true;
        edPageHeader.open(form);
        edTitle.open(form);
        edColumnsHeader.open(form);
        edDetails.open(form);
        edSummary.open(form);
        edPageFooter.open(form);
        updating = false;
    }

    private void updateEnableState() {
        edPageHeader.update();
        edTitle.update();
        edColumnsHeader.update();
        edDetails.update();
        edSummary.update();
        edPageFooter.update();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBandsCount = new javax.swing.JPanel();
        edPageHeader = new org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor();
        edTitle = new org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor();
        edColumnsHeader = new org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor();
        edDetails = new org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor();
        edSummary = new org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor();
        edPageFooter = new org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor();

        pBandsCount.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(BandsPanel.class, "BandsPanel.pBandsCount.border.title"))); // NOI18N

        edPageHeader.setBandType(org.radixware.kernel.common.enums.EReportBandType.PAGE_HEADER);

        edColumnsHeader.setBandType(org.radixware.kernel.common.enums.EReportBandType.COLUMN_HEADER);

        edDetails.setBandType(org.radixware.kernel.common.enums.EReportBandType.DETAIL);

        edSummary.setBandType(org.radixware.kernel.common.enums.EReportBandType.SUMMARY);

        edPageFooter.setBandType(org.radixware.kernel.common.enums.EReportBandType.PAGE_FOOTER);

        javax.swing.GroupLayout pBandsCountLayout = new javax.swing.GroupLayout(pBandsCount);
        pBandsCount.setLayout(pBandsCountLayout);
        pBandsCountLayout.setHorizontalGroup(
            pBandsCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBandsCountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBandsCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edPageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edColumnsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edPageFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 198, Short.MAX_VALUE))
        );
        pBandsCountLayout.setVerticalGroup(
            pBandsCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBandsCountLayout.createSequentialGroup()
                .addComponent(edPageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edColumnsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edPageFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBandsCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBandsCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void apply() {
        if (updating) {
            return;
        }
//        if (pageHeaderCheckBox.isSelected()) {
//            if (pageHeaderBand == null) {
//                form.setPageHeaderBandUsed(true);
//            } else {
//                form.setPageHeaderBand(pageHeaderBand);
//            }
//        } else {
//            form.setPageHeaderBandUsed(false);
//        }
//        if (titleCheckBox.isSelected()) {
//            if (titleBand == null) {
//                form.setTitleBandUsed(true);
//            } else {
//                form.setTitleBand(titleBand);
//            }
//        } else {
//            form.setTitleBandUsed(false);
//        }
//        if (columnHeaderCheckBox.isSelected()) {
//            if (columnHeaderBand == null) {
//                form.setColumnHeaderBandUsed(true);
//            } else {
//                form.setColumnHeaderBand(columnHeaderBand);
//            }
//        } else {
//            form.setColumnHeaderBandUsed(false);
//        }
//        if (detailsCheckBox.isSelected()) {
//            if (detailBand == null) {
//                form.setDetailBandUsed(true);
//            } else {
//                form.setDetailBand(detailBand);
//            }
//        } else {
//            form.setDetailBandUsed(false);
//        }
//        if (summaryCheckBox.isSelected()) {
//            if (summaryBand == null) {
//                form.setSummaryBandUsed(true);
//            } else {
//                form.setSummaryBand(summaryBand);
//            }
//        } else {
//            form.setSummaryBandUsed(false);
//        }
//        if (pageFooterCheckBox.isSelected()) {
//            if (pageFooterBand == null) {
//                form.setPageFooterBandUsed(true);
//            } else {
//                form.setPageFooterBand(pageFooterBand);
//            }
//        } else {
//            form.setPageFooterBandUsed(false);
//        }
//        form.setPageHeaderBandUsed(pageHeaderCheckBox.isSelected());
//        form.setTitleBandUsed(titleCheckBox.isSelected());
//        form.setColumnHeaderBandUsed(columnHeaderCheckBox.isSelected());
//        form.setDetailBandUsed(detailsCheckBox.isSelected());
//        form.setSummaryBandUsed(summaryCheckBox.isSelected());
//        form.setPageFooterBandUsed(pageFooterCheckBox.isSelected());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor edColumnsHeader;
    private org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor edDetails;
    private org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor edPageFooter;
    private org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor edPageHeader;
    private org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor edSummary;
    private org.radixware.kernel.designer.ads.editors.clazz.report.BandCountEditor edTitle;
    private javax.swing.JPanel pBandsCount;
    // End of variables declaration//GEN-END:variables
}
