/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * UdsUserFuncEditor.java
 *
 * Created on Jul 22, 2011, 4:16:42 PM
 */
package org.radixware.kernel.designer.uds.editors;

import java.awt.Color;
import org.radixware.kernel.common.defs.ads.clazz.AdsClassDef;
import org.radixware.kernel.common.defs.ads.clazz.members.AdsMethodDef;
import org.radixware.kernel.common.defs.uds.userfunc.UdsUserFuncDef;
import org.radixware.kernel.designer.common.annotations.registrators.EditorFactoryRegistration;
import org.radixware.kernel.designer.common.editors.RadixObjectEditor;
import org.radixware.kernel.designer.common.general.editors.IEditorFactory;
import org.radixware.kernel.designer.common.general.editors.IRadixObjectEditor;
import org.radixware.kernel.designer.common.general.editors.OpenInfo;


public class UdsUserFuncEditor extends RadixObjectEditor<UdsUserFuncDef> {

    @EditorFactoryRegistration
    public static final class Factory implements IEditorFactory<UdsUserFuncDef> {

        @Override
        public IRadixObjectEditor<UdsUserFuncDef> newInstance(UdsUserFuncDef method) {
            return new UdsUserFuncEditor(method);
        }
    }

    /** Creates new form UdsUserFuncEditor */
    public UdsUserFuncEditor(UdsUserFuncDef uf) {
        super(uf);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codeEditor = new org.radixware.kernel.designer.common.editors.jml.JmlEditor();
        edProperty = new org.radixware.kernel.designer.common.dialogs.components.DefinitionLinkEditPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edClass = new org.radixware.kernel.designer.common.dialogs.components.DefinitionLinkEditPanel();
        jLabel3 = new javax.swing.JLabel();
        edProfile = new javax.swing.JTextField();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(UdsUserFuncEditor.class, "UdsUserFuncEditor.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(UdsUserFuncEditor.class, "UdsUserFuncEditor.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(UdsUserFuncEditor.class, "UdsUserFuncEditor.jLabel3.text")); // NOI18N

        edProfile.setText(org.openide.util.NbBundle.getMessage(UdsUserFuncEditor.class, "UdsUserFuncEditor.edProfile.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeEditor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edProperty, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(edClass, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(edProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codeEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.radixware.kernel.designer.common.editors.jml.JmlEditor codeEditor;
    private org.radixware.kernel.designer.common.dialogs.components.DefinitionLinkEditPanel edClass;
    private javax.swing.JTextField edProfile;
    private org.radixware.kernel.designer.common.dialogs.components.DefinitionLinkEditPanel edProperty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        update((OpenInfo) null);
    }

    private UdsUserFuncDef getUserFunc() {
        return getRadixObject();
    }

    private void update(OpenInfo openInfo) {
        UdsUserFuncDef userFunc = getUserFunc();
        edProperty.open(userFunc.findOwnerProperty(), userFunc.getPropId());

        AdsClassDef clazz = userFunc.findBaseClass();
        edClass.open(clazz, userFunc.getBaseClassId());
        edProfile.setEditable(false);
        AdsMethodDef method = userFunc.findMethod();
        if (method != null) {
            edProfile.setText(method.getProfile().getName());
            edProfile.setForeground(Color.black);
        } else {
            edProfile.setText(userFunc.getMethodId().toString());
            edProfile.setForeground(Color.red);
        }

        codeEditor.open(userFunc.getSource(), openInfo);
        codeEditor.setEditable(
                !getUserFunc().isReadOnly());
    }

    @Override
    public boolean open(OpenInfo openInfo) {
        update(openInfo);
        return true;
    }
}
