/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * MergePanel.java
 *
 * Created on 6 Ноябрь 2008 г., 14:25
 */

package org.radixware.kernel.designer.ads.editors.clazz.forms.dialog;

import org.openide.util.NbBundle;
import java.awt.Component;
import java.lang.reflect.InvocationTargetException;
import javax.swing.AbstractCellEditor;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import org.openide.explorer.propertysheet.PropertyPanel;
import org.radixware.kernel.common.defs.ads.ui.AdsAbstractUIDef;
import org.radixware.kernel.common.defs.ads.ui.AdsItemWidgetDef;
import org.radixware.kernel.common.defs.ads.ui.AdsItemWidgetDef.Items;
import org.radixware.kernel.common.defs.ads.ui.AdsItemWidgetDef.WidgetItem;
import org.radixware.kernel.common.defs.ads.ui.AdsUIProperty;
import org.radixware.kernel.common.defs.ads.ui.AdsUIUtil;
import org.radixware.kernel.common.defs.ads.ui.UiProperties;
import org.radixware.kernel.common.resources.icons.RadixIcon;
import org.radixware.kernel.common.types.Id;
import org.radixware.kernel.designer.ads.editors.clazz.forms.palette.Item;
import org.radixware.kernel.designer.ads.editors.clazz.forms.props.UIPropertySupport;
import org.radixware.kernel.common.resources.RadixWareIcons;


public class ComboBoxPanel extends EditorDialog.EditorPanel<AdsItemWidgetDef> {

    /** Creates new form MergePanel */
    public ComboBoxPanel(AdsAbstractUIDef uiDef,AdsItemWidgetDef widget) {
        super(uiDef,widget);
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        scrollPane = new javax.swing.JScrollPane();
        propTable = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        scrollPane2 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        panel2 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonDel = new javax.swing.JButton();
        buttonUp = new javax.swing.JButton();
        buttonDown = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        splitPane.setDividerLocation(160);
        splitPane.setLastDividerLocation(160);

        propTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title"
            }
        ));
        propTable.setGridColor(new java.awt.Color(213, 213, 213));
        propTable.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        scrollPane.setViewportView(propTable);

        splitPane.setRightComponent(scrollPane);

        panel.setMinimumSize(new java.awt.Dimension(160, 10));
        panel.setPreferredSize(new java.awt.Dimension(160, 100));
        panel.setLayout(new java.awt.BorderLayout());

        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        scrollPane2.setViewportView(list);

        panel.add(scrollPane2, java.awt.BorderLayout.CENTER);

        buttonAdd.setIcon(RadixWareIcons.CREATE.ADD.getIcon());
        buttonAdd.setFocusPainted(false);
        buttonAdd.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        panel2.add(buttonAdd);

        buttonDel.setIcon(RadixWareIcons.DELETE.DELETE.getIcon());
        buttonDel.setFocusPainted(false);
        buttonDel.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelActionPerformed(evt);
            }
        });
        panel2.add(buttonDel);

        buttonUp.setIcon(RadixWareIcons.ARROW.MOVE_UP.getIcon());
        buttonUp.setFocusPainted(false);
        buttonUp.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpActionPerformed(evt);
            }
        });
        panel2.add(buttonUp);

        buttonDown.setIcon(RadixWareIcons.ARROW.MOVE_DOWN.getIcon());
        buttonDown.setFocusPainted(false);
        buttonDown.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonDown.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonDown.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDownActionPerformed(evt);
            }
        });
        panel2.add(buttonDown);

        panel.add(panel2, java.awt.BorderLayout.PAGE_END);

        splitPane.setLeftComponent(panel);

        add(splitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        int idx = list.getSelectedIndex();
        listModel.add(idx+1, new WidgetItem());
        list.setSelectedIndex(Math.max(idx+1, 0));
        update();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelActionPerformed
        // TODO add your handling code here:
        int idx = list.getSelectedIndex();
        listModel.del(idx);
        list.setSelectedIndex(Math.min(idx, listModel.getSize()-1));
        update();
    }//GEN-LAST:event_buttonDelActionPerformed

    private void buttonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpActionPerformed
        // TODO add your handling code here:
        int idx = list.getSelectedIndex();
        listModel.up(idx);
        list.setSelectedIndex(Math.max(Math.min(idx-1, listModel.getSize()-1), -1));
        update();
    }//GEN-LAST:event_buttonUpActionPerformed

    private void buttonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDownActionPerformed
        // TODO add your handling code here:
        int idx = list.getSelectedIndex();
        listModel.down(idx);
        list.setSelectedIndex(Math.max(Math.min(idx+1, listModel.getSize()-1), -1));
        update();
    }//GEN-LAST:event_buttonDownActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDel;
    private javax.swing.JButton buttonDown;
    private javax.swing.JButton buttonUp;
    private javax.swing.JList list;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel2;
    private javax.swing.JTable propTable;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

    private ListModel listModel;
    private TableModel tableModel;

    @Override
    public void init() {
        list.setModel(listModel = new ListModel());
        propTable.setModel(tableModel = new TableModel());

        list.getSelectionModel().addListSelectionListener(tableModel);
        list.setCellRenderer(new ListRenderer());

        list.setSelectedIndex(0);
        list.requestFocusInWindow();

        list.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting())
                    return;
                ListSelectionModel sm = (ListSelectionModel)e.getSource();
                cursorChanged(sm.isSelectionEmpty() ? -1 : list.getSelectedIndex());
            }
        });

        propTable.setModel(tableModel);
        propTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        propTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        propTable.setRowHeight(18);

        propTable.setDefaultRenderer(AdsUIProperty.class, new PropertyCellRenderer());
        propTable.setDefaultEditor(AdsUIProperty.class, new PropertyCellEditor());
        update();
    }

    private void cursorChanged(int idx) {
        update();
    }
    
    private void update() {
        int idx = list.getSelectedIndex();
        int size = listModel.getSize();
        buttonAdd.setEnabled(!widget.isReadOnly());
        buttonDel.setEnabled(!widget.isReadOnly() && idx >= 0);
        buttonUp.setEnabled(!widget.isReadOnly() && idx >= 1);
        buttonDown.setEnabled(!widget.isReadOnly() && idx >= 0 && idx < size - 1);
    }

    @Override
    public String getTitle() {
        return NbBundle.getMessage(getClass(), "CTL_ComboBoxPanel");
    }

    public class ListRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean hasFocus) {
            WidgetItem item = (WidgetItem)value;

            AdsUIProperty.LocalizedStringRefProperty text = (AdsUIProperty.LocalizedStringRefProperty)AdsUIUtil.getUiProperty(item, "text");
            AdsUIProperty.ImageProperty icon = (AdsUIProperty.ImageProperty)AdsUIUtil.getUiProperty(item, "icon");
            AdsUIProperty.BrushProperty background = (AdsUIProperty.BrushProperty)AdsUIUtil.getUiProperty(item, "background");
            AdsUIProperty.BrushProperty foreground = (AdsUIProperty.BrushProperty)AdsUIUtil.getUiProperty(item, "foreground");

            String s = Item.getTextById(item, text.getStringId());
            JLabel label = (JLabel)super.getListCellRendererComponent(list, s.isEmpty() ? " " : s, index, isSelected, hasFocus);
            RadixIcon radixIcon = Item.getIconById(item, icon.getImageId());
            if (radixIcon != null) {
                label.setIcon(radixIcon.getIcon());
            }

            if (!isSelected)
                label.setBackground(background.color);
            label.setForeground(foreground.color);

            return label;
        }       
    }

    // list model
    private class ListModel extends AbstractListModel {

        private final Items items = widget.getItems();

        ListModel() {
        }

        @Override
        public Object getElementAt(int i) {
            return items.get(i);
        }

        @Override
        public int getSize() {
            return items.size();
        }

        public Items getItems() {
            return items;
        }

        public void fireContentChanged(WidgetItem item) {
            super.fireContentsChanged(this,  items.indexOf(item), items.indexOf(item));
        }

        public void fireContentChanged(int idx) {
            super.fireContentsChanged(this, idx, idx);
        }

        void edited(WidgetItem item) {
            int idx = items.indexOf(item);
            if (idx >= 0 && idx < getSize())
                fireContentsChanged(this, idx, idx);
        }

        void add(int idx, WidgetItem item) {
            if (idx < 0 || idx > getSize())
                idx = 0;

            AdsUIProperty.LocalizedStringRefProperty text = new AdsUIProperty.LocalizedStringRefProperty("text");
            item.getProperties().add(text);

            items.add(idx, item);
            fireIntervalAdded(this, idx, idx);
        }

        void del(int idx) {
            if (idx >= 0 && idx < getSize()) {
                items.remove(idx);
                fireIntervalRemoved(this, idx, idx);
            }
        }

        void up(int idx) {
            if (idx > 0 && idx < getSize()) {
                items.moveUp(idx);
                fireContentsChanged(this, idx-1, idx);
            }
        }

        void down(int idx) {
            if (idx >= 0 && idx < getSize()-1) {
                items.moveDown(idx);
                fireContentsChanged(this, idx, idx+1);
            }
        }
    }

    // properties table model
    private class TableModel extends AbstractTableModel implements ListSelectionListener {

        private String[] columns = new String[] {
            NbBundle.getBundle(ComboBoxPanel.class).getString("PropTable.Name"),
            NbBundle.getBundle(ComboBoxPanel.class).getString("PropTable.Value")
        };

        private WidgetItem item = null;
        private AdsUIProperty[] rows = new AdsUIProperty[] {
            new AdsUIProperty.LocalizedStringRefProperty("text"),
            new AdsUIProperty.ImageProperty("icon", (Id)null)
        };

        public WidgetItem getItem() {
            return item;
        }

        @Override
        public int getColumnCount() {
            return columns.length;
        }

        @Override
        public int getRowCount() {
            return item == null || rows == null ? 0 : rows.length;
        }

        @Override
        public String getColumnName(int col) {
            return columns[col];
        }

        @Override
        public Object getValueAt(int row, int col) {
            return col > 0 ? rows[row] : rows[row].getName();
        }

        @Override
        public Class getColumnClass(int c) {
            return getValueAt(0, c).getClass();
        }

        @Override
        public boolean isCellEditable(int row, int col) {
            return col != 0 && !widget.isReadOnly();
        }

        @Override
        public void setValueAt(Object value, int row, int col) {
            rows[row] = (AdsUIProperty)value;
            fireTableCellUpdated(row, col);
        }

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (e.getValueIsAdjusting())
                return;
            int idx = list.getSelectedIndex();
            item = idx >=0 ? (WidgetItem)listModel.getElementAt(idx) : null;
            if (item != null) {
                rows = new AdsUIProperty[] {
                    new AdsUIProperty.LocalizedStringRefProperty("text"),
                    new AdsUIProperty.ImageProperty("icon", (Id)null)
                };
                UiProperties props = AdsUIUtil.getUiProperties(item);
                for (int i=0; i < rows.length; i++) {
                    AdsUIProperty p = props.getByName(rows[i].getName());
                    if (p != null)
                        rows[i] = p;
                }
            }
            fireTableStructureChanged();
        }
    }

    // property cell renderer
    private class PropertyCellEditor extends AbstractCellEditor implements TableCellEditor {

        private AdsUIProperty prop;

        public PropertyCellEditor() {
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int r, int c) {
            prop = (AdsUIProperty)value;
            final WidgetItem item = ((TableModel)table.getModel()).getItem();
            UIPropertySupport sup = new UIPropertySupport(prop, uiDef,item) {
                @Override
                public void setValue(Object val) throws IllegalAccessException, IllegalArgumentException, InvocationTargetException {
                    super.setValue(val);
                    listModel.fireContentChanged(item);
                }
            };
            return new PropertyPanel(sup, PropertyPanel.PREF_TABLEUI);
        }

        @Override
        public Object getCellEditorValue() {
            return prop;
        }
    }

    // property cell renderer
    private class PropertyCellRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            AdsUIProperty prop = (AdsUIProperty)value;
            WidgetItem item = ((TableModel)table.getModel()).getItem();
            UIPropertySupport sup = new UIPropertySupport(prop, uiDef,item);
            return new PropertyPanel(sup, PropertyPanel.PREF_TABLEUI);
        }
    }
}
