/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.reporteditor.tree;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.MessageFormat;
import javax.swing.JDialog;


public class ChooseImportActionDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChoseImportActionDialog
     */
    public static final int OPT_CREATE_REPORT=1;
    public static final int OPT_ADD_VERSIONS=2;
    public static final int OPT_CANCEL=0;
    private int option = OPT_CANCEL;

    public int getOption() {
        return option;
    }
    
    
    public ChooseImportActionDialog(final String currentReportName) {
        super();
        initComponents();
        label.setText(MessageFormat.format("Imported report is alredy exists ({0}).\n To continue with import select option you want",currentReportName));
        btAddReport.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(final ActionEvent e) {
                option = OPT_CREATE_REPORT;
                ChooseImportActionDialog.this.setVisible(false);
            }
        });
        btAddVersion.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(final ActionEvent e) {
                option = OPT_ADD_VERSIONS;
                ChooseImportActionDialog.this.setVisible(false);
            }
        });
        btCancel.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(final ActionEvent e) {
                option = OPT_CANCEL;
                ChooseImportActionDialog.this.setVisible(false);
            }
        });
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancel = new javax.swing.JButton();
        btAddVersion = new javax.swing.JButton();
        btAddReport = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(btCancel, org.openide.util.NbBundle.getMessage(ChooseImportActionDialog.class, "ChooseImportActionDialog.btCancel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btAddVersion, org.openide.util.NbBundle.getMessage(ChooseImportActionDialog.class, "ChooseImportActionDialog.btAddVersion.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btAddReport, org.openide.util.NbBundle.getMessage(ChooseImportActionDialog.class, "ChooseImportActionDialog.btAddReport.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(label, org.openide.util.NbBundle.getMessage(ChooseImportActionDialog.class, "ChooseImportActionDialog.label.text")); // NOI18N
        label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAddReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddVersion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancel))
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btAddVersion)
                    .addComponent(btAddReport))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddReport;
    private javax.swing.JButton btAddVersion;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
