/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.editors.clazz.sql;

import java.awt.BorderLayout;
import org.radixware.kernel.common.defs.ads.clazz.sql.AdsSqlClassDef;
import org.radixware.kernel.designer.common.annotations.registrators.EditorFactoryRegistration;
import org.radixware.kernel.designer.common.editors.RadixObjectEditor;
import org.radixware.kernel.designer.common.general.editors.IEditorFactory;
import org.radixware.kernel.designer.common.general.editors.IRadixObjectEditor;
import org.radixware.kernel.designer.common.general.editors.OpenInfo;


public class AdsSqlClassEditor extends RadixObjectEditor<AdsSqlClassDef> {

    private AdsSqlClassEditorPanel panel;

    @EditorFactoryRegistration
    public static final class Factory implements IEditorFactory<AdsSqlClassDef> {

        @Override
        public IRadixObjectEditor<AdsSqlClassDef> newInstance(AdsSqlClassDef sqlClass) {
            return new AdsSqlClassEditor(sqlClass);
        }
    }

    /** Creates new form AdsClassEditorView */
    public AdsSqlClassEditor(AdsSqlClassDef sqlClass) {
        super(sqlClass);
        initComponents();
        this.setLayout(new BorderLayout());
        this.panel = new AdsSqlClassEditorPanel();
        this.add(panel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(AdsSqlClassEditor.class, "AdsSqlClassEditor.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(670, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public AdsSqlClassDef getSqlClass() {
        return getRadixObject();
    }

    @Override
    public boolean open(OpenInfo info) {
        final AdsSqlClassDef sqlClass = getSqlClass();
        panel.open(sqlClass, info);
        return super.open(info);
    }

    @Override
    public void update() {
        panel.update();
    }

    @Override
    public void requestFocus() {
        panel.bodyPanel.codeEditor.getPane().requestFocusInWindow();
    }
}
