/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * ExtendableNameEditPanel.java
 *
 * Created on Jan 5, 2009, 12:51:45 PM
 */

package org.radixware.kernel.designer.common.dialogs.components;

import javax.swing.JPanel;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;


public abstract class ExtendableNameEditPanel extends javax.swing.JPanel {

    /** Creates new form ExtendableNameEditPanel */
    public ExtendableNameEditPanel() {
        initComponents();
    }
    private String nameStr;
    public void open(String name){
        if(name != null){
            nameEdit.setText(name);
        }
        this.nameStr = name;

        this.nameEdit.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                if(!nameEdit.getText().equals(nameStr)){
                    nameStr = nameEdit.getText();
                    nameChanged(nameStr);
                }
            }
        });
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameEdit = new javax.swing.JTextField();

        contentPanel.setLayout(new java.awt.BorderLayout());

        nameLabel.setText(org.openide.util.NbBundle.getMessage(ExtendableNameEditPanel.class, "ExtendableNameEditPanel.nameLabel.text")); // NOI18N

        nameEdit.setText(org.openide.util.NbBundle.getMessage(ExtendableNameEditPanel.class, "ExtendableNameEditPanel.nameEdit.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTextField nameEdit;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

    protected abstract void nameChanged(String newName);

    public JPanel getContentPanel(){
        return contentPanel;
    }

    public String getEditedName(){
        return nameStr;
    }
    public void setEditedName(String newName){
        if(!this.nameEdit.getText().equals(newName)){
            this.nameStr = newName;
            this.nameEdit.setText(newName);
            nameChanged(newName);
        }
    }
}
