/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.localization.prompt;

import java.util.List;
import javax.swing.table.AbstractTableModel;
import org.openide.util.NbBundle;
import org.radixware.kernel.common.enums.EIsoLanguage;
import org.radixware.kernel.designer.ads.localization.RowString;
import org.radixware.kernel.designer.common.dialogs.components.SimpleTable;


public class TimeAuthorInfoPanel extends javax.swing.JPanel {

    private final static String LABEL_TEXT=NbBundle.getMessage(TimeAuthorTableModel.class, "AUTHOR");
    /**
     * Creates new form TimeAuthorInfoPanel
     */
    public TimeAuthorInfoPanel() {
        initComponents();
    }
    
     public void setContext(final RowString rowString,final List<EIsoLanguage> langs) {
        if(rowString==null){
            return;
        }
        final TimeAuthorTableModel model=new TimeAuthorTableModel(rowString,langs);
        tableInfo.setModel(model);
        final String rowCreator = LABEL_TEXT + " " + (rowString.getAuthor() != null ? rowString.getAuthor() : "<unknown>") + ";";
        final String rowCreationTime = "Creation date " + (rowString.getCreationDateStr() != null ? rowString.getCreationDateStr() : "<unknown>");
        final String sCreationInfo=rowCreator+" "+rowCreationTime;
        lbAuthor.setText(sCreationInfo);
    }

    public void update(){
        ((AbstractTableModel)tableInfo.getModel()).fireTableDataChanged();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableInfo = new SimpleTable();
        jPanel1 = new javax.swing.JPanel();
        lbAuthor = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableInfo);

        add(jScrollPane1);

        lbAuthor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.openide.awt.Mnemonics.setLocalizedText(lbAuthor, org.openide.util.NbBundle.getMessage(TimeAuthorInfoPanel.class, "TimeAuthorInfoPanel.lbAuthor.text")); // NOI18N
        lbAuthor.setAlignmentY(0.0F);
        lbAuthor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbAuthor)
                .addGap(0, 369, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbAuthor))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAuthor;
    private javax.swing.JTable tableInfo;
    // End of variables declaration//GEN-END:variables
}
