/*
 * Copyright (c) 2008-2016, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */
 
package org.radixware.kernel.utils.wia.properties;

public enum EComPropSpecId {

	UNKNOWN(0,"Unknown Property"),
    WIA_DIP_DEV_ID(2, "Unique Device ID"),
    WIA_DIP_VEND_DESC(3, "Manufacturer"),
    WIA_DIP_DEV_DESC(4, "Description"),
    WIA_DIP_DEV_TYPE(5, "Type"),
    WIA_DIP_PORT_NAME(6, "Port"),
    WIA_DIP_DEV_NAME(7, "Name"),
    WIA_DIP_SERVER_NAME(8, "Server"),
    WIA_DIP_REMOTE_DEV_ID(9, "Remote Device ID"),
    WIA_DIP_UI_CLSID(10, "UI Class ID"),
    WIA_DIP_HW_CONFIG(11, "Hardware Configuration"),
    WIA_DIP_BAUDRATE(12, "BaudRate"),
    WIA_DIP_STI_GEN_CAPABILITIES(13, "STI Generic Capabilities"),
    WIA_DIP_WIA_VERSION(14, "WIA Version"),
    WIA_DIP_DRIVER_VERSION(15, "Driver Version"),
    WIA_DIP_PNP_ID(16, "PnP ID String"),
    WIA_DIP_STI_DRIVER_VERSION(17, "STI Driver Version"),
    WIA_DPA_FIRMWARE_VERSION(1026, "Firmware Version"),
    WIA_DPA_CONNECT_STATUS(1027, "Connect Status"),
    WIA_DPA_DEVICE_TIME(1028, "Device Time"),
    WIA_DPC_PICTURES_TAKEN(2050, "Pictures Taken"),
    WIA_DPC_PICTURES_REMAINING(2051, "Pictures Remaining"),
    WIA_DPC_EXPOSURE_MODE(2052, "Exposure Mode"),
    WIA_DPC_EXPOSURE_COMP(2053, "Exposure Compensation"),
    WIA_DPC_EXPOSURE_TIME(2054, "Exposure Time"),
    WIA_DPC_FNUMBER(2055, "F Number"),
    WIA_DPC_FLASH_MODE(2056, "Flash Mode"),
    WIA_DPC_FOCUS_MODE(2057, "Focus Mode"),
    WIA_DPC_FOCUS_MANUAL_DIST(2058, "Focus Manual Dist"),
    WIA_DPC_ZOOM_POSITION(2059, "Zoom Position"),
    WIA_DPC_PAN_POSITION(2060, "Pan Position"),
    WIA_DPC_TILT_POSITION(2061, "Tilt Position"),
    WIA_DPC_TIMER_MODE(2062, "Timer Mode"),
    WIA_DPC_TIMER_VALUE(2063, "Timer Value"),
    WIA_DPC_POWER_MODE(2064, "Power Mode"),
    WIA_DPC_BATTERY_STATUS(2065, "Battery Status"),
    WIA_DPC_THUMB_WIDTH(2066, "Thumbnail Width"),
    WIA_DPC_THUMB_HEIGHT(2067, "Thumbnail Height"),
    WIA_DPC_PICT_WIDTH(2068, "Picture Width"),
    WIA_DPC_PICT_HEIGHT(2069, "Picture Height"),
    WIA_DPC_DIMENSION(2070, "Dimension"),
    WIA_DPC_COMPRESSION_SETTING(2071, "Compression Setting"),
    WIA_DPC_FOCUS_METERING(2072, "Focus Metering Mode"),
    WIA_DPC_TIMELAPSE_INTERVAL(2073, "Timelapse Interval"),
    WIA_DPC_TIMELAPSE_NUMBER(2074, "Timelapse Number"),
    WIA_DPC_BURST_INTERVAL(2075, "Burst Interval"),
    WIA_DPC_BURST_NUMBER(2076, "Burst Number"),
    WIA_DPC_EFFECT_MODE(2077, "Effect Mode"),
    WIA_DPC_DIGITAL_ZOOM(2078, "Digital Zoom"),
    WIA_DPC_SHARPNESS(2079, "Sharpness"),
    WIA_DPC_CONTRAST(2080, "Contrast"),
    WIA_DPC_CAPTURE_MODE(2081, "Capture Mode"),
    WIA_DPC_CAPTURE_DELAY(2082, "Capture Delay"),
    WIA_DPC_EXPOSURE_INDEX(2083, "Exposure Index"),
    WIA_DPC_EXPOSURE_METERING_MODE(2084, "Exposure Metering Mode"),
    WIA_DPC_FOCUS_METERING_MODE(2085, "Focus Metering Mode"),
    WIA_DPC_FOCUS_DISTANCE(2086, "Focus Distance"),
    WIA_DPC_FOCAL_LENGTH(2087, "Focus Length"),
    WIA_DPC_RGB_GAIN(2088, "RGB Gain"),
    WIA_DPC_WHITE_BALANCE(2089, "White Balance"),
    WIA_DPC_UPLOAD_URL(2090, "Upload URL"),
    WIA_DPC_ARTIST(2091, "Artist"),
    WIA_DPC_COPYRIGHT_INFO(2092, "Copyright Info"),
    WIA_DPS_HORIZONTAL_BED_SIZE(3074, "Horizontal Bed Size"),
    WIA_DPS_VERTICAL_BED_SIZE(3075, "Vertical Bed Size"),
    WIA_DPS_HORIZONTAL_SHEET_FEED_SIZE(3076, "Horizontal Sheet Feed Size"),
    WIA_DPS_VERTICAL_SHEET_FEED_SIZE(3077, "Vertical Sheet Feed Size"),
    WIA_DPS_SHEET_FEEDER_REGISTRATION(3078, "Sheet Feeder Registration"),
    WIA_DPS_HORIZONTAL_BED_REGISTRATION(3079, "Horizontal Bed Registration"),
    WIA_DPS_VERTICAL_BED_REGISTRATION(3080, "Vertical Bed Registration"),
    WIA_DPS_PLATEN_COLOR(3081, "Platen Color"),
    WIA_DPS_PAD_COLOR(3082, "Pad Color"),
    WIA_DPS_FILTER_SELECT(3083, "Filter Select"),
    WIA_DPS_DITHER_SELECT(3084, "Dither Select"),
    WIA_DPS_DITHER_PATTERN_DATA(3085, "Dither Pattern Data"),
    WIA_DPS_DOCUMENT_HANDLING_CAPABILITIES(3086, "Document Handling Capabilities"),
    WIA_DPS_DOCUMENT_HANDLING_STATUS(3087, "Document Handling Status"),
    WIA_DPS_DOCUMENT_HANDLING_SELECT(3088, "Document Handling Select"),
    WIA_DPS_DOCUMENT_HANDLING_CAPACITY(3089, "Document Handling Capacity"),
    WIA_DPS_OPTICAL_XRES(3090, "Horizontal Optical Resolution"),
    WIA_DPS_OPTICAL_YRES(3091, "Vertical Optical Resolution"),
    WIA_DPS_ENDORSER_CHARACTERS(3092, "Endorser Characters"),
    WIA_DPS_ENDORSER_STRING(3093, "Endorser String"),
    WIA_DPS_SCAN_AHEAD_PAGES(3094, "Scan Ahead Pages"),
    WIA_DPS_MAX_SCAN_TIME(3095, "Max Scan Time"),
    WIA_DPS_PAGES(3096, "Pages"),
    WIA_DPS_PAGE_SIZE(3097, "Page Size"),
    WIA_DPS_PAGE_WIDTH(3098, "Page Width"),
    WIA_DPS_PAGE_HEIGHT(3099, "Page Height"),
    WIA_DPS_PREVIEW(3100, "Preview"),
    WIA_DPS_TRANSPARENCY(3101, "Transparency Adapter"),
    WIA_DPS_TRANSPARENCY_SELECT(3102, "Transparency Adapter Select"),
    WIA_DPS_SHOW_PREVIEW_CONTROL(3103, "Show preview control"),
    WIA_DPS_MIN_HORIZONTAL_SHEET_FEED_SIZE(3104, "Minimum Horizontal Sheet Feed Size"),
    WIA_DPS_MIN_VERTICAL_SHEET_FEED_SIZE(3105, "Minimum Vertical Sheet Feed Size"),
    WIA_DPS_TRANSPARENCY_CAPABILITIES(3106, "Transparency Adapter Capabilities"),
    WIA_DPS_TRANSPARENCY_STATUS(3107, "Transparency Adapter Status"),
    WIA_DPF_MOUNT_POINT(3330, "Directory mount point"),
    WIA_DPV_LAST_PICTURE_TAKEN(3586, "Last Picture Taken"),
    WIA_DPV_IMAGES_DIRECTORY(3587, "Images Directory"),
    WIA_DPV_DSHOW_DEVICE_PATH(3588, "Directshow Device Path"),
    WIA_IPA_ITEM_NAME(4098, "Item Name"),
    WIA_IPA_FULL_ITEM_NAME(4099, "Full Item Name"),
    WIA_IPA_ITEM_TIME(4100, "Item Time Stamp"),
    WIA_IPA_ITEM_FLAGS(4101, "Item Flags"),
    WIA_IPA_ACCESS_RIGHTS(4102, "Access Rights"),
    WIA_IPA_DATATYPE(4103, "Data Type"),
    WIA_IPA_DEPTH(4104, "Bits Per Pixel"),
    WIA_IPA_PREFERRED_FORMAT(4105, "Preferred Format"),
    WIA_IPA_FORMAT(4106, "Format"),
    WIA_IPA_COMPRESSION(4107, "Compression"),
    WIA_IPA_TYMED(4108, "Media Type"),
    WIA_IPA_CHANNELS_PER_PIXEL(4109, "Channels Per Pixel"),
    WIA_IPA_BITS_PER_CHANNEL(4110, "Bits Per Channel"),
    WIA_IPA_PLANAR(4111, "Planar"),
    WIA_IPA_PIXELS_PER_LINE(4112, "Pixels Per Line"),
    WIA_IPA_BYTES_PER_LINE(4113, "Bytes Per Line"),
    WIA_IPA_NUMBER_OF_LINES(4114, "Number of Lines"),
    WIA_IPA_GAMMA_CURVES(4115, "Gamma Curves"),
    WIA_IPA_ITEM_SIZE(4116, "Item Size"),
    WIA_IPA_COLOR_PROFILE(4117, "Color Profiles"),
    WIA_IPA_MIN_BUFFER_SIZE(4118, "Buffer Size"),
    WIA_IPA_BUFFER_SIZE(4118, "Buffer Size"),
    WIA_IPA_REGION_TYPE(4119, "Region Type"),
    WIA_IPA_ICM_PROFILE_NAME(4120, "Color Profile Name"),
    WIA_IPA_APP_COLOR_MAPPING(4121, "Application Applies Color Mapping"),
    WIA_IPA_PROP_STREAM_COMPAT_ID(4122, "Stream Compatibility ID"),
    WIA_IPA_FILENAME_EXTENSION(4123, "Filename extension"),
    WIA_IPA_SUPPRESS_PROPERTY_PAGE(4124, "Suppress a property page"),
    WIA_IPC_THUMBNAIL(5122, "Thumbnail Data"),
    WIA_IPC_THUMB_WIDTH(5123, "Thumbnail Width"),
    WIA_IPC_THUMB_HEIGHT(5124, "Thumbnail Height"),
    WIA_IPC_AUDIO_AVAILABLE(5125, "Audio Available"),
    WIA_IPC_AUDIO_DATA_FORMAT(5126, "Audio Format"),
    WIA_IPC_AUDIO_DATA(5127, "Audio Data"),
    WIA_IPC_NUM_PICT_PER_ROW(5128, "Pictures per Row"),
    WIA_IPC_SEQUENCE(5129, "Sequence Number"),
    WIA_IPC_TIMEDELAY(5130, "Time Delay"),
    WIA_IPS_CUR_INTENT(6146, "Current Intent"),
    WIA_IPS_XRES(6147, "Horizontal Resolution"),
    WIA_IPS_YRES(6148, "Vertical Resolution"),
    WIA_IPS_XPOS(6149, "Horizontal Start Position"),
    WIA_IPS_YPOS(6150, "Vertical Start Position"),
    WIA_IPS_XEXTENT(6151, "Horizontal Extent"),
    WIA_IPS_YEXTENT(6152, "Vertical Extent"),
    WIA_IPS_PHOTOMETRIC_INTERP(6153, "Photometric Interpretation"),
    WIA_IPS_BRIGHTNESS(6154, "Brightness"),
    WIA_IPS_CONTRAST(6155, "Contrast"),
    WIA_IPS_ORIENTATION(6156, "Orientation"),
    WIA_IPS_ROTATION(6157, "Rotation"),
    WIA_IPS_MIRROR(6158, "Mirror"),
    WIA_IPS_THRESHOLD(6159, "Threshold"),
    WIA_IPS_INVERT(6160, "Invert"),
    WIA_IPS_WARM_UP_TIME(6161, "Lamp Warm up Time"),
    WIA_DPS_USER_NAME(3112, "User Name"),
    WIA_DPS_SERVICE_ID(3113, "Service ID"),
    WIA_DPS_DEVICE_ID(3114, "Device ID"),
    WIA_DPS_GLOBAL_IDENTITY(3115, "Global Identity"),
    WIA_IPS_DESKEW_X(6162, "DeskewX"),
    WIA_IPS_DESKEW_Y(6163, "DeskewY"),
    WIA_IPS_SEGMENTATION(6164, "Segmentation"),
    WIA_IPS_MAX_HORIZONTAL_SIZE(6165, "Maximum Horizontal Scan Size"),
    WIA_IPS_MAX_VERTICAL_SIZE(6166, "Maximum Vertical Scan Size"),
    WIA_IPS_MIN_HORIZONTAL_SIZE(6167, "Minimum Horizontal Scan Size"),
    WIA_IPS_MIN_VERTICAL_SIZE(6168, "Minimum Vertical Scan Size"),
    WIA_IPS_TRANSFER_CAPABILITIES(6169, "Transfer Capabilities"),
    WIA_IPS_SHEET_FEEDER_REGISTRATION(3078, "Sheet Feeder Registration"),
    WIA_IPS_DOCUMENT_HANDLING_SELECT(3088, "Document Handling Select"),
    WIA_IPS_OPTICAL_XRES(3090, "Horizontal Optical Resolution"),
    WIA_IPS_OPTICAL_YRES(3091, "Vertical Optical Resolution"),
    WIA_IPS_PAGES(3096, "Pages"),
    WIA_IPS_PAGE_SIZE(3097, "Page Size"),
    WIA_IPS_PAGE_WIDTH(3098, "Page Width"),
    WIA_IPS_PAGE_HEIGHT(3099, "Page Height"),
    WIA_IPS_PREVIEW(3100, "Preview"),
    WIA_IPS_SHOW_PREVIEW_CONTROL(3103, "Show preview control"),
    WIA_IPS_FILM_SCAN_MODE(3104, "Film Scan Mode"),
    WIA_IPS_LAMP(3105, "Lamp"),
    WIA_IPS_LAMP_AUTO_OFF(3106, "Lamp Auto Off"),
    WIA_IPS_AUTO_DESKEW(3107, "Automatic Deskew"),
    WIA_IPS_SUPPORTS_CHILD_ITEM_CREATION(3108, "Supports Child Item Creation"),
    WIA_IPS_XSCALING(3109, "Horizontal Scaling"),
    WIA_IPS_YSCALING(3110, "Vertical Scaling"),
    WIA_IPS_PREVIEW_TYPE(3111, "Preview Type"),
    WIA_IPA_ITEM_CATEGORY(4125, "Item Category"),
    WIA_IPA_UPLOAD_ITEM_SIZE(4126, "Upload Item Size"),
    WIA_IPA_ITEMS_STORED(4127, "Items Stored"),
    WIA_IPA_RAW_BITS_PER_CHANNEL(4128, "Raw Bits Per Channel"),
    WIA_IPS_FILM_NODE_NAME(4129, "Film Node Name");
	
    private final long value;
	private final String description;

    private EComPropSpecId(final long val, final String desc) {
        value = val;
		description = desc;
    }

    public long getValue() {
        return value;
    }
	
	public String getDescription(){
	    return description;
	}
    
    public static EComPropSpecId fromLong(final long value) {
        for (EComPropSpecId val : EComPropSpecId.values()) {
            if (val.getValue() == value) {
                return val;
            }
        }		
        return UNKNOWN;
    }
}
