drop trigger atuX5TD7JDVVHWDBROXAAIT4AGD7E
/

drop trigger atu52CHFNO3EGWDBRCRAAIT4AGD7E
/

drop trigger atiX5TD7JDVVHWDBROXAAIT4AGD7E
/

drop trigger ati52CHFNO3EGWDBRCRAAIT4AGD7E
/

-- In case ORA-00054 you should stop perso comm. units
create index IDX_RDX_PC_OUTMESSAGE_CREATETI on RDX_PC_OUTMESSAGE (CREATETIME asc)
/


begin
    execute immediate 'ALTER PACKAGE RDX_AUDIT COMPILE BODY';
end;
/

create or replace trigger ati52CHFNO3EGWDBRCRAAIT4AGD7E
after insert on RDX_INSTANCE
for each row
disable
declare vStoreDuration integer; vSaveData integer; vPID varchar2(4000); vChangeData clob; vSchemeId varchar2(50); vClassGuid varchar2(50);
begin
   begin
      select DEFAULTAUDITSCHEMEID into vSchemeId from RDX_SYSTEM where ID=1;
      select RDX_AU_SCHEMEITEM.STOREDURATION, RDX_AU_SCHEMEITEM.SAVEDATA into vStoreDuration, vSaveData
      from RDX_AU_SCHEMEITEM
      where RDX_AU_SCHEMEITEM.SCHEMEGUID = vSchemeId
         and RDX_AU_SCHEMEITEM.TABLEID = 'tbl52CHFNO3EGWDBRCRAAIT4AGD7E'
         and RDX_AU_SCHEMEITEM.EVENTTYPE = 'I';
   exception
      when no_data_found then return;
   end;
   vPID:=:new.ID;
   if vSaveData=1 then
            RDX_AUDIT.addValueStr(vChangeData,'new.colUJAMRNBTMVE2BHL3BKCXMXSNMI',:new.DBTRACEPROFILE);
            RDX_AUDIT.addValueStr(vChangeData,'new.col24KG33MBMRAATA7S5VFV34PLTE',:new.GUITRACEPROFILE);
            RDX_AUDIT.addValueStr(vChangeData,'new.colF666DZAJ3NF3BOLDRS6BDK75T4',:new.FILETRACEPROFILE);
            RDX_AUDIT.addValueStr(vChangeData,'new.colXGRPSYS6JVGHRMXMH2FEUSJMQU',:new.TRACEFILESDIR);
            RDX_AUDIT.addValueInt(vChangeData,'new.colKTN2GUM43VD5TH34XEED3NBSWM',:new.MAXTRACEFILESIZEKB);
            RDX_AUDIT.addValueInt(vChangeData,'new.colGPBWOB42OZCATJ6INHY24PAYLI',:new.MAXTRACEFILECNT);
            RDX_AUDIT.addValueStr(vChangeData,'new.colO6KNHKT4RHWDBRCXAAIT4AGD7E',:new.STARTOSCOMMAND);
            RDX_AUDIT.addValueStr(vChangeData,'new.colROO4LOT4RHWDBRCXAAIT4AGD7E',:new.STOPOSCOMMAND);
            RDX_AUDIT.addValueStr(vChangeData,'new.colYSPDMMOVEBGPZIMQX2RBMXCBQE',:new.SCPNAME);
            RDX_AUDIT.addValueInt(vChangeData,'new.col3YSQY2R375FKFKYACAY762WGD4',:new.KEYSTORETYPE);
            RDX_AUDIT.addValueStr(vChangeData,'new.colDAQ557DC6BAZRI6VNI3WDLB5HQ',:new.KEYSTOREPATH);
            RDX_AUDIT.addValueStr(vChangeData,'new.colTLHWR7V5OJE53K6G4EJDPJY2XY',:new.KEYTABPATH);
            RDX_AUDIT.addValueInt(vChangeData,'new.col4Z2JD6POZNCZJLGNTEGIJHZEQQ',:new.LOWARTEINSTCOUNT);
            RDX_AUDIT.addValueInt(vChangeData,'new.col27DHEMV4S5FAVBSPLT6B6R4E6M',:new.HIGHARTEINSTCOUNT);
            RDX_AUDIT.addValueInt(vChangeData,'new.colPVFIBHTN5NA35FF6RJCZIM6SAY',:new.ARTEINSTLIVETIME);
   end if;

   vClassGuid := 'aec52CHFNO3EGWDBRCRAAIT4AGD7E';
   insert into RDX_AU_AUDITLOG (ID,EVENTTIME,STOREDURATION,USERNAME,STATIONNAME,TABLEID,CLASSID,PID,EVENTTYPE,EVENTDATA)
   values(SQN_RDX_AU_AUDITLOGID.NextVal,SYSTIMESTAMP,vStoreDuration,RDX_Arte.getUserName,RDX_Arte.getStationName,'tbl52CHFNO3EGWDBRCRAAIT4AGD7E',vClassGuid,vPID,'I',vChangeData);
end;
/

begin
   RDX_AUDIT.updateTableAuditStateEventType('tbl52CHFNO3EGWDBRCRAAIT4AGD7E', 'I','tbl52CHFNO3EGWDBRCRAAIT4AGD7E');
end;
/

create or replace trigger atiX5TD7JDVVHWDBROXAAIT4AGD7E
after insert on RDX_SYSTEM
for each row
disable
declare vStoreDuration integer; vSaveData integer; vPID varchar2(4000); vChangeData clob; vSchemeId varchar2(50); vClassGuid varchar2(50);
begin
   begin
      select RDX_AU_SCHEMEITEM.STOREDURATION, RDX_AU_SCHEMEITEM.SAVEDATA into vStoreDuration, vSaveData
      from RDX_AU_SCHEMEITEM
      where RDX_AU_SCHEMEITEM.SCHEMEGUID=RDX_AUDIT.DEFAULTAUDITSCHEME
         and RDX_AU_SCHEMEITEM.TABLEID = 'tblX5TD7JDVVHWDBROXAAIT4AGD7E'
         and RDX_AU_SCHEMEITEM.EVENTTYPE = 'I';
   exception
      when no_data_found then return;
   end;
   vPID:=:new.ID;
   if vSaveData=1 then
            RDX_AUDIT.addValueStr(vChangeData,'new.colTCOQ4HOZRHWDBRCXAAIT4AGD7E',:new.NAME);
            RDX_AUDIT.addValueStr(vChangeData,'new.col546FXWYZJ3NRDJIRACQMTAIZT4',:new.ARTELANGUAGE);
            RDX_AUDIT.addValueStr(vChangeData,'new.colWGL2VHS7RNBIRA3NYYV3KGAIPI',:new.ARTECOUNTRY);
            RDX_AUDIT.addValueStr(vChangeData,'new.colMJDA72X3RRHX5AQ4RSCK3YNA44',:new.ARTEGUITRACEPROFILE);
            RDX_AUDIT.addValueStr(vChangeData,'new.colMYF3QYYJ7BFS7AJ6YRMZUFBE4M',:new.ARTEFILETRACEPROFILE);
            RDX_AUDIT.addValueStr(vChangeData,'new.colXLSJR3OUKLNRDAQSABIFNQAAAE',:new.ARTEDBTRACEPROFILE);
            RDX_AUDIT.addValueInt(vChangeData,'new.colM6ABGYQYNVGYRC6NTJ76DIBZ4I',:new.EASSESSIONACTIVITYMINS);
            RDX_AUDIT.addValueInt(vChangeData,'new.colLPOXOGA2J3NRDJIRACQMTAIZT4',:new.EASSESSIONINACTIVITYMINS);
            RDX_AUDIT.addValueStr(vChangeData,'new.colM6KLR5HJ3JDI7DTS5S52SRQEFU',:new.EASKRBPRINCNAME);
            RDX_AUDIT.addValueInt(vChangeData,'new.colRJ6YTFHGWPNBDPLGABQJO5ADDQ',:new.AUDITSTOREPERIOD1);
            RDX_AUDIT.addValueInt(vChangeData,'new.col3J6FBUPGWPNBDPLGABQJO5ADDQ',:new.AUDITSTOREPERIOD2);
            RDX_AUDIT.addValueInt(vChangeData,'new.col3N6FBUPGWPNBDPLGABQJO5ADDQ',:new.AUDITSTOREPERIOD3);
            RDX_AUDIT.addValueInt(vChangeData,'new.colTJMVJWXGWPNBDPLGABQJO5ADDQ',:new.AUDITSTOREPERIOD4);
            RDX_AUDIT.addValueInt(vChangeData,'new.colTNMVJWXGWPNBDPLGABQJO5ADDQ',:new.AUDITSTOREPERIOD5);
            RDX_AUDIT.addValueStr(vChangeData,'new.colEKZMW4XGWPNBDPLGABQJO5ADDQ',:new.DEFAULTAUDITSCHEMEID);
            RDX_AUDIT.addValueInt(vChangeData,'new.colDCLAU6NMGVDSNKN7ZPB6SQJE5Y',:new.BLOCKUSERINVALIDLOGONCNT);
            RDX_AUDIT.addValueInt(vChangeData,'new.colQTEXFSBLXJES3AOB6SXXKNGQQE',:new.BLOCKUSERINVALIDLOGONMINS);
            RDX_AUDIT.addValueInt(vChangeData,'new.colLRLGIOF3DVB2XEFQXLCJLPUYTU',:new.ENABLESENSITIVETRACE);
            RDX_AUDIT.addValueInt(vChangeData,'new.colKDV6X7RAL5DCBO2HENGADFNFTY',:new.PROFILELOGSTOREDAYS);
   end if;

   vClassGuid := 'aecX5TD7JDVVHWDBROXAAIT4AGD7E';
   insert into RDX_AU_AUDITLOG (ID,EVENTTIME,STOREDURATION,USERNAME,STATIONNAME,TABLEID,CLASSID,PID,EVENTTYPE,EVENTDATA)
   values(SQN_RDX_AU_AUDITLOGID.NextVal,SYSTIMESTAMP,vStoreDuration,RDX_Arte.getUserName,RDX_Arte.getStationName,'tblX5TD7JDVVHWDBROXAAIT4AGD7E',vClassGuid,vPID,'I',vChangeData);
end;
/

begin
   RDX_AUDIT.updateTableAuditStateEventType('tblX5TD7JDVVHWDBROXAAIT4AGD7E', 'I','tblX5TD7JDVVHWDBROXAAIT4AGD7E');
end;
/

create or replace trigger atu52CHFNO3EGWDBRCRAAIT4AGD7E
after update of AADCDGADDRESS, AADCMEMBERID, ARTEINSTLIVETIME, AUTOACTUALIZEVER, AUTORESTARTDELAYSEC, CLASSLOADINGPROFILEID, DBTRACEPROFILE, FILETRACEPROFILE, GUITRACEPROFILE, HIGHARTEINSTCOUNT, HTTPPROXY, HTTPSPROXY, KEYSTOREPATH, KEYSTORETYPE, KEYTABPATH, LOWARTEINSTCOUNT, MAXACTIVEARTEABOVENORMAL, MAXACTIVEARTECRITICAL, MAXACTIVEARTEHIGH, MAXACTIVEARTENORMAL, MAXACTIVEARTEVERYHIGH, MAXTRACEFILECNT, MAXTRACEFILESIZEKB, MEMORYCHECKPERIODSEC, ORAIMPLSTMTCACHESIZE, ROTATETRACEFILESDAILY, SCPNAME, STARTOSCOMMAND, STOPOSCOMMAND, TRACEFILESDIR, USEACTIVEARTELIMITS, USEORAIMPLSTMTCACHE on RDX_INSTANCE
for each row
disable
declare vStoreDuration integer; vSaveData integer; vPID varchar2(4000); vChangeData clob; vSchemeId varchar2(50); vClassGuid varchar2(50);
begin
   begin
      select DEFAULTAUDITSCHEMEID into vSchemeId from RDX_SYSTEM where ID=1;
      select RDX_AU_SCHEMEITEM.STOREDURATION, RDX_AU_SCHEMEITEM.SAVEDATA into vStoreDuration, vSaveData
      from RDX_AU_SCHEMEITEM
      where RDX_AU_SCHEMEITEM.SCHEMEGUID = vSchemeId
         and RDX_AU_SCHEMEITEM.TABLEID = 'tbl52CHFNO3EGWDBRCRAAIT4AGD7E'
         and RDX_AU_SCHEMEITEM.EVENTTYPE = 'U';
   exception
      when no_data_found then return;
   end;
   vPID:=:old.ID;
   if vSaveData=1 then
            RDX_AUDIT.addChangedValueStr(vChangeData,'colUJAMRNBTMVE2BHL3BKCXMXSNMI',:old.DBTRACEPROFILE,:new.DBTRACEPROFILE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'col24KG33MBMRAATA7S5VFV34PLTE',:old.GUITRACEPROFILE,:new.GUITRACEPROFILE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colF666DZAJ3NF3BOLDRS6BDK75T4',:old.FILETRACEPROFILE,:new.FILETRACEPROFILE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colXGRPSYS6JVGHRMXMH2FEUSJMQU',:old.TRACEFILESDIR,:new.TRACEFILESDIR);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colKTN2GUM43VD5TH34XEED3NBSWM',:old.MAXTRACEFILESIZEKB,:new.MAXTRACEFILESIZEKB);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colGPBWOB42OZCATJ6INHY24PAYLI',:old.MAXTRACEFILECNT,:new.MAXTRACEFILECNT);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colCHSEV5KJGVACBL2YSMNARJCWKI',:old.ROTATETRACEFILESDAILY,:new.ROTATETRACEFILESDAILY);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colO6KNHKT4RHWDBRCXAAIT4AGD7E',:old.STARTOSCOMMAND,:new.STARTOSCOMMAND);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colROO4LOT4RHWDBRCXAAIT4AGD7E',:old.STOPOSCOMMAND,:new.STOPOSCOMMAND);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colYSPDMMOVEBGPZIMQX2RBMXCBQE',:old.SCPNAME,:new.SCPNAME);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col3YSQY2R375FKFKYACAY762WGD4',:old.KEYSTORETYPE,:new.KEYSTORETYPE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colDAQ557DC6BAZRI6VNI3WDLB5HQ',:old.KEYSTOREPATH,:new.KEYSTOREPATH);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colTLHWR7V5OJE53K6G4EJDPJY2XY',:old.KEYTABPATH,:new.KEYTABPATH);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colZDM5FZM6CNAAVLLCHIQB4F6WL4',:old.AUTOACTUALIZEVER,:new.AUTOACTUALIZEVER);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colETPNDLR7SVE4JEEF664PVZPKN4',:old.MEMORYCHECKPERIODSEC,:new.MEMORYCHECKPERIODSEC);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col4Z2JD6POZNCZJLGNTEGIJHZEQQ',:old.LOWARTEINSTCOUNT,:new.LOWARTEINSTCOUNT);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col27DHEMV4S5FAVBSPLT6B6R4E6M',:old.HIGHARTEINSTCOUNT,:new.HIGHARTEINSTCOUNT);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colPVFIBHTN5NA35FF6RJCZIM6SAY',:old.ARTEINSTLIVETIME,:new.ARTEINSTLIVETIME);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colC5B6RPEAWRBJVMM2OVLX3MSGKY',:old.HTTPPROXY,:new.HTTPPROXY);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colMQKXC2RA7BFJTI5YEECPN2JU2I',:old.HTTPSPROXY,:new.HTTPSPROXY);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colD3UDCXDDAJDR7B3YEBXV3TBNAU',:old.USEORAIMPLSTMTCACHE,:new.USEORAIMPLSTMTCACHE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colQW66DBXQ2BFOTAKTX7LRPNLTZY',:old.ORAIMPLSTMTCACHESIZE,:new.ORAIMPLSTMTCACHESIZE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col2ABN5MPEFBGRNERT3MSWLBFILE',:old.USEACTIVEARTELIMITS,:new.USEACTIVEARTELIMITS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col4FNLYMXZMRF7VNKWXW4LAG2VMY',:old.MAXACTIVEARTENORMAL,:new.MAXACTIVEARTENORMAL);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colLXK2TPSGGJDEZK6YZB5HJJC5RI',:old.MAXACTIVEARTEABOVENORMAL,:new.MAXACTIVEARTEABOVENORMAL);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colFWLWDVK6E5FZHA3FOQEMLGSEI4',:old.MAXACTIVEARTEHIGH,:new.MAXACTIVEARTEHIGH);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colOTSOCR6D45FQ5FFHIDN4SYAR7E',:old.MAXACTIVEARTEVERYHIGH,:new.MAXACTIVEARTEVERYHIGH);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col63MN22Q6GRFUVDV2J6UD2I4VOU',:old.MAXACTIVEARTECRITICAL,:new.MAXACTIVEARTECRITICAL);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colMJMKGEQX2FG53KHYXUTIJMMKYE',:old.CLASSLOADINGPROFILEID,:new.CLASSLOADINGPROFILEID);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colP5PSVWUEQBHPTA6CXUPA2UVOWI',:old.AADCMEMBERID,:new.AADCMEMBERID);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colOF6APP4I7FHV7BCQLHO75CZR74',:old.AADCDGADDRESS,:new.AADCDGADDRESS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colM65QF5VLNZD6FPDDMADFENBBUU',:old.AUTORESTARTDELAYSEC,:new.AUTORESTARTDELAYSEC);
   end if;

   vClassGuid := 'aec52CHFNO3EGWDBRCRAAIT4AGD7E';
   insert into RDX_AU_AUDITLOG (ID,EVENTTIME,STOREDURATION,USERNAME,STATIONNAME,TABLEID,CLASSID,PID,EVENTTYPE,EVENTDATA)
   values(SQN_RDX_AU_AUDITLOGID.NextVal,SYSTIMESTAMP,vStoreDuration,RDX_Arte.getUserName,RDX_Arte.getStationName,'tbl52CHFNO3EGWDBRCRAAIT4AGD7E',vClassGuid,vPID,'U',vChangeData);
end;
/

begin
   RDX_AUDIT.updateTableAuditStateEventType('tbl52CHFNO3EGWDBRCRAAIT4AGD7E', 'U','tbl52CHFNO3EGWDBRCRAAIT4AGD7E');
end;
/

create or replace trigger atuX5TD7JDVVHWDBROXAAIT4AGD7E
after update of AADCMEMBERID, AADCTESTEDMEMBERID, ARTECOUNTRY, ARTEDBTRACEPROFILE, ARTEFILETRACEPROFILE, ARTEGUITRACEPROFILE, ARTELANGUAGE, ASKUSERPWDAFTERINACTIVITY, AUDITSTOREPERIOD1, AUDITSTOREPERIOD2, AUDITSTOREPERIOD3, AUDITSTOREPERIOD4, AUDITSTOREPERIOD5, BLOCKUSERINVALIDLOGONCNT, BLOCKUSERINVALIDLOGONMINS, CERTATTRFORUSERLOGIN, DEFAULTAUDITSCHEMEID, DUALCONTROLFORASSIGNROLE, DUALCONTROLFORCFGMGMT, EASKRBPRINCNAME, EASSESSIONACTIVITYMINS, EASSESSIONINACTIVITYMINS, ENABLESENSITIVETRACE, EVENTSTOREDAYS, EXTSYSTEMCODE, FAILEDOUTMESSAGESTOREDAYS, LIMITEASSESSIONSPERUSR, METRICHISTORYSTOREDAYS, NAME, ORAIMPLSTMTCACHESIZE, PCMSTOREDAYS, PROFILELOGSTOREDAYS, PWDEXPIRATIONPERIOD, PWDMINLEN, PWDMUSTBEINMIXEDCASE, PWDMUSTCONTAINACHARS, PWDMUSTCONTAINNCHARS, PWDMUSTCONTAINSCHARS, PWDMUSTDIFFERFROMNAME, TEMPORARYPWDEXPIRATIONPERIOD, UNIQUEPWDSEQLEN, USEORAIMPLSTMTCACHE, WRITECONTEXTTOFILE on RDX_SYSTEM
for each row
disable
declare vStoreDuration integer; vSaveData integer; vPID varchar2(4000); vChangeData clob; vSchemeId varchar2(50); vClassGuid varchar2(50);
begin
   begin
      select RDX_AU_SCHEMEITEM.STOREDURATION, RDX_AU_SCHEMEITEM.SAVEDATA into vStoreDuration, vSaveData
      from RDX_AU_SCHEMEITEM
      where RDX_AU_SCHEMEITEM.SCHEMEGUID=RDX_AUDIT.DEFAULTAUDITSCHEME
         and RDX_AU_SCHEMEITEM.TABLEID = 'tblX5TD7JDVVHWDBROXAAIT4AGD7E'
         and RDX_AU_SCHEMEITEM.EVENTTYPE = 'U';
   exception
      when no_data_found then return;
   end;
   vPID:=:old.ID;
   if vSaveData=1 then
            RDX_AUDIT.addChangedValueInt(vChangeData,'colFRZFQPKGI5EM7DCHTHZ4PSKVCA',:old.EXTSYSTEMCODE,:new.EXTSYSTEMCODE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'col7WZAHHSUZVCAVPPUZDJX5WWCA4',:old.CERTATTRFORUSERLOGIN,:new.CERTATTRFORUSERLOGIN);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colTCOQ4HOZRHWDBRCXAAIT4AGD7E',:old.NAME,:new.NAME);
            RDX_AUDIT.addChangedValueStr(vChangeData,'col546FXWYZJ3NRDJIRACQMTAIZT4',:old.ARTELANGUAGE,:new.ARTELANGUAGE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colWGL2VHS7RNBIRA3NYYV3KGAIPI',:old.ARTECOUNTRY,:new.ARTECOUNTRY);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colMJDA72X3RRHX5AQ4RSCK3YNA44',:old.ARTEGUITRACEPROFILE,:new.ARTEGUITRACEPROFILE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colMYF3QYYJ7BFS7AJ6YRMZUFBE4M',:old.ARTEFILETRACEPROFILE,:new.ARTEFILETRACEPROFILE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colXLSJR3OUKLNRDAQSABIFNQAAAE',:old.ARTEDBTRACEPROFILE,:new.ARTEDBTRACEPROFILE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colM6ABGYQYNVGYRC6NTJ76DIBZ4I',:old.EASSESSIONACTIVITYMINS,:new.EASSESSIONACTIVITYMINS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colLPOXOGA2J3NRDJIRACQMTAIZT4',:old.EASSESSIONINACTIVITYMINS,:new.EASSESSIONINACTIVITYMINS);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colM6KLR5HJ3JDI7DTS5S52SRQEFU',:old.EASKRBPRINCNAME,:new.EASKRBPRINCNAME);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colMBAPYLBLXFEOPBVK2IYG2HSVC4',:old.LIMITEASSESSIONSPERUSR,:new.LIMITEASSESSIONSPERUSR);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colMYUJ6LOEMVDTHCVJ6BTLZ2PTHI',:old.ASKUSERPWDAFTERINACTIVITY,:new.ASKUSERPWDAFTERINACTIVITY);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colCK5BEU6WO5H4VKRDA46ALDEZ3M',:old.UNIQUEPWDSEQLEN,:new.UNIQUEPWDSEQLEN);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col2J4RCA57UBFPFNVYLNMEXJI5CU',:old.PWDMINLEN,:new.PWDMINLEN);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colSLXTNR7MBRF23O655OVBOAL5LA',:old.PWDMUSTDIFFERFROMNAME,:new.PWDMUSTDIFFERFROMNAME);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colTY6XN5X66FD2FIC7ZQVWKRV7YQ',:old.PWDMUSTCONTAINACHARS,:new.PWDMUSTCONTAINACHARS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colEFLQTDCHFZCTFNM77TYMJH35JY',:old.PWDMUSTBEINMIXEDCASE,:new.PWDMUSTBEINMIXEDCASE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colOJXZPIRBDZG6HCJZ4F2JDH7UFI',:old.PWDMUSTCONTAINNCHARS,:new.PWDMUSTCONTAINNCHARS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colPSC5YLHYXJD3ZICERRHVMMWRZI',:old.PWDMUSTCONTAINSCHARS,:new.PWDMUSTCONTAINSCHARS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colIVNUPJC565CXRNA3SBZKHI2LG4',:old.PWDEXPIRATIONPERIOD,:new.PWDEXPIRATIONPERIOD);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col6EXIXL45PZEBZOF2MKFF7RJWSA',:old.TEMPORARYPWDEXPIRATIONPERIOD,:new.TEMPORARYPWDEXPIRATIONPERIOD);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colUMLKGQCFD6VDBNKJAAUMFADAIA',:old.EVENTSTOREDAYS,:new.EVENTSTOREDAYS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colIH2FRGR6EKWDRWGPAAUUN6FMUG',:old.PCMSTOREDAYS,:new.PCMSTOREDAYS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colRJ6YTFHGWPNBDPLGABQJO5ADDQ',:old.AUDITSTOREPERIOD1,:new.AUDITSTOREPERIOD1);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col3J6FBUPGWPNBDPLGABQJO5ADDQ',:old.AUDITSTOREPERIOD2,:new.AUDITSTOREPERIOD2);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col3N6FBUPGWPNBDPLGABQJO5ADDQ',:old.AUDITSTOREPERIOD3,:new.AUDITSTOREPERIOD3);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colTJMVJWXGWPNBDPLGABQJO5ADDQ',:old.AUDITSTOREPERIOD4,:new.AUDITSTOREPERIOD4);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colTNMVJWXGWPNBDPLGABQJO5ADDQ',:old.AUDITSTOREPERIOD5,:new.AUDITSTOREPERIOD5);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colEKZMW4XGWPNBDPLGABQJO5ADDQ',:old.DEFAULTAUDITSCHEMEID,:new.DEFAULTAUDITSCHEMEID);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colDCLAU6NMGVDSNKN7ZPB6SQJE5Y',:old.BLOCKUSERINVALIDLOGONCNT,:new.BLOCKUSERINVALIDLOGONCNT);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colQTEXFSBLXJES3AOB6SXXKNGQQE',:old.BLOCKUSERINVALIDLOGONMINS,:new.BLOCKUSERINVALIDLOGONMINS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colLRLGIOF3DVB2XEFQXLCJLPUYTU',:old.ENABLESENSITIVETRACE,:new.ENABLESENSITIVETRACE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colKDV6X7RAL5DCBO2HENGADFNFTY',:old.PROFILELOGSTOREDAYS,:new.PROFILELOGSTOREDAYS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colE2XLLDK4RVAMFAL7O6XQGRTVNY',:old.METRICHISTORYSTOREDAYS,:new.METRICHISTORYSTOREDAYS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colKQKCWI72DVAO7OFVSNBZ7XN2WQ',:old.USEORAIMPLSTMTCACHE,:new.USEORAIMPLSTMTCACHE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colJN25VAA7SVD5FKDTO47ERVQIDQ',:old.ORAIMPLSTMTCACHESIZE,:new.ORAIMPLSTMTCACHESIZE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colJ7OWNFGW3RCUVIE7PJUK3OO5GI',:old.DUALCONTROLFORASSIGNROLE,:new.DUALCONTROLFORASSIGNROLE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col5QRDG2EULRGM3IGS4RAPZWD2RQ',:old.DUALCONTROLFORCFGMGMT,:new.DUALCONTROLFORCFGMGMT);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col42FD7ZUMLNA77LXG67VMOVRC5I',:old.WRITECONTEXTTOFILE,:new.WRITECONTEXTTOFILE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col66PAXUAEFBGMZPUYOHGU32ZD2Q',:old.FAILEDOUTMESSAGESTOREDAYS,:new.FAILEDOUTMESSAGESTOREDAYS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colM2PT6HH34FHXRHWAOZLL6HQATU',:old.AADCMEMBERID,:new.AADCMEMBERID);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colUWT5OQ6VLRDUXIBQ6CZ5S7O53Q',:old.AADCTESTEDMEMBERID,:new.AADCTESTEDMEMBERID);
   end if;

   vClassGuid := 'aecX5TD7JDVVHWDBROXAAIT4AGD7E';
   insert into RDX_AU_AUDITLOG (ID,EVENTTIME,STOREDURATION,USERNAME,STATIONNAME,TABLEID,CLASSID,PID,EVENTTYPE,EVENTDATA)
   values(SQN_RDX_AU_AUDITLOGID.NextVal,SYSTIMESTAMP,vStoreDuration,RDX_Arte.getUserName,RDX_Arte.getStationName,'tblX5TD7JDVVHWDBROXAAIT4AGD7E',vClassGuid,vPID,'U',vChangeData);
end;
/

begin
   RDX_AUDIT.updateTableAuditStateEventType('tblX5TD7JDVVHWDBROXAAIT4AGD7E', 'U','tblX5TD7JDVVHWDBROXAAIT4AGD7E');
end;
/

