drop trigger atuX5TD7JDVVHWDBROXAAIT4AGD7E
/

alter table RDX_SYSTEM
	add AADCCOMMITEDLOCKEXP NUMBER(9,0) default 600 not null
/

alter table RDX_SYSTEM
	add AADCUNLOCKTABLES VARCHAR2(4000 char) null
/

create or replace trigger atuX5TD7JDVVHWDBROXAAIT4AGD7E
after update of AADCCOMMITEDLOCKEXP, AADCMEMBERID, AADCTESTEDMEMBERID, AADCUNLOCKTABLES, ARTECOUNTRY, ARTEDBTRACEPROFILE, ARTEFILETRACEPROFILE, ARTEGUITRACEPROFILE, ARTELANGUAGE, ASKUSERPWDAFTERINACTIVITY, AUDITSTOREPERIOD1, AUDITSTOREPERIOD2, AUDITSTOREPERIOD3, AUDITSTOREPERIOD4, AUDITSTOREPERIOD5, BLOCKUSERINVALIDLOGONCNT, BLOCKUSERINVALIDLOGONMINS, CERTATTRFORUSERLOGIN, DEFAULTAUDITSCHEMEID, DUALCONTROLFORASSIGNROLE, DUALCONTROLFORCFGMGMT, EASKRBPRINCNAME, EASSESSIONACTIVITYMINS, EASSESSIONINACTIVITYMINS, ENABLESENSITIVETRACE, EVENTSTOREDAYS, EXTSYSTEMCODE, FAILEDOUTMESSAGESTOREDAYS, LIMITEASSESSIONSPERUSR, METRICHISTORYSTOREDAYS, NAME, ORAIMPLSTMTCACHESIZE, PCMSTOREDAYS, PROFILELOGSTOREDAYS, PWDEXPIRATIONPERIOD, PWDMINLEN, PWDMUSTBEINMIXEDCASE, PWDMUSTCONTAINACHARS, PWDMUSTCONTAINNCHARS, PWDMUSTCONTAINSCHARS, PWDMUSTDIFFERFROMNAME, TEMPORARYPWDEXPIRATIONPERIOD, UNIQUEPWDSEQLEN, USEORAIMPLSTMTCACHE, WRITECONTEXTTOFILE on RDX_SYSTEM
for each row
disable
declare vStoreDuration integer; vSaveData integer; vPID varchar2(4000); vChangeData clob; vSchemeId varchar2(50); vClassGuid varchar2(50);
begin
   begin
      select RDX_AU_SCHEMEITEM.STOREDURATION, RDX_AU_SCHEMEITEM.SAVEDATA into vStoreDuration, vSaveData
      from RDX_AU_SCHEMEITEM
      where RDX_AU_SCHEMEITEM.SCHEMEGUID=RDX_AUDIT.DEFAULTAUDITSCHEME
         and RDX_AU_SCHEMEITEM.TABLEID = 'tblX5TD7JDVVHWDBROXAAIT4AGD7E'
         and RDX_AU_SCHEMEITEM.EVENTTYPE = 'U';
   exception
      when no_data_found then return;
   end;
   vPID:=:old.ID;
   if vSaveData=1 then
            RDX_AUDIT.addChangedValueInt(vChangeData,'colFRZFQPKGI5EM7DCHTHZ4PSKVCA',:old.EXTSYSTEMCODE,:new.EXTSYSTEMCODE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'col7WZAHHSUZVCAVPPUZDJX5WWCA4',:old.CERTATTRFORUSERLOGIN,:new.CERTATTRFORUSERLOGIN);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colTCOQ4HOZRHWDBRCXAAIT4AGD7E',:old.NAME,:new.NAME);
            RDX_AUDIT.addChangedValueStr(vChangeData,'col546FXWYZJ3NRDJIRACQMTAIZT4',:old.ARTELANGUAGE,:new.ARTELANGUAGE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colWGL2VHS7RNBIRA3NYYV3KGAIPI',:old.ARTECOUNTRY,:new.ARTECOUNTRY);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colMJDA72X3RRHX5AQ4RSCK3YNA44',:old.ARTEGUITRACEPROFILE,:new.ARTEGUITRACEPROFILE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colMYF3QYYJ7BFS7AJ6YRMZUFBE4M',:old.ARTEFILETRACEPROFILE,:new.ARTEFILETRACEPROFILE);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colXLSJR3OUKLNRDAQSABIFNQAAAE',:old.ARTEDBTRACEPROFILE,:new.ARTEDBTRACEPROFILE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colM6ABGYQYNVGYRC6NTJ76DIBZ4I',:old.EASSESSIONACTIVITYMINS,:new.EASSESSIONACTIVITYMINS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colLPOXOGA2J3NRDJIRACQMTAIZT4',:old.EASSESSIONINACTIVITYMINS,:new.EASSESSIONINACTIVITYMINS);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colM6KLR5HJ3JDI7DTS5S52SRQEFU',:old.EASKRBPRINCNAME,:new.EASKRBPRINCNAME);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colMBAPYLBLXFEOPBVK2IYG2HSVC4',:old.LIMITEASSESSIONSPERUSR,:new.LIMITEASSESSIONSPERUSR);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colMYUJ6LOEMVDTHCVJ6BTLZ2PTHI',:old.ASKUSERPWDAFTERINACTIVITY,:new.ASKUSERPWDAFTERINACTIVITY);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colCK5BEU6WO5H4VKRDA46ALDEZ3M',:old.UNIQUEPWDSEQLEN,:new.UNIQUEPWDSEQLEN);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col2J4RCA57UBFPFNVYLNMEXJI5CU',:old.PWDMINLEN,:new.PWDMINLEN);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colSLXTNR7MBRF23O655OVBOAL5LA',:old.PWDMUSTDIFFERFROMNAME,:new.PWDMUSTDIFFERFROMNAME);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colTY6XN5X66FD2FIC7ZQVWKRV7YQ',:old.PWDMUSTCONTAINACHARS,:new.PWDMUSTCONTAINACHARS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colEFLQTDCHFZCTFNM77TYMJH35JY',:old.PWDMUSTBEINMIXEDCASE,:new.PWDMUSTBEINMIXEDCASE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colOJXZPIRBDZG6HCJZ4F2JDH7UFI',:old.PWDMUSTCONTAINNCHARS,:new.PWDMUSTCONTAINNCHARS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colPSC5YLHYXJD3ZICERRHVMMWRZI',:old.PWDMUSTCONTAINSCHARS,:new.PWDMUSTCONTAINSCHARS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colIVNUPJC565CXRNA3SBZKHI2LG4',:old.PWDEXPIRATIONPERIOD,:new.PWDEXPIRATIONPERIOD);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col6EXIXL45PZEBZOF2MKFF7RJWSA',:old.TEMPORARYPWDEXPIRATIONPERIOD,:new.TEMPORARYPWDEXPIRATIONPERIOD);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colUMLKGQCFD6VDBNKJAAUMFADAIA',:old.EVENTSTOREDAYS,:new.EVENTSTOREDAYS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colIH2FRGR6EKWDRWGPAAUUN6FMUG',:old.PCMSTOREDAYS,:new.PCMSTOREDAYS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colRJ6YTFHGWPNBDPLGABQJO5ADDQ',:old.AUDITSTOREPERIOD1,:new.AUDITSTOREPERIOD1);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col3J6FBUPGWPNBDPLGABQJO5ADDQ',:old.AUDITSTOREPERIOD2,:new.AUDITSTOREPERIOD2);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col3N6FBUPGWPNBDPLGABQJO5ADDQ',:old.AUDITSTOREPERIOD3,:new.AUDITSTOREPERIOD3);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colTJMVJWXGWPNBDPLGABQJO5ADDQ',:old.AUDITSTOREPERIOD4,:new.AUDITSTOREPERIOD4);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colTNMVJWXGWPNBDPLGABQJO5ADDQ',:old.AUDITSTOREPERIOD5,:new.AUDITSTOREPERIOD5);
            RDX_AUDIT.addChangedValueStr(vChangeData,'colEKZMW4XGWPNBDPLGABQJO5ADDQ',:old.DEFAULTAUDITSCHEMEID,:new.DEFAULTAUDITSCHEMEID);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colDCLAU6NMGVDSNKN7ZPB6SQJE5Y',:old.BLOCKUSERINVALIDLOGONCNT,:new.BLOCKUSERINVALIDLOGONCNT);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colQTEXFSBLXJES3AOB6SXXKNGQQE',:old.BLOCKUSERINVALIDLOGONMINS,:new.BLOCKUSERINVALIDLOGONMINS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colLRLGIOF3DVB2XEFQXLCJLPUYTU',:old.ENABLESENSITIVETRACE,:new.ENABLESENSITIVETRACE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colKDV6X7RAL5DCBO2HENGADFNFTY',:old.PROFILELOGSTOREDAYS,:new.PROFILELOGSTOREDAYS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colE2XLLDK4RVAMFAL7O6XQGRTVNY',:old.METRICHISTORYSTOREDAYS,:new.METRICHISTORYSTOREDAYS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colKQKCWI72DVAO7OFVSNBZ7XN2WQ',:old.USEORAIMPLSTMTCACHE,:new.USEORAIMPLSTMTCACHE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colJN25VAA7SVD5FKDTO47ERVQIDQ',:old.ORAIMPLSTMTCACHESIZE,:new.ORAIMPLSTMTCACHESIZE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colJ7OWNFGW3RCUVIE7PJUK3OO5GI',:old.DUALCONTROLFORASSIGNROLE,:new.DUALCONTROLFORASSIGNROLE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col5QRDG2EULRGM3IGS4RAPZWD2RQ',:old.DUALCONTROLFORCFGMGMT,:new.DUALCONTROLFORCFGMGMT);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col42FD7ZUMLNA77LXG67VMOVRC5I',:old.WRITECONTEXTTOFILE,:new.WRITECONTEXTTOFILE);
            RDX_AUDIT.addChangedValueInt(vChangeData,'col66PAXUAEFBGMZPUYOHGU32ZD2Q',:old.FAILEDOUTMESSAGESTOREDAYS,:new.FAILEDOUTMESSAGESTOREDAYS);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colM2PT6HH34FHXRHWAOZLL6HQATU',:old.AADCMEMBERID,:new.AADCMEMBERID);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colUWT5OQ6VLRDUXIBQ6CZ5S7O53Q',:old.AADCTESTEDMEMBERID,:new.AADCTESTEDMEMBERID);
            RDX_AUDIT.addChangedValueInt(vChangeData,'colGS3V2W2ZNNEXJA3CYQJ5O4AFSA',:old.AADCCOMMITEDLOCKEXP,:new.AADCCOMMITEDLOCKEXP);
   end if;

   vClassGuid := 'aecX5TD7JDVVHWDBROXAAIT4AGD7E';
   insert into RDX_AU_AUDITLOG (ID,EVENTTIME,STOREDURATION,USERNAME,STATIONNAME,TABLEID,CLASSID,PID,EVENTTYPE,EVENTDATA)
   values(SQN_RDX_AU_AUDITLOGID.NextVal,SYSTIMESTAMP,vStoreDuration,RDX_Arte.getUserName,RDX_Arte.getStationName,'tblX5TD7JDVVHWDBROXAAIT4AGD7E',vClassGuid,vPID,'U',vChangeData);
end;
/

begin
   RDX_AUDIT.updateTableAuditStateEventType('tblX5TD7JDVVHWDBROXAAIT4AGD7E', 'U','tblX5TD7JDVVHWDBROXAAIT4AGD7E');
end;
/

