drop view RDX_SM_INSTANCESTATEVIEW
/

alter table RDX_SM_INSTANCESTATEHISTORY
	add ANCESTORTHREADID NUMBER(18,0) null
/

create or replace view RDX_SM_INSTANCESTATEVIEW as
select RDX_SM_INSTANCESTATEHISTORY.INSTANCEID as INSTANCEID,
       RDX_SM_INSTANCESTATEHISTORY.REGTIMEMILLIS as REGTIMEMILLIS,
       RDX_SM_INSTANCESTATEHISTORY.THREADID as THREADID,
       RDX_SM_INSTANCESTATEHISTORY.THREADKIND as THREADKIND,
       RDX_SM_INSTANCESTATEHISTORY.FORCED as FORCED,
       RDX_SM_INSTANCESTATEHISTORY.NAME as NAME,
       RDX_SM_INSTANCESTATEHISTORY.UNITID as UNITID,
       RDX_SM_INSTANCESTATEHISTORY.PRIMARYUNITID as PRIMARYUNITID,
       RDX_SM_INSTANCESTATEHISTORY.ARTESEQ as ARTESEQ,
       RDX_SM_INSTANCESTATEHISTORY.ARTESERIAL as ARTESERIAL,
       RDX_SM_INSTANCESTATEHISTORY.DBSID as DBSID,
       RDX_SM_INSTANCESTATEHISTORY.DBSERIAL as DBSERIAL,
       RDX_SM_INSTANCESTATEHISTORY.TRACECONTEXTS as TRACECONTEXTS,
       RDX_SM_INSTANCESTATEHISTORY.CPUDIFFNANOS as CPUDIFFNANOS,
       RDX_SM_INSTANCESTATEHISTORY.DBDIFFNANOS as DBDIFFNANOS,
       RDX_SM_INSTANCESTATEHISTORY.EXTDIFFNANOS as EXTDIFFNANOS,
       RDX_SM_INSTANCESTATEHISTORY.OTHERDIFFNANOS as OTHERDIFFNANOS,
       RDX_SM_INSTANCESTATEHISTORY.UPTIMESEC as UPTIMESEC,
       RDX_SM_INSTANCESTATEHISTORY.STACKDIGEST as STACKDIGEST,
       RDX_SM_STACKDATA.STACKTOP as STACKTOP,
       RDX_SM_STACKDATA.COMPRESSEDSTACK as COMPRESSEDSTACK,
       RDX_Utils.gunzipToClob(RDX_SM_STACKDATA.COMPRESSEDSTACK) as STACK,
       RDX_SM_INSTANCESTATEHISTORY.LOCKNAME as LOCKNAME,
       RDX_SM_INSTANCESTATEHISTORY.LOCKOWNERNAME as LOCKOWNERNAME,
       RDX_SM_INSTANCESTATEHISTORY.RQSTARTTIMEMILLIS as RQSTARTTIMEMILLIS,
       RDX_SM_INSTANCESTATEHISTORY.EXTDATA as EXTDATA,
       RDX_SM_INSTANCESTATEHISTORY.ANCESTORTHREADID as ANCESTORTHREADID
from RDX_SM_INSTANCESTATEHISTORY, RDX_SM_STACKDATA
where RDX_SM_INSTANCESTATEHISTORY.STACKDIGEST = RDX_SM_STACKDATA.DIGEST(+)
/

grant select, delete on RDX_SM_INSTANCESTATEVIEW to &USER&_RUN_ROLE
/

