alter table RDX_SM_INSTANCESTATEHISTORY
	modify (LOCKNAME VARCHAR2(400 char))
/

alter table RDX_SM_INSTANCESTATEHISTORY
	modify (LOCKOWNERNAME VARCHAR2(400 char))
/

alter table RDX_SM_INSTANCESTATEHISTORY
	modify (TRACECONTEXTS VARCHAR2(1000 char))
/

