alter table RDX_PC_OUTMESSAGE
	add DELIVERYEXPTIMEMILLIS NUMBER(18,0) null
/


alter table RDX_PC_SENTMESSAGE
	add ADDRESSFROM VARCHAR2(1000 char) null
/

alter table RDX_PC_SENTMESSAGE
	add INITIALDUETIME TIMESTAMP(6) null
/

