rename RDX_QUEUEDELAYEDMESS to RDX_QUEUESAFMESS
/

grant select, update, insert, delete on RDX_QUEUESAFMESS to &USER&_RUN_ROLE
/

rename RDX_QUEUEPARTITIONDELAY to RDX_QUEUESAFPARTITION
/

grant select, update, insert, delete on RDX_QUEUESAFPARTITION to &USER&_RUN_ROLE
/

alter table RDX_QUEUESAFPARTITION rename column DELAY to SAFMODE
/

alter index IDX_RDX_QUEUEDELAYEDMESS_QUEUE rename to IDX_RDX_QUEUESAFMESS_QUEUEPART
/

alter index PK_RDX_QUEUEDELAYEDMESS rename to PK_RDX_QUEUESAFMESS
/

alter index PK_RDX_QUEUEPARTITIONDELAY rename to PK_RDX_QUEUESAFPARTITION
/

alter table RDX_QUEUESAFMESS rename constraint PK_RDX_QUEUEDELAYEDMESS to PK_RDX_QUEUESAFMESS
/

alter table RDX_QUEUESAFPARTITION rename constraint PK_RDX_QUEUEPARTITIONDELAY to PK_RDX_QUEUESAFPARTITION
/

alter table RDX_QUEUESAFMESS rename constraint FK_RDX_QUEUEDELAYEDMESS_MESSAG to FK_RDX_QUEUESAFMESS_MESSAGEQUE
/

