/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * LangsPanel.java
 *
 * Created on Sep 7, 2009, 11:08:05 AM
 */
package org.radixware.kernel.designer.ads.localization.dialog;

import java.awt.BorderLayout;
import java.util.List;
import java.util.Map;
import org.openide.util.NbBundle;
import org.radixware.kernel.common.defs.Module;
import org.radixware.kernel.common.enums.EIsoLanguage;
import org.radixware.kernel.common.repository.Layer;
import org.radixware.kernel.designer.common.dialogs.components.state.StateAbstractDialog.StateAbstractPanel;


public class ChooseLanguagesDialog extends StateAbstractPanel {
    //private List<EIsoLanguage> sourceLangs;
    //private List<EIsoLanguage> translLangs;

    private final ChooseLanguagesPanelNew p;
    //private final LayerPanel layerPanel;
    private final org.radixware.kernel.designer.common.dialogs.components.state.StateDisplayer stateDisplayer;

    /**
     * Creates new form LangsPanel
     */
    public ChooseLanguagesDialog(final List<EIsoLanguage> sourceLangs, final List<EIsoLanguage> translLangs) {
        //this.sourceLangs=sourceLangs;
        //this.translLangs=translLangs;
        stateDisplayer = new org.radixware.kernel.designer.common.dialogs.components.state.StateDisplayer();
        initComponents();

        p = new ChooseLanguagesPanelNew(sourceLangs, translLangs);
        this.add(p,BorderLayout.CENTER);
        this.add(stateDisplayer,BorderLayout.SOUTH);
    }

    /*public void  setSourceLangs() {
     sourceLangs=p.getSourceLangs();
     }

     public void  setTranslatedLangs() {
     translLangs=p.getTargetLangs();
     }*/
    public List<EIsoLanguage> getSourceLangs() {
        return p.getSourceLangs();
    }

    public List<EIsoLanguage> getTranslatedLangs() {
        return p.getTargetLangs();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAlignmentY(0.0F);
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void check() {
        //setSourceLangs();
        //setTranslatedLangs();
        if ((getSourceLangs() == null) || (getSourceLangs().isEmpty())) {
            stateManager.error(NbBundle.getMessage(ChooseLanguagesDialog.class, "SRC_LANGS_NOT_SELECTED"));
        } else if ((getTranslatedLangs() == null) || (getTranslatedLangs().isEmpty())) {
            stateManager.error(NbBundle.getMessage(ChooseLanguagesDialog.class, "TRANSLATE_LANGSNOT_SELECTED"));
        } else if (!checkLangs(getSourceLangs(), getTranslatedLangs())) {
            stateManager.error(NbBundle.getMessage(ChooseLanguagesDialog.class, "SAME_LANGS"));
        } else {
            stateManager.ok();
        }
        /*if((sourceLangs!=null)&&(sourceLangs.size()>0)&&(translLangs!=null)&&(translLangs.size()>0)){
         stateManager.ok();
         }else{
         stateManager.error("Language is not selection");
         }*/
        changeSupport.fireChange();
    }

    private boolean checkLangs(final List<EIsoLanguage> sourceLangs, final List<EIsoLanguage> targetLangs) {
        for (EIsoLanguage lang : sourceLangs) {
            if (targetLangs.contains(lang)) {
                return false;
            }
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
