/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * MainStatisticsPanel.java
 *
 * Created on Oct 1, 2009, 1:29:03 PM
 */

package org.radixware.kernel.designer.ads.localization.dialog;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import org.radixware.kernel.designer.ads.localization.dialog.StatisticsPanel.StatisticsInfo;


public class StatisticsDiagramPanel  extends javax.swing.JPanel {
    private final StatisticsInformationPanel infop;
    private final StatisticsImagePanel img;

    /** Creates new form MainStatisticsPanel */
    public StatisticsDiagramPanel() {
        initComponents();
        infop= new StatisticsInformationPanel();
        img=new StatisticsImagePanel();
        infop.setBorder(new EmptyBorder(0,0,0,10));
        this.add(img);
        this.add(infop);
        
    }

    public void open(final List<StatisticsInfo> statistic){
        infop.open(statistic);
        img.open(statistic);
        
//        int width=img.getPreferredSize().width+infop.getPreferredSize().width+10;
//        this.setPreferredSize(new Dimension(width,this.getPreferredSize().height));
//        this.setMinimumSize(new Dimension(width,this.getPreferredSize().height));
        revalidate();
        repaint();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(StatisticsDiagramPanel.class, "StatisticsDiagramPanel.border.title"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(10000, 10000));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
        getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(StatisticsDiagramPanel.class, "StatisticsDiagramPanel.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
