/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * ViewHtmlDialog.java
 *
 * Created on Nov 19, 2009, 4:35:04 PM
 */

package org.radixware.kernel.designer.ads.localization.dialog;

import java.util.List;
import org.radixware.kernel.common.enums.EIsoLanguage;
import org.radixware.kernel.designer.ads.localization.RowString;


public class ViewHtmlDialog extends javax.swing.JPanel {

    //private List<EIsoLanguage> sourceLangs;
    //private List<EIsoLanguage> translLangs;

    /** Creates new form ViewHtmlDialog */
    public ViewHtmlDialog(final RowString rowString,final List<EIsoLanguage> sourceLangs,final List<EIsoLanguage> translLangs) {
        //this.sourceLangs=sourceLangs;
        //this.translLangs=translLangs;
        initComponents();
        
        for(EIsoLanguage lang:sourceLangs){
            final ViewHtmlPanel panel=new ViewHtmlPanel(rowString.getValue(lang));
            topTabPanel.addTab(lang.getName(), panel);
        }
        for(EIsoLanguage lang:translLangs){
            final ViewHtmlPanel panel=new ViewHtmlPanel(rowString.getValue(lang));
            bottomTabPanel.addTab(lang.getName(), panel);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        topTabPanel = new javax.swing.JTabbedPane();
        bottomTabPanel = new javax.swing.JTabbedPane();

        splitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPanel.setResizeWeight(0.5);
        splitPanel.setTopComponent(topTabPanel);
        splitPanel.setRightComponent(bottomTabPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane bottomTabPanel;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JTabbedPane topTabPanel;
    // End of variables declaration//GEN-END:variables

}
