/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */
package org.radixware.kernel.common.design.msdleditor.field.panel.simple;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;
import org.radixware.kernel.common.enums.EMsdlTimeZoneType;

public class DateTimeZonePanel extends AbstractEditItem implements ActionListener {

    private EMsdlTimeZoneType defaultParentValue = EMsdlTimeZoneType.LOCAL;
    private EMsdlTimeZoneType parentValue;
    private ActionListener al;

    public DateTimeZonePanel() {
        initComponents();
        jComboBoxUnit.setModel(new DefaultComboBoxModel(EMsdlTimeZoneType.values()));
        setParentPanel.addActionListener(this);
        jComboBoxUnit.addActionListener(this);
    }

    public void addActionListener(final ActionListener l) {
        al = l;
    }

    public void removeActionListener(final ActionListener l) {
        al = null;
    }

    public void setDefaultParentValue(EMsdlTimeZoneType value) {
        defaultParentValue = value;
    }

    public void setValue(EMsdlTimeZoneType value, EMsdlTimeZoneType parentValue) {
        if (parentValue == null && defaultParentValue != null) {
            parentValue = defaultParentValue;
        }
        this.parentValue = parentValue;
        getSetParentPanel().setSelected(false);
        setValueImpl(value);
        getSetParentPanel().setEnabled(parentValue != null);
        if (value == null) {
            getSetParentPanel().setSelected(parentValue != null);
            setValueImpl(parentValue);
            jComboBoxUnit.setEnabled(parentValue == null);
        }
    }

    private void setValueImpl(EMsdlTimeZoneType val) {
        if (val != null) {
            jComboBoxUnit.getModel().setSelectedItem(val);
        }
    }

    public EMsdlTimeZoneType getValue() {
        if (getSetParentPanel().getSelected()) {
            return null;
        } else {
            return (EMsdlTimeZoneType) jComboBoxUnit.getModel().getSelectedItem();
        }
    }

    public SetParentPanel getSetParentPanel() {
        return setParentPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBoxUnit = new javax.swing.JComboBox();
        setParentPanel = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel();

        setPreferredSize(new java.awt.Dimension(200, 20));
        setLayout(new java.awt.GridBagLayout());

        jComboBoxUnit.setPreferredSize(new java.awt.Dimension(1000, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        add(jComboBoxUnit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(setParentPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxUnit;
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel setParentPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JCheckBox) {
            if (setParentPanel.getSelected()) {
                setValueImpl(parentValue);
                jComboBoxUnit.setEnabled(false);
            } else {
                jComboBoxUnit.setEnabled(true);
            }
        }
        if (al != null) {
            al.actionPerformed(new ActionEvent(this, 0, null));
        }
    }
}
