/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * AlignPanel.java
 *
 * Created on 22.01.2009, 11:21:49
 */

package org.radixware.kernel.common.design.msdleditor.field.panel.simple;

import java.awt.event.ActionListener;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;
import org.radixware.kernel.common.design.msdleditor.enums.ESelfInclusive;


public class SelfInclusivePanel extends AbstractEditItem {

    private ESelfInclusive parentValue;
    public static class SelfInclusiveModel extends DefaultComboBoxModel {
        public SelfInclusiveModel() {
            super(new ESelfInclusive[]{ESelfInclusive.NOTDEFINED,ESelfInclusive.INCLUSIVE,ESelfInclusive.NOTINCLUSIVE});
        }
    }

    /** Creates new form AlignPanel */
    public SelfInclusivePanel() {
        initComponents();
        setModel(new SelfInclusiveModel());
    }

    public void addActionListener(final ActionListener l) {
        jComboBoxUnit.addActionListener(l);
    }

    public void removeActionListener(final ActionListener l) {
        jComboBoxUnit.removeActionListener(l);
    }


    public void setModel(ComboBoxModel model) {
        jComboBoxUnit.setModel(model);
    }

    public void setSelfInclusive(ESelfInclusive value, ESelfInclusive parentValue) {
        this.parentValue = parentValue;
        getSetParentPanel().setSelected(false);
        jComboBoxUnit.getModel().setSelectedItem(value);
        getSetParentPanel().setEnabled(parentValue != ESelfInclusive.NOTDEFINED);
        if (value == ESelfInclusive.NOTDEFINED) {
            getSetParentPanel().setSelected(parentValue != ESelfInclusive.NOTDEFINED);
            jComboBoxUnit.getModel().setSelectedItem(parentValue);
            jComboBoxUnit.setEnabled(parentValue == ESelfInclusive.NOTDEFINED);
        }
    }

    public ESelfInclusive getSelfInclusive() {
        if (getSetParentPanel().getSelected()) {
            jComboBoxUnit.getModel().setSelectedItem(parentValue);
            jComboBoxUnit.setEnabled(false);
            return ESelfInclusive.NOTDEFINED;
        }
        else {
            jComboBoxUnit.setEnabled(true);
            ESelfInclusive result = (ESelfInclusive)jComboBoxUnit.getModel().getSelectedItem();
            if (result == ESelfInclusive.NOTDEFINED && parentValue != ESelfInclusive.NOTDEFINED) {
                jComboBoxUnit.getModel().setSelectedItem(parentValue);
                jComboBoxUnit.setEnabled(false);
                getSetParentPanel().setSelected(true);
            }
            return result;
        }
    }

    public SetParentPanel getSetParentPanel() {
        return setParentPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBoxUnit = new javax.swing.JComboBox();
        setParentPanel = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel();

        setPreferredSize(new java.awt.Dimension(800, 24));
        setLayout(new java.awt.GridBagLayout());

        jComboBoxUnit.setPreferredSize(new java.awt.Dimension(1000, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        add(jComboBoxUnit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(setParentPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxUnit;
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel setParentPanel;
    // End of variables declaration//GEN-END:variables

}
