/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * AlignPanel.java
 *
 * Created on 22.01.2009, 11:21:49
 */

package org.radixware.kernel.common.design.msdleditor.field.panel.simple;

import java.awt.event.ActionListener;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;
import org.radixware.kernel.common.design.msdleditor.enums.EUnit;


public class UnitPanel extends AbstractEditItem {

    private EUnit parentValue;
    public static class UnitModel extends DefaultComboBoxModel {
        public UnitModel() {
            super(new EUnit[]{EUnit.NOTDEFINED,EUnit.BYTE,EUnit.CHAR,EUnit.ELEMENT});
        }
    }

    /** Creates new form AlignPanel */
    public UnitPanel() {
        initComponents();
        setAlignModel(new UnitModel());
    }

    public void addActionListener(final ActionListener l) {
        jComboBoxUnit.addActionListener(l);
    }

    public void removeActionListener(final ActionListener l) {
        jComboBoxUnit.removeActionListener(l);
    }


    public void setAlignModel(ComboBoxModel model) {
        jComboBoxUnit.setModel(model);
    }

    public void setUnit(EUnit value, EUnit parentValue) {
        this.parentValue = parentValue;
        getSetParentPanel().setSelected(false);
        jComboBoxUnit.getModel().setSelectedItem(value);
        getSetParentPanel().setEnabled(parentValue != EUnit.NOTDEFINED);
        if (value == EUnit.NOTDEFINED) {
            getSetParentPanel().setSelected(parentValue != EUnit.NOTDEFINED);
            jComboBoxUnit.getModel().setSelectedItem(parentValue);
            jComboBoxUnit.setEnabled(parentValue == EUnit.NOTDEFINED);
        }
    }

    public EUnit getUnit() {
        if (getSetParentPanel().getSelected()) {
            jComboBoxUnit.getModel().setSelectedItem(parentValue);
            jComboBoxUnit.setEnabled(false);
            return EUnit.NOTDEFINED;
        }
        else {
            jComboBoxUnit.setEnabled(true);
            EUnit result = (EUnit)jComboBoxUnit.getModel().getSelectedItem();
            if (result == EUnit.NOTDEFINED && parentValue != EUnit.NOTDEFINED) {
                jComboBoxUnit.getModel().setSelectedItem(parentValue);
                jComboBoxUnit.setEnabled(false);
                getSetParentPanel().setSelected(true);
            }
            return result;
        }
    }

    public EUnit getViewedUnit() {
        return (EUnit)jComboBoxUnit.getModel().getSelectedItem();
    }

    public SetParentPanel getSetParentPanel() {
        return setParentPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxUnit = new javax.swing.JComboBox();
        setParentPanel = new org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel();

        setPreferredSize(new java.awt.Dimension(100, 24));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(jComboBoxUnit);
        add(setParentPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxUnit;
    private org.radixware.kernel.common.design.msdleditor.field.panel.simple.SetParentPanel setParentPanel;
    // End of variables declaration//GEN-END:variables

}
