/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

package org.radixware.kernel.designer.ads.editors.clazz.algo;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.Collections;
import java.util.List;
import org.radixware.kernel.common.defs.RadixObject;
import org.radixware.kernel.common.defs.ads.clazz.algo.AdsAlgoClassDef;
import org.radixware.kernel.designer.common.annotations.registrators.EditorFactoryRegistration;
import org.radixware.kernel.designer.common.editors.RadixObjectEditor;
import org.radixware.kernel.designer.common.general.editors.IEditorFactory;
import org.radixware.kernel.designer.common.general.editors.IRadixObjectEditor;
import org.radixware.kernel.designer.common.general.editors.OpenInfo;


public class AdsAlgoClassEditor extends RadixObjectEditor<AdsAlgoClassDef> {

    private boolean initialized = false;
    private AdsAlgoEditorTabbedPane tabbedPanel = null;

    @EditorFactoryRegistration
    public static final class Factory implements IEditorFactory<AdsAlgoClassDef> {

        @Override
        public IRadixObjectEditor<AdsAlgoClassDef> newInstance(AdsAlgoClassDef algoClass) {
            return new AdsAlgoClassEditor(algoClass);
        }
    }

    /** Creates new form AdsClassEditorView */
    protected AdsAlgoClassEditor(AdsAlgoClassDef algoClass) {
        super(algoClass);
        initComponents();
    }

    @Override
    public Dimension getPreferredSize() {
        return super.getPreferredSize();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    public AdsAlgoClassDef getAlgoClass() {
        return getRadixObject();
    }

    @Override
    @SuppressWarnings("unchecked")
    public boolean open(OpenInfo info) {
        final AdsAlgoClassDef algoClass = getAlgoClass();

        //invoking first time?
        if (!initialized) {
            initialized = true;

            tabbedPanel = new AdsAlgoEditorTabbedPane();
            this.add(tabbedPanel,BorderLayout.CENTER);

            tabbedPanel.open(algoClass, info);
        }

        setReadonly(algoClass.isReadOnly());
        
        List<RadixObject> empty = Collections.emptyList();
        notifySelectionChanged(empty);

        return super.open(info);
    }

    @Override
    public void update() {
        tabbedPanel.update();
    }

    public void setReadonly(boolean readonly) {
        tabbedPanel.setReadonly(readonly);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
