/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * TitledPiecePanel.java
 *
 * Created on 19.03.2009, 18:16:47
 */

package org.radixware.kernel.common.design.msdleditor.piece;

import org.radixware.kernel.common.design.msdleditor.AbstractEditItem;
import org.radixware.kernel.common.msdl.fields.AbstractFieldModel;
import org.radixware.schemas.msdl.Piece;


public class TitledPiecePanel extends AbstractEditItem {

    /** Creates new form TitledPiecePanel */
    public TitledPiecePanel() {
        initComponents();
    }

    public void setTitle(String title) {
        jLabelTitle.setText(title);
    }
    public void open(AbstractFieldModel field, Piece piece) {
        super.open(field.getMsdlField());
        piecePanel1.open(field, piece);
        update();
    }

    @Override
    public void update() {
        update(false);
    }
    
    public void update(boolean updateContent) {
        piecePanel1.update(updateContent);
        super.update();
    }

    @Override
    public void setVisible(boolean flag) {
        piecePanel1.setVisible(flag);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piecePanel1 = new org.radixware.kernel.common.design.msdleditor.piece.PiecePanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());
        add(piecePanel1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Field Format");
        jLabelTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabelTitle.setFocusable(false);
        jPanel1.add(jLabelTitle, java.awt.BorderLayout.NORTH);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private org.radixware.kernel.common.design.msdleditor.piece.PiecePanel piecePanel1;
    // End of variables declaration//GEN-END:variables

}
