/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * AdsCommandCommonPropertiesPanel.java
 *
 * Created on Jan 30, 2009, 2:09:56 PM
 */

package org.radixware.kernel.designer.ads.editors.command.components;

import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.radixware.kernel.common.defs.ads.command.AdsCommandDef;


public class AdsCommandCommonPropertiesPanel extends javax.swing.JPanel{

    private AdsCommandDef command;

    private BasicPropertiesPanel basicPropsEditor = new BasicPropertiesPanel();
    private ContextualPropertiesPanel contextualPropsEditor = new ContextualPropertiesPanel();
    private DataEditor dataEditor = new DataEditor();
    /** Creates new form AdsCommandCommonPropertiesPanel */
    public AdsCommandCommonPropertiesPanel() {
        initComponents();
        GridBagLayout gbl = new GridBagLayout();
        GridBagConstraints c = new GridBagConstraints();
        javax.swing.JPanel content = new javax.swing.JPanel();
        content.setLayout(gbl);

        c.fill = GridBagConstraints.HORIZONTAL;
        c.weightx = 1.0;
        c.insets = new Insets(0, 0, 0, 0);
        gbl.setConstraints(basicPropsEditor, c);
        content.add(basicPropsEditor);

        c.gridy = 1;
        c.insets = new Insets(0, 0, 10, 0);
        gbl.setConstraints(contextualPropsEditor, c);
        content.add(contextualPropsEditor);

        c.gridy = 2;
        gbl.setConstraints(dataEditor, c);
        content.add(dataEditor);

        this.setLayout(new BorderLayout());
        this.add(content, BorderLayout.NORTH);
        setupListeners();
    }

    private void setupListeners(){
        ChangeListener localChangeListener = new ChangeListener(){

            @Override
            public void stateChanged(ChangeEvent e) {
                AdsCommandCommonPropertiesPanel.this.dataEditor.update();
                AdsCommandCommonPropertiesPanel.this.basicPropsEditor.update();
            }

        };
        contextualPropsEditor.addChangeListener(localChangeListener);
    }

    public void open(final AdsCommandDef command){
        this.command = command;
        basicPropsEditor.open(command);
        contextualPropsEditor.open(command);
        dataEditor.open(command);
    }

    public void update(){
        basicPropsEditor.update();
        contextualPropsEditor.update();
        dataEditor.update();
    }
    
    public DataEditor getDataTypeEditor(){
        return dataEditor;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName(org.openide.util.NbBundle.getMessage(AdsCommandCommonPropertiesPanel.class, "AdsCommand-CommonProps")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
