/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * AdsReportChartCellCreatureSetupStep1Visual.java
 *
 * Created on May 24, 2012, 6:32:40 PM
 */
package org.radixware.kernel.designer.ads.editors.clazz.report.chart;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ChangeListener;
import org.openide.util.ChangeSupport;
import org.radixware.kernel.common.defs.ads.clazz.sql.report.AdsReportChartCell;
import org.radixware.kernel.common.enums.EReportChartCellType;



public class AdsReportChartCellSetupStep1Panel extends javax.swing.JPanel {

    private EReportChartCellType chartType= EReportChartCellType.CATEGORY;
    
    /** Creates new form AdsReportChartCellCreatureSetupStep1Visual */
    public AdsReportChartCellSetupStep1Panel() {
        initComponents();
        rbCategoryChart.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(final ActionEvent e) {
                chartType = EReportChartCellType.CATEGORY;
            }
        });        
        rbXYChart.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(final ActionEvent e) {
                chartType = EReportChartCellType.XY;
            }
        });
        
        rbPieChart.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(final ActionEvent e) {
                chartType = EReportChartCellType.PIE;
            }
        });
        rbCategoryChart.setSelected(true);
    }
    
    public EReportChartCellType getChartType(){
        return chartType;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbCategoryChart = new javax.swing.JRadioButton();
        rbXYChart = new javax.swing.JRadioButton();
        rbPieChart = new javax.swing.JRadioButton();

        buttonGroup1.add(rbCategoryChart);
        rbCategoryChart.setText(org.openide.util.NbBundle.getMessage(AdsReportChartCellSetupStep1Panel.class, "AdsReportChartCellSetupStep1Panel.rbCategoryChart.text")); // NOI18N

        buttonGroup1.add(rbXYChart);
        rbXYChart.setText(org.openide.util.NbBundle.getMessage(AdsReportChartCellSetupStep1Panel.class, "AdsReportChartCellSetupStep1Panel.rbXYChart.text")); // NOI18N

        buttonGroup1.add(rbPieChart);
        rbPieChart.setText(org.openide.util.NbBundle.getMessage(AdsReportChartCellSetupStep1Panel.class, "AdsReportChartCellSetupStep1Panel.rbPieChart.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCategoryChart)
                    .addComponent(rbXYChart)
                    .addComponent(rbPieChart))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCategoryChart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbXYChart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPieChart)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rbCategoryChart;
    private javax.swing.JRadioButton rbPieChart;
    private javax.swing.JRadioButton rbXYChart;
    // End of variables declaration//GEN-END:variables


    private final ChangeSupport changeSupport = new ChangeSupport(this);

    public void removeChangeListener(final ChangeListener listener) {
        changeSupport.removeChangeListener(listener);
    }

    public void fireChange() {
        changeSupport.fireChange();
    }

    public void addChangeListener(final ChangeListener listener) {
        changeSupport.addChangeListener(listener);
    }


    public void open(final AdsReportChartCell cell) {

    }

    boolean isComplete() {
        return true;
    }
}
