/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * ValueAxisLabelPosition.java
 *
 * Created on Jun 7, 2012, 4:18:39 PM
 */
package org.radixware.kernel.designer.ads.editors.clazz.report.chart;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import org.radixware.kernel.common.defs.ads.clazz.sql.report.AdsReportChartAxis;
import org.radixware.kernel.common.enums.EReportChartAxisLabelPositions;


public class ValueAxisLabelPosition extends  AbstractAxisLabelPositionPanel {
    private AdsReportChartAxis axis;

    /** Creates new form ValueAxisLabelPosition */
    public ValueAxisLabelPosition() {
        initComponents();
        rbHorizontal.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(final ItemEvent e) {
               if(axis!=null && rbHorizontal.isSelected()){
                   axis.setAxisLabelPosition(EReportChartAxisLabelPositions.STANDARD);
               } 
            }
        });
        rbVertical.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(final ItemEvent e) {
               if(axis!=null && rbVertical.isSelected()){
                   axis.setAxisLabelPosition(EReportChartAxisLabelPositions.UP_90);
               } 
            }
        }); 
    }
    
    private void setPanelEnabled(final boolean enabled){
        rbVertical.setEnabled(enabled);
        rbHorizontal.setEnabled(enabled); 
        this.setEnabled(enabled);
    }
    
    @Override
    public void setAxis(final AdsReportChartAxis axis){
        this.axis=axis;
         setPanelEnabled(axis!=null);
         if(axis!=null){
             if(axis.getAxisLabelPosition()==EReportChartAxisLabelPositions.STANDARD){
                 rbHorizontal.setSelected(true);
             }else{
                 rbVertical.setSelected(true);
             }
         }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbHorizontal = new javax.swing.JRadioButton();
        rbVertical = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ValueAxisLabelPosition.class, "ValueAxisLabelPosition.border.title"))); // NOI18N

        buttonGroup1.add(rbHorizontal);
        rbHorizontal.setText(org.openide.util.NbBundle.getMessage(ValueAxisLabelPosition.class, "ValueAxisLabelPosition.rbHorizontal.text")); // NOI18N

        buttonGroup1.add(rbVertical);
        rbVertical.setText(org.openide.util.NbBundle.getMessage(ValueAxisLabelPosition.class, "ValueAxisLabelPosition.rbVertical.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbHorizontal)
                    .addComponent(rbVertical))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rbHorizontal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbVertical)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rbHorizontal;
    private javax.swing.JRadioButton rbVertical;
    // End of variables declaration//GEN-END:variables
}
