/*
 * Copyright (c) 2008-2015, Compass Plus Limited. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. This Source Code is distributed
 * WITHOUT ANY WARRANTY; including any implied warranties but not limited to
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Mozilla Public License, v. 2.0. for more details.
 */

/*
 * DbTypePanel.java
 *
 * Created on Feb 2, 2011, 4:13:12 PM
 */
package org.radixware.kernel.designer.ads.editors.property;

import java.awt.BorderLayout;
import javax.swing.AbstractSpinnerModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.radixware.kernel.common.defs.ads.clazz.members.AdsPropertyDef;
import org.radixware.kernel.common.defs.ads.clazz.members.DbPropertyValue;
import org.radixware.kernel.common.defs.ads.clazz.members.PropertyValue;
import org.radixware.kernel.designer.common.editors.DbTypePanel;


public class DbTypePanelWrapper extends javax.swing.JPanel {



    /** Creates new form DbTypePanel */
    public DbTypePanelWrapper() {
        initComponents();
        add(internal, BorderLayout.CENTER);
    }
    private DbPropertyValue value = null;

    public void open(AdsPropertyDef prop) {
        PropertyValue val = prop.getValue();
        if (val instanceof DbPropertyValue) {
            value = (DbPropertyValue) val;
            internal.open(value);
        } else {
            setVisible(false);
        }
    }

    public void update() {
        if (value != null) {
            internal.update();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internal = new org.radixware.kernel.designer.common.editors.DbTypePanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DbTypePanelWrapper.class, "DbTypePanelWrapper.border.title"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(internal, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(internal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.radixware.kernel.designer.common.editors.DbTypePanel internal;
    // End of variables declaration//GEN-END:variables
}
